### ISSUE TITLE
Is there another way?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#126]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1128

**Comment by tschaffter** [comment]
@brucehoff In the configuration of Synapse Docker repository, have you came across a "TLS handshake timeout" setting? If yes, would you agree to double the value?

This may help the participant, but his internet connection doesn't seem reliable. Using Google DNS seems to have helped a bit. He has a slow internet connection so I'll see with him if it's an option to work remotely on another machine and then `docker push`from there.
