### ISSUE TITLE
Use more intuitive job status

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#13]
Use more intuitive job status (EVALUATING -> RUNNING, ACCEPTED -> COMPLETED, etc.)
Moreover, display a list of all the status and their meaning at the bottom of the Dashboard

**Comment by tschaffter** [comment]
@brucehoff Can we close this ticket?

**Comment by brucehoff** [comment]
> @brucehoff Can we close this ticket?
Yes, the 'Status Detail' column in the personalized dashboard is meant to fill this need.
