### ISSUE TITLE
truncated log file

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#132]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1141

**Comment by brucehoff** [comment]
Tom:  When you address questions like this it will help to know that we limit the size up uploaded log files to 1MB.    

Here's how you look up the log file:
The submission ID (as you can see in the issue is 7440486).  You can then look up the submission ID on this page:
https://www.synapse.org/#!Synapse:syn5644795/wiki/405302
There's a column in the 'leader board' for Submission Folder.  For this submission it's:
https://www.synapse.org/#!Synapse:syn7444792
In that folder is the log file:
https://www.synapse.org/#!Synapse:syn7444793
and the portal shows the file size is 2.707 KB, so in this case it's NOT that we limited the log file.  Back in the leader board you see that the issue status is CLOSED.  It terminated with an error which is probably the cause of the short log file.

**Comment by thomasyu888** [comment]
I don't have access to the view the log file.  Please kindly give me access so I can take a look.

**Comment by brucehoff** [comment]
Tom:  Can you click "request access from the owner" on the entity page?  If that route does not work, please let me know.

**Comment by thomasyu888** [comment]
I still cannot access that page.

**Comment by brucehoff** [comment]
Thomas:  My mistake -- each submission folder has its own ACL, so giving you access at the 'parent folder' level didn't work.  I just gave you access to the particular folder you need to see.  If you need to see others I'll add you to their ACLs too.

**Comment by brucehoff** [comment]
Something odd is going on.  I am investigating.

**Comment by brucehoff** [comment]
I have done a 'deep dive' into the problem and determined that the participant is hitting our 1MB maximum log file size.  I have responded on the forum.
