### ISSUE TITLE
Advanced log file limit

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#138]
implement a limit on log files that considers more than one submission in order to prevent someone from downloading significant amounts of data by using a large volume of submissions.

One approach is to have a daily limit rather than a per-submission limit. This could be coupled with a round limit.   E.g. you could have 5MB/day, and 35 days/round with the add'l constraint of 50MB/round (much less than the 175 MB/round that you'd otherwise have).

**Comment by tschaffter** [comment]
The log size limit must be per day and not per round.
Closing as this thread is a duplicated of #6.
