### ISSUE TITLE
Tell the participants when the log file size limit is reached

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#14]
See Issue #6 

Add a notification to the dashboard when the log file is no longer returned because the size limit of X MB has been reached. The participant must be informed so that he can decide to stop the job.

Send also a notification email to the participant.

**Comment by brucehoff** [comment]
This is subsumed by https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/6
