### ISSUE TITLE
Ensure prediction (scoring) jobs have sufficient scratch space

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#151]
Can we insist that the submitted code process images 'on the fly' or do we need to support batch preprocessing of images before starting prediction?

**Comment by tschaffter** [comment]
We will not provide a scratch space similar to /preprocessedData during the scoring phase. We want to request that the inference methods must process one subject at a time (and most importantly reset the random seed before processing each new subject).

Action: document this aspect of the scoring

**Comment by tschaffter** [comment]
Done
