### ISSUE TITLE
Design leader board

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#152]
What should the columns of the scoring leaderboard be? (Note, this is distinct from the training 'dashboard'.)

**Comment by tschaffter** [comment]
Tentative columns:

- Submitting entity (obfuscated?)
- AUROC
- p-AUROC
- rank

**Comment by tschaffter** [comment]
@thomasyu888 Are the SC1 and SC2 "live" leaderboard tables ready?
