### ISSUE TITLE
Automatic checking that predictions are independent

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#153]
We should 'spot check' that submitted predictors operate independently on each subject.  We can do this by rerunning prediction jobs on individual subject and comparing the predictions to those made on the same subjects when they are part of a batch.

**Comment by tschaffter** [comment]
To have this approach working, we need to request the participant to reset the random seed to a fix value before predicting each subject.

Add this element to the documentation / Guidelines

**Comment by tschaffter** [comment]
Up

**Comment by tschaffter** [comment]
Done
