### ISSUE TITLE
Documentation notes

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#154]
Add the following to the doc's:
- you can run just preprocessing or just training by including just one container line in the submitted file;
- if you want to maintain the preprocessing from one job to the next do NOT omit the preprocessing step from later jobs, rather include the SAME preprocessing step as before.  The system will recognize its the same and avoid deleting the preprocessing output.
- ensure that quotas are clearly documented.

**Comment by tschaffter** [comment]
Done
