### ISSUE TITLE
Add documentation on how to personalize submission dashboard

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#159]
On the dashboard page of the participants, display instructions (or a link to instructions) on how the table can be updated.

**Comment by brucehoff** [comment]
Thomas:  By "updated" do you mean to "refresh" or to "modify" (e.g. change the column definitions)?  I don't think I want to do the latter, i.e. I think we should set up the submission dashboard in what we think is the most meaningful way.

**Comment by tschaffter** [comment]
> I think we should set up the submission dashboard in what we think is the most meaningful way.

The default dashboard should be that anyway. You have advertised recently that dashboard can be customized so I thought we would need to inform participants how to do that. Most likely the default version of the dashboard should be all they need.
