### ISSUE TITLE
Do we support the case where there are more participants than total user slots?

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#160]
Assume that we have N user slots on each machine and M machines available. A property of the design that I proposed previously is that the Cloud must still be able to run when there are more than N*M users. In that configuration, we don't guarantee the pre-processed data to be persistent (stress that point in the documentation) but the system continue to be ready.

When the job of a user without user slot is selected to be processed, a user slot on which to run it must be identified. How is this user slot being identified?

Related to #148.

**Comment by tschaffter** [comment]
@brucehoff Is a manual intervention required to allow the N+1th user to run his submission when the system has only N user slots?

**Comment by brucehoff** [comment]
> @brucehoff Is a manual intervention required to allow the N+1th user to run his submission when the system has only N user slots?

Yes, if all slots are assigned to users.  This happened in Round 2 to a small extent.  I was able to manage the situation manually with a small amount of effort, unassigning a few users who had not submitted anything in a long time or whose preprocessed data was computed in a short time.

**Comment by tschaffter** [comment]
This feature is no longer required for this challenge.
