### ISSUE TITLE
Make it clear to share docker repo's with dmchallengeit

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#164]
e.g. include this in the 'invalid' error message

**Comment by tschaffter** [comment]
@brucehoff Has this been implemented?

**Comment by brucehoff** [comment]
> @brucehoff Has this been implemented?
Yes, I think so.  The instructions to share are in Sect. 3.6.  Also, if the challenge agent fails to 'docker pull' the submitted Docker image, a notification is sent with a reminder to share the repo with 'dmchallengeit'.  I will be reviewing the submission instructions and will review the sharing instructions as well.
