### ISSUE TITLE
Generate scratch folders during provisioning of the machine

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#172]
1. Generated N scratch folders where N is the number of job slots.
2. Empty the content of the stratch directory in `dm-preprocess-init`and (new) `dm-train-init`.
3. Mount the scratch folder volume to the docker submission (either pre-processing or training; scoring doesn't need stratch).

**Comment by tschaffter** [comment]
Items 1 and 2 are completed.

- /data/scratch0 and /data/scratch1 (200 GB each) created on bm21 and added to SoftLayer provisioning script
- /data/modelX reduced to 5 GB (was 100 GB)
- Must be mounted as the volume /scratch to the Docker containers
- The following Dry Run Docker images remove the files from /scratch (we could do something more safe like running `shred` but this would takes 15 minutes are so 200 GB).

docker.synapse.org/syn5644795/dm-preprocess-init
docker.synapse.org/syn5644795/dm-train-init

https://github.com/tschaffter/dm-docker-admin

@brucehoff Can you update the DM smoke test queues to mount the /scratch volume?

**Comment by brucehoff** [comment]
> @brucehoff Can you update the DM smoke test queues to mount the /scratch volume?
Done!

**Comment by brucehoff** [comment]
Remaining items:
- Thomas to update current production machines (01,02,16,17,18,22,23) to have 'scratch' volume.
- Bruce to update agent start-up script to pass scratch volume to agent, rerun script on production machines.

**Comment by brucehoff** [comment]
I think we're done with this for the 'express lane' but have to ensure it's implemented in the competitive phase, so I'm leaving it open but changing the Milestone.
