### ISSUE TITLE
TokenMgrError: Lexical error at line 1, column 48. Encountered: "@" (64), after : ""

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#175]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1157

**Comment by thomasyu888** [comment]
The participant hasn't responded to my question in a couple days

**Comment by brucehoff** [comment]
Tom:  He is saying that the cited error appeared in the wiki page he linked.
