### ISSUE TITLE
Too Many Users

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#176]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1158

**Comment by tschaffter** [comment]
This participant is not providing detailed information in general (here and other questions). Don't hesitate to ask him and similar participants for more information on how to reproduce the error including screenshots, log files, etc.

**Comment by thomasyu888** [comment]
No problem.  I know what he is talking about.  The synapse team resolved it by building a system of our own.
