### ISSUE TITLE
truncated log file

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#177]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1159

**Comment by tschaffter** [comment]
The current log file size limit strategy is intermediate. Instead of fixing the reported issue we should work on the final strategy and have it tested.

See #6

**Comment by thomasyu888** [comment]
Theres another post about this that has the same name.  I don't think github got it.  Please help:
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1159

**Comment by brucehoff** [comment]
I responded to the participant.
I was hoping to compare the actual, stopped containers to the logs returned to the participant, but they are only available on machine bm16.  (I accidentally let the others, bm01 and bm18 and bm22, be reclaimed.)  I spot checked 7516609 and verified that the returned logs are complete.  The archived containers on bm16 are:
archive.7516609.bm16-2.TRAIN.PREPROCESSING
archive.7516609.bm16-2.TRAIN.TRAINING
archive.7519649.bm16-2.TRAIN.TRAINING
archive.7519649.bm16-2.TRAIN.PREPROCESSING
archive.7536352.bm16-2.TRAIN.TRAINING


Regarding the 'other post with the same name', that's tracked under https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/132.
