### ISSUE TITLE
Messages on completion of submissions - 'has completed its training phase'

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#179]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1163

**Comment by thomasyu888** [comment]
From what I understand, users can choose to write STDOUT to keep track of their submission running?  If it errors, then it will spit out a STDERR unless the error is that the log file is too large?

**Comment by brucehoff** [comment]
If the log file exceeds 1MB then the pipeline stops capturing STDOUT and STDERR.  The "error" that the file exceeded 1MB is *not* part of the content of the log file.

**Comment by tschaffter** [comment]
Please remember that this is an intermediate implementation of the log file size limit. We should address the final strategy described in #6 . Alternatively, we may wait for an answer from Group Health to know if we can release the model state, in which case we may reconsider the approach to limit or not limit log file size.

**Comment by tschaffter** [comment]
@brucehoff Can we close this thread?

**Comment by brucehoff** [comment]
> @brucehoff Can we close this thread?
Yes, Tom responded and the participant did not answer Tom's follow up question, so I think the thread is finished.
