### ISSUE TITLE
Cannot see list of currently running jobs

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#184]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1173

**Comment by thomasyu888** [comment]
After the new system has been implemented, participants have complained that they would like to also see running/pending jobs (Only completed jobs can be seen now).  https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/180
