### ISSUE TITLE
Set Sysdig custom tags to differential the machines

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#189]
When running the Sysdig container on a machine, define custom tag(s) to help monitoring groups of machines that have the same purpose.

Custom tags (environment variable TAGS) are specified in the `docker run` command using:
```
docker run ... TAGS=key1:val1,key2:val2 ... sysdig/agent
```
Suggestion:
```
TAGS=...,cloud:challenge,dataset:train
```
Values for "cloud": {challenge,expresslane}
Values for "dataset": {training,leaderboard}

**Comment by brucehoff** [comment]
Thomas:  You're free to update the 'docker run' command in the ./setupNewServer.sh script on the dm client machine to assign these tags.

**Comment by tschaffter** [comment]
I'm using a common prefix for the name of the arguments in order to interact with them more easily on Sysdig website.

dm.cloud={challenge,expresslane}
dm.role={training,leaderboard}

**Comment by tschaffter** [comment]
Added to setupNewServer.sh
