### ISSUE TITLE
Missing information from scoring error email

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#198]
Submitted the following SC1 scoring submission file:
```
scoring=docker.synapse.org/syn5644795/dm-sc1-infer-random@sha256:sha256:07d7c58c8745eceee1119eb84e1aca14e66a586ab9128dacf862d5631fe143ad
```

Emailed received:
```
DM Challenge Administrator:

Submission 7511335 to SCORE_SC_1 failed. Agent: bm04-1 

Sincerely,

Challenge Administration
```

Hypothesis: Is it because the line "model_state=syn12345" is missing (should be optional)?

**Comment by brucehoff** [comment]
There was a small bug your submission encountered, now fixed.  Indeed you hit the bug by omitting "model_state=syn12345".  With the fix in place you can omit it and should not encounter any error.
