### ISSUE TITLE
Combine DM Smoke test with and without GPU

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#199]
Combine the two submission queues into one that has access to the GPU.
Please also keep the agents on it updated.
Thanks!

**Comment by brucehoff** [comment]
Not sure exactly what you are asking:  Are you asking the the submission queue be allowed to access all four GPUs on bm21?  (We can certainly do this, it's just a matter of starting a second agent on bm21 to run jobs on the other GPU pair.)

**Comment by tschaffter** [comment]
No. We have discussed to merge DM Smoke test and DM Smoke test NO GPU to have one submission queue DM Smoke test (both with access to the GPU).
Thanks!

**Comment by brucehoff** [comment]
Thomas:  I have now updated the agents on bm21, and configure both to process training submissions from "Digital Mammography Model Training Express Lane (7500018)".
