### ISSUE TITLE
Pre-processing log file missing when pre-processing + training

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#2]
After completion, the log archive includes only the log file for the training but not for the pre-processing. The training log file returned is named "c5ec39851dee2a68f9efe7021e721c231fd5f05d35411c54e0e70c21e8b4503a1606786419383895181.txt".

The expected output would be to have two log file in the zip archive: `preprocess.log` and `train.log`.

Submission file: https://www.synapse.org/#!Synapse:syn7428877
Submitted to: DM smoke test
Submission ID: 7433904

Pre-processing container: https://github.com/tschaffter/dm-docker-admin/tree/master/test/dm-preprocess-helloworld
Training container: https://github.com/tschaffter/dm-docker-admin/tree/master/test/dm-train-helloworld

**Comment by brucehoff** [comment]
The folder for captured logs is here:
https://www.synapse.org/#!Synapse:syn7433938
If both containers produce output then there should be two logs, dm-preprocess-helloworld_preprocessing_logs.zip and dm-train-helloworld_training_logs.zip but the first one is not present.   Either the preprocessing step produced no output to capture or the pipeline failed to capture the preprocessing log file.

**Comment by brucehoff** [comment]
I reran Thomas' submission.  The new submission ID is 7476855.  I reproduced the result that the preprocessing log file is not present.  However this may have happened because preprocessing was already done and therefore not repeated.

**Comment by brucehoff** [comment]
I removed the preprocessing output to 'force' the recomputation of preprocessing and found the problem:  The pipeline is creating two different submission folders.  For this submisison the preprocessing folder is:
https://www.synapse.org/#!Synapse:syn7476931 and is named 7476929_dm-preprocess-helloworld
There's also a folder
https://www.synapse.org/#!Synapse:syn7476868 named 7476855_dm-train-helloworld.

The intention is to have a single folder with both archives in the folder.

**Comment by brucehoff** [comment]
Fixed!  Here's an output folder with both log files: https://www.synapse.org/#!Synapse:syn7477329
