### ISSUE TITLE
Add Docker repository digest to its preview on Synapse

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#20]
Docker repository digest is an important piece of information that must be included to the submission file to uniquely identify a Docker image to submit. If the digest if not too long, add it to the previews of the repositories listed under the Docker Tab on Synapse.

Also, display the digest fully on the complete page of the Docker repository (after selecting a repository from the Docker Tab). Currently the length of the field is too small to entirely display it. Consider also displaying the digest in a field that automatically select the entire string (the digest) when we click on it. In place or in addition, add a small button that copy the digest to the clickboard (GitHub has this feature when cloning a repository).

**Comment by brucehoff** [comment]
> If the digest if not too long, add it to the previews of the repositories listed under the Docker Tab on Synapse.

There are many digests per repository.  Not sure there is room or that it makes sense to add the digest to the repository list.  Look at https://hub.docker.com which follows the same pattern:  There's a page that lists the repo names and a page for each repo with further details.

**Comment by tschaffter** [comment]
> There are many digests per repository.

That would be the latest one as this is the one that participants will keep updating in their submission file.

**Comment by tschaffter** [comment]
I remove this suggestion.
