### ISSUE TITLE
Add timestamp to log files

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#203]
The lines in the log files have the prefix "STDOUT: " or "STDERR: ".

Is is possible to modify the prefix to include the date and time (yyyy-MM-dd hh:mm:ss)?

**Comment by brucehoff** [comment]
Yes, initially we used this option, but it makes the files much bigger (in terms of MB) and wider (in terms of characters per line).  With the new approach to file size quota the first problem goes away but the second (minor) consideration remains.

**Comment by tschaffter** [comment]
What about the following?

For STDOUT:
yyyyMMdd hhmmss Hello world!

FOR STDERR:
yyyyMMdd hhmmss STDERR: Trump elected!

**Comment by brucehoff** [comment]
Thomas:  The format is not optional it is RFC3339Nano.  Please see: https://docs.docker.com/engine/reference/commandline/logs/

**Comment by tschaffter** [comment]
Let's leave to the participants the freedom to add themselves a time stamps to their log since we limit the amount of information that we return to them.
