### ISSUE TITLE
Add Last Updated to a repository hosted on Synapse

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#204]

**Comment by brucehoff** [comment]
Thomas:  I think the the feature you request is already there:  For each commit (tag+digest) the date stamp is shown.

**Comment by tschaffter** [comment]
You are right, the feature is there. Can you rename the field "Added On" on Synapse to "Last pushed"?

**Comment by brucehoff** [comment]
Tracking here: https://sagebionetworks.jira.com/browse/SWC-3369

**Comment by tschaffter** [comment]
"Last Pushed" actually comes from DockerHub too (they use both).
