### ISSUE TITLE
Can not access model state file

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#207]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1196

**Comment by tschaffter** [comment]
Duplicate of another question. We should not have displayed the link to download the trained model in the public training express lane before having the feature ready (we had three questions regarding this). Participant has been redirected to an answer.

**Comment by brucehoff** [comment]
Mea culpa.
