### ISSUE TITLE
Increase number of Docker repositories per page on Synapse

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#21]
Increase number of Docker repositories per page on Synapse to 20 or more (I’m not a fan of pages, which is the old way to limit the amount of data to transfer when loading a web page)

**Comment by brucehoff** [comment]
Since this is a Synapse issue, we'll track it in Jira:
https://sagebionetworks.jira.com/browse/SWC-3381
