### ISSUE TITLE
Scoring returns AUROC ~= 0.8 for random predictions on SC1 scoring Express Lane

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#210]
It shouldn't be the reason but I remind here that the dataset installed on the Express Lane is a dummy dataset generated by duplicating subjects from the Pilot Set (the subjectId of two clones/same subject are different).

**Comment by thomasyu888** [comment]
Elias looked into this and there was no error.

**Comment by tschaffter** [comment]
This was an artifact because the substitute dataset used for the SC1 Express Lane had only one positive exam. I've generated a new dataset before the opening of the Express Lane that include more positive exams.
