### ISSUE TITLE
Log Files for Express Lane

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#213]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1202

**Comment by thomasyu888** [comment]
Do participants get to see their log files if they exceed the maximum time of 20 minutes? Or do they just get an error saying their process took more than 20 minutes.

**Comment by brucehoff** [comment]
The latter:  They should get their log files.

**Comment by thomasyu888** [comment]
This participant says that he didn't actually get his log file after this submission was stopped due to the limit.

**Comment by brucehoff** [comment]
I responded to the participant.
