### ISSUE TITLE
Docker CPU allocation

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#217]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1207

**Comment by tschaffter** [comment]
@brucehoff I think that the participant is doing something wrong, but can you check that we are effectively using `cpuset-cpus=0-21` (indexes may be different)?

**Comment by tschaffter** [comment]
@brucehoff Do you confirm that the cpu indexes are correctly set?

**Comment by brucehoff** [comment]
@tschaffter It's not obvious to me how to check whether the CPUs are assigned correctly.  As a quick experiment I tried this:
> docker run --rm -it --name nproc-check ubuntu nproc --all
48
> docker run --rm -ti --name nproc-check --cpuset-cpus=1-22 ubuntu nproc --all
48

I don't know if the 'cpuset-cpus' option isn't working or if the 'nproc' command isn't doing what I think it should.

**Comment by tschaffter** [comment]
```
# nproc --help
Usage: nproc [OPTION]...
Print the number of processing units available to the current process,
which may be less than the number of online processors

     --all       print the number of installed processors
...
# docker run --rm -ti --name nproc-check --cpuset-cpus=1-22 ubuntu nproc
22
```

For a more reliable test, I use the command `stress -c <num cores>` from within a container run with ` --cpuset-cpus=1-22`. The images below show the output of `htop` run from the host where `<num cores>` is set to 5, 22, and 40. This shows that Docker reliably prevent a container to use more CPU cores than allocated.

![screen shot 2016-11-17 at 08 43 40](https://cloud.githubusercontent.com/assets/3056480/20391736/a4365f16-aca2-11e6-9a3b-2e820bb8d50a.png)

![screen shot 2016-11-17 at 08 45 09](https://cloud.githubusercontent.com/assets/3056480/20391738/a83935de-aca2-11e6-8c8d-5a955709e1ee.png)

![screen shot 2016-11-17 at 08 44 24](https://cloud.githubusercontent.com/assets/3056480/20391743/ac2aad9e-aca2-11e6-92ae-74268c659e26.png)

A participant is suggesting that there may be an issue regarding "CPU affinity". I'll have a look to that.

**Comment by brucehoff** [comment]
This seems to work:
> ubuntu@ip-172-31-59-223:~$ docker run --rm -it --name nproc-check ubuntu nproc
48
> ubuntu@ip-172-31-59-223:~$ docker run --rm -ti --name nproc-check --cpuset-cpus=1-22 ubuntu nproc 
22

**Comment by tschaffter** [comment]
The issue is specific to the code of the participant. He is using python multiprocessing library that has been reported to have issues. I'll help him to fix his problem. I'm removing this issue from the Base Minimum milestone because the issue appears to be on the side of the participant.
