### ISSUE TITLE
Conflicting Submission

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#218]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1209

**Comment by thomasyu888** [comment]
The participant wants to submit as a team but my guess is that he has already submitted as an individual.  Are we allowed to make their submissions invalid?

**Comment by brucehoff** [comment]
Thomas:  For questions like this I would first clarify which submission queue he is talking about.   If it's the 'express lane' queue you can post to the thread a dashboard showing his submission history, as shown below, then ask whether he prefers to submit as an individual or a team, the two being mutually exclusive.  To answer your question, yes it's OK to mark the submissions as INVALID to resolve the conflict.  One other thing to mention:  There's some evidence that the exclusivity mechanism of team vs. individual doesn't always work.  I've captured the issue here: https://sagebionetworks.jira.com/browse/PLFM-4129 and will be looking into it.

${leaderboard?path=%2Fevaluation%2Fsubmission%2Fquery%3Fquery%3Dselect%2B%2A%2Bfrom%2Bevaluation%5F7500018%2Bwhere%2BUSER%5FID%253D%253D%25223345123%2522&paging=true&queryTableResults=true&showIfLoggedInOnly=false&pageSize=100&showRowNumber=false&jsonResultsKeyName=rows&columnConfig0=none%2CSubmission ID%2CobjectId%3B%2CNONE&columnConfig1=none%2CStatus%2Cstatus%3B%2CNONE&columnConfig2=none%2CStatus Detail%2CSTATUS%5FDESCRIPTION%3B%2CNONE&columnConfig3=cancelcontrol%2CCancel%2CcancelControl%3B%2CNONE&columnConfig4=epochdate%2CLast Updated%2CmodifiedOn%3B%2CNONE&columnConfig5=synapseid%2CSubmitted Repository or File%2CentityId%3B%2CNONE&columnConfig6=none%2CFile Version%2CversionNumber%3B%2CNONE&columnConfig7=synapseid%2CLog Folder%2CSUBMISSION%5FFOLDER%3B%2CNONE&columnConfig8=none%2CSubmitting User or Team%2CSUBMITTER%3B%2CNONE&columnConfig9=synapseid%2CModel State File%2CMODEL%5FSTATE%5FENTITY%5FID%3B%2CNONE}

**Comment by thomasyu888** [comment]
One issue with this (Through the main challenge is that we return scores to participants via email)  If they submit as an individual and then decide they want to submit as a team.  They will have gotten scores back already.

**Comment by brucehoff** [comment]
> Is it an issue for that participants have unlimited submissions and that every submission they get a score back? 

To be clear, we would only do this in the 'express lane' where the results don't reveal anything about the data.  When the competitive phase opens we would rarely do this for real training and prediction submissions.

> Also, I would only need to make the "ACCEPTED, SCORED, VALIDATED" submissions invalid correct? All the other submissions don't count as actual submissions as they are already CLOSED or INVALID.

I believe that's correct.
