### ISSUE TITLE
Build Digital Mammography Model Training

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#221]
This submission queue is the one that participants will use to train their method during the DM Challenge. The goal of this thread is to provide an overview of the machines that have been successfully added to this submission queue before the opening of the Leaderboard Phase.

The first machine to be added is bm10. Before adding it, I will discuss with Bruce regarding the structure of the files.

**Comment by brucehoff** [comment]
In this file:
https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/blob/master/dmagentprod.sh
anywhere it says "TODO" we have to update with the intended file structure for the competitive phase machines (training and prediction).

**Comment by tschaffter** [comment]
Hi Bruce,

bm21 is the first machine that we can add to the DM Challenge Training submission queue! Can you please add this machine to the queue without making it visible to the participants for now.

Here are where the different files are located (training).

/trainingData/*.dcm -> /data/data/dm-challenge-dcm/training/*.dcm
/metadata/exams_metadata.tsv -> /data/data/metadata/training_exams_metadata.tsv
/metadata/images_crosswalk.tsv -> /data/data/metadata/training_images_crosswalk.tsv

I will open shortly a similar ticket for the Challenge scoring machines.

**Comment by tschaffter** [comment]
Can you set "[ ]" to "[x]" in the document "DREAM 11: IBM Cloud Status" once the machine is added to the queue?

**Comment by tschaffter** [comment]
Here is the list of machines that can be added to the Challenge Training submission queues:
bm17, bm18, bm21, bm23

More machines would be ready but they are used to transfer the training set to other machines.

**Comment by brucehoff** [comment]
Update the leader board volume mounts:
https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/commit/ce3e263975634aa71b64f0ce79f6e7dfd93980df

**Comment by brucehoff** [comment]
Training is now up on bm17, bm18, bm21, bm23.
