### ISSUE TITLE
Issue with Theano example using CUDA

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#231]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1223

**Comment by brucehoff** [comment]
@tschaffter Do you have any insight here?

**Comment by tschaffter** [comment]
Tested tschaffter/theano-gpu on the Express Lane and GPU is working fine. Shared a complete example with the participant.
