### ISSUE TITLE
Scoring notification should include missing, repeated values

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#233]
We should impute missing predictions and skip repeated ones, but the scoring notification should report the counts, e.g. "Your submission was missing predictions for 123 out of 98765 samples.  The missing values have been replaced with xxx.  There were 432 samples have multiple predictions.  We disregard the repeated values."

**Comment by thomasyu888** [comment]
Add impute missing predictions message

**Comment by tschaffter** [comment]
I have a request: can we obfuscate the number of samples by providing percent values with 2 decimals?

"Your submission was missing predictions for x.xx % of the samples. The missing values have been replaced with xxx. x.xx % of the samples have multiple predictions. We disregard the repeated values."

**Comment by thomasyu888** [comment]
Bruce and I just had a conversation and I feel like it is best to not allow duplicated values for now.  The validator will send an email back to the participant if there are any duplicated samples.  I will try to prioritize and get to all the action items by the end of tomorrow.

**Comment by thomasyu888** [comment]
The percentage has been implemented for missing predictions.  We are going ahead with sending an error for participants that repeat any samples. Am currently testing the email to see if I get the correct responses.

**Comment by tschaffter** [comment]
Formatting only to 2 decimals is not suitable considering the numbers involved. We can just print all the decimals.

**Comment by thomasyu888** [comment]
No problem.  I will not truncate.

**Comment by brucehoff** [comment]
Please close this issue when complete.

**Comment by thomasyu888** [comment]
Tested and completed
