### ISSUE TITLE
Could you stop sending the same  email 10 times 

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#237]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1232

**Comment by brucehoff** [comment]
Ziming:   Please look at how validateAndInitSubmissionBundle() calls retrieveAndValidateTrainingParams() and what it does afterwards.  I think that it sets INVALID submissions to VALIDATED and that may have caused an infinite series of emails to this participant.

**Comment by zimingd** [comment]
That's definitely the bug. It's a pretty quick fix i think. I'll make a pull request

**Comment by zimingd** [comment]
https://github.com/Sage-Bionetworks/ChallengeDockerAgent/pull/15

**Comment by brucehoff** [comment]
Ziming:  There's something else wrong.   I briefly restarted the agent and saw multiple emails again, going to users 3343808 and 3344561.  User 3343808 sent submission 7555800 which is simply this Docker container image: docker.synapse.org/syn7555790/dm-trial-tensorflow  I would not expect it to be invalid.

User 3344561 submitted 7555795 which is entity https://www.synapse.org/#!Synapse:syn7501865, one of our samples (which is presumably valid).  So I think we are tagging valid submissions as invalid.

**Comment by brucehoff** [comment]
Here's the message sent repeatedly to user 3343808:

> 

Your Submission to the Digital Mammography challenge, syn7555796 (ID 7555800), was invalid.  The message is:

	The repository for image docker.synapse.org/syn7555790/dm-trial-tensorflow@sha256:c18c3a3a26f646912d839273ab153f7f1507d95e62817b8576241af9b4eeb144 does not exist or is not accessible by the submission processing infrastructure.
>

Here's the message to 3344561:

> Your Submission to the Digital Mammography challenge, syn7501865 (ID 7555795), was invalid.  The message is:

	syn7498325 is not accessible by the submission creators.

>

**Comment by brucehoff** [comment]
I'm pretty sure the problem with the submission by 3344561 is in   SubmissionUtils.validateEntityAccess().  Here we check that the submission team (the 'contributors') have read access in the ACL of the requested container.  In the case of syn7501865, the team doesn't have explicit access, rather "PUBLIC" (273949) is given read access in the ACL.  We should allow access for both "Authenticated Users" (273948) and "PUBLIC" (273949).

**Comment by brucehoff** [comment]
I'm pretty sure the problem with the submission by 3343808 is as follows:  In retrieveAndValidateTrainingParams() we call validateAccess() to make sure the submitted container is owned (or at least accessible) by the submitting team.  When the user is submitting a File they have to grant us access to the containers they list in the file and then we can do the access check.   But if the user simply submits a Docker container image then they need not grant us access and we can't do the necessary query to validate access.   In this case we can skip the validation check on the container, which has already been done when they submitted it.

**Comment by brucehoff** [comment]
We fixed these problems and manually tested them on the express lane.
