### ISSUE TITLE
Build Digital Mammography Model Scoring

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#240]
The first machine with the Challenge Leaderboard SC1 and SC2 dataset is ready (bm03).

SC1:
/inferenceData/\*.dcm -> /data/data/dm-challenge-dcm/SC1_leaderboard/*.dcm
/metadata/images_crosswalk.tsv -> /data/data/metadata/SC1_leaderboard_images_crosswalk.tsv

SC2:
/inferenceData/\*.dcm -> /data/data/dm-challenge-dcm/SC2_leaderboard/*.dcm
/metadata/images_crosswalk.tsv -> /data/data/metadata/SC2_leaderboard_images_crosswalk.tsv
/metadata/exams_metadata.tsv -> /data/data/metadata/SC2_leaderboard_exams_metadata.tsv

Set "[ ]" to "[x]" in the Google doc "DREAM 11: IBM Cloud Status" once the machine has been added to the submission queue.

**Comment by brucehoff** [comment]
volume mounts updated here: https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/commit/613d54215921b13acf183f52e5c96f4565cc5e92

**Comment by brucehoff** [comment]
Scoring is now up on bm03.
