### ISSUE TITLE
Personalized dashboards

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#243]
make one subpage to sect. 3.6 which has personalized dashboards for training, sc1, sc2
make a second subpage for the three express lane dashboards.

**Comment by tschaffter** [comment]
@brucehoff This is an important item.

**Comment by tschaffter** [comment]
This task includes #7 and #139

**Comment by tschaffter** [comment]
This task include #8
