### ISSUE TITLE
submitting as individual vs. team

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#250]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1250

**Comment by tschaffter** [comment]
@thomasyu888 As a reminder, please the participants for more information. Here he is not saying why he cannot submit as part of a team. Thanks!

**Comment by thomasyu888** [comment]
He can't submit as part of a team, because he has submitted as an individual apparently..  I will look at the queues he has submitted to and make any older submissions invalid.

**Comment by brucehoff** [comment]
There's another, easier solution.   I did not define *rounds* for the challenge submission queues (an oversight on my part), but if we define the round to start as advertised (last Friday), then the restriction will only apply on a per-round basis, decoupling the pre-competitive phase submissions from the new ones.  I will start working on this.

**Comment by brucehoff** [comment]
The remaining task is to update the round start for each round:
round 2: 2017-01-03T08:00:00.000Z
round 3: 2017-02-14T08:00:00.000Z
final:       2017-03-28T08:00:00.000Z

I added a milestone 'start round 2' and moved this issue to that milestone to remind us to do this task when the time comes.
