### ISSUE TITLE
No feedback for Digital Mammography Prediction - Sub-Challenge 1 Express Lane

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#259]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1256

**Comment by thomasyu888** [comment]
When the status detail of his runs are INFRASTRUCTURE_ERROR, does that mean it is an error with our machines?  He says he hasn't gotten any feedback in +6 hours.

**Comment by brucehoff** [comment]
> When the status detail of his runs are INFRASTRUCTURE_ERROR, does that mean it is an error with our machines?

Yes!  When such an error occurs I get an email and have to look into the problem.  In this case it was a problem with disk volume capacity, now fixed.  His submission has now run.  

He has a follow up question, so I'll leave this issue open while you can respond to him.

Thanks!

**Comment by thomasyu888** [comment]
There are still infrastructure errors with his submissions.

**Comment by brucehoff** [comment]
I don't see any outstanding problem.  I replied on the forum, asking him to reply with the submission ID of any problematic submission.  In the meantime I think we can close this issue.
