### ISSUE TITLE
Error encountered during training (dm-preprocess-caffe)

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#264]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1260

**Comment by tschaffter** [comment]
Do we know from the email that he received whether he submitted to the Challenge queue or Express Lane?

**Comment by brucehoff** [comment]
Yes, indirectly.  Each submission has a reference to its submission queue.  Using our R client:
```
> synGetSubmission("7791968", downloadFile=F)@submissionContent@evaluationId
[1] "7500018"
> synGetEvaluation("7500018")@name
[1] "Digital Mammography Model Training Express Lane"
```

**Comment by tschaffter** [comment]
Just compiled the example from source and run them successfully on the Express Lane. Asked the participant if he can reproduce the issue. If he can reproduce the issue, we can dig deeper.

**Comment by tschaffter** [comment]
According to my last comment, I successfully tested the example and ask additional information to the participant. We didn't get any reply from him.
