### ISSUE TITLE
docker hangs on bm21

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#271]
An agent on bm21 failed to start a user container.  It emailed the error:
```
Submission  to TRAIN failed. Agent: bm21-2 

 The message is:

	Submission ID: 7791615
{"message":"containerd: container did not start before the specified timeout"}
```
and then stopped itself.  Trying to restart I find that docker commands like `docker ps -a` and ` docker start `bm21-2-train` also hang.  I don't dare restart the daemon or the bm21 node since there is another user container (7791563.bm21-1.TRAIN.TRAINING) that has been running for two days.

**Comment by brucehoff** [comment]
Update:  The job running on bm21 (7791563) has not been updated (the 'modifiedOn' field in the submission has not been modified) in 12 hours.  I tried stopping and restarting the agent.  I could stop it but not restart it.  I ssh'ed in and ran 'sudo reboot'.  Now I can't ssh in at all.

I will migrate the running job to another machine and free the teams assigned to slots on bm21 to other machines.

**Comment by tschaffter** [comment]
bm21 appears as "Powered On" and "Connected" on SoftLayer but I can't ssh to it either.
Soft Reboot from SoftLayer web interface.
Can now ssh to bm21.

@brucehoff You can close this ticket if you want as there are not much I can do now. Next time I'll try to experiment with the "hanging docker" and hopefully find a fix.
