### ISSUE TITLE
job stuck in "Evaluation In Progress" state

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#275]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1269

**Comment by brucehoff** [comment]
Tom:
You said
> This job will not count towards your time quota.

but when I look at the status of submission 7799334 I see that it is CLOSED, not INVALID (or some other status that is not counted toward the user's quota).  Do you not have to change the status to omit the submission from the user's quota?

**Comment by thomasyu888** [comment]
Ya submissions that are CLOSED will count towards the quota.  I will change it to invalid
