### ISSUE TITLE
Training submissions after an INVALID submission are not shown

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#276]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1270

**Comment by tschaffter** [comment]
@thomasyu888 @brucehoff Tom, can you reassure participants who report errors on the Challenge training submission queue that their time quota will be systematically refunded in case an error is due to a failure of the system?

@brucehoff Can you systematically refund the time quota of participants whose jobs failed due to the system?

**Comment by brucehoff** [comment]
> Can you systematically refund the time quota of participants whose jobs failed due to the system?

@thomasyu888 :  I believe the time computation omits submissions marked as INVALID.  Can you confirm this?  If so we can 'refund' time quota simply by marking submissions as INVALID.

**Comment by thomasyu888** [comment]
I think that is true.  However, there is a flaw with the system right now.  I only update those statuses that are: "EVALUATION_IN_PROGRESS" and "RECEIVED".  I think I also need to update those that are: "ACCEPTED" and "SCORED" right?

**Comment by brucehoff** [comment]
> I think I also need to update those that are: "ACCEPTED" and "SCORED" right?

No, I don't think so:  Your code (1) looks at certain submissions when adding up the time already used, and (2) selects certain submissions to update with the time remaining.  My original question was about (1), i.e. whether you omit INVALID submissions when summing the time used.  Regarding (2) (which submissions to update) we only need to update the submissions that we are running, not the ones that have stopped already.   So we don't have to update ACCEPTED and SCORED submissions.

**Comment by thomasyu888** [comment]
Right.  I fixed the quota application.  Thanks!
