### ISSUE TITLE
Learning submission stuck , EVALUATION_IN_PROGRESS with no logs (and time quota question)

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#277]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1271

**Comment by thomasyu888** [comment]
Lets meet to discuss about the time quota again.  I have some questions about this

**Comment by brucehoff** [comment]
Some notes:
The submission in question 7801961 had failed because the Softlayer server was unable to pull the docker image.  I had gotten this email from the server agent:
```
Submission  to TRAIN failed. Agent: bm02-2 

 The message is:

	Submission ID: 7801961
Unable to pull image docker.synapse.org/syn7800554/ivycad_preprocess@sha256:36fb9c6c47824c840c39fa73b9b331dcebc7f37f89122b9062cd511a427a4c63 after 3 tries.
```
I think it's fine to remove the submission from the time quota computation.

Regarding his question about the express lane, it's worth reminding him that (1) activity in the express lane is not deducted from the time quota and (2) invalid submissions to the leader board are not deducted from the time quota.
