### ISSUE TITLE
bm01 containers stopped

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#278]
30 hours ago two training containers and two challenge agents stopped on bm01

       STATUS                    PORTS               NAMES
09263e5c014a        docker.synapse.org/syn7428675/reliif@sha256:3239d3c11278807d96e9bed401e26e02c3baea24f4d2da4c97980d5476b1fe67        "/train.sh"              30 hours ago        Exited (1) 30 hours ago                       7799650.bm01-1.TRAIN.TRAINING
3be625baefaa        docker.synapse.org/syn7504501/model@sha256:b393ad8cccd143d693fc27f14d51ea7f9c60beff16c308a044bc9a90a19cbd34         "/preprocess.sh"         35 hours ago        Exited (1) 30 hours ago                       7799334.bm01-2.TRAIN.PREPROCESSING
bd20eae2ee69        docker.synapse.org/syn7504740/method@sha256:eb8bbb9c15a42ef84869ac99416bf5ebf156eac6e4b402dd3a5e0950714e1ba7        "/train.sh"              40 hours ago        Exited (0) 40 hours ago                       archive.7799090.bm01-1.TRAIN.TRAINING
8a633fe7ac88        docker.synapse.org/syn7504740/method@sha256:38c8e183ca2305719270892520860c9a4a4f95be477fe9475532d5f9d762d379        "/train.sh"              45 hours ago        Exited (0) 42 hours ago                       archive.7798776.bm01-2.TRAIN.TRAINING
2d71d4aa89c1        docker.synapse.org/syn7260217/dmg@sha256:fae57172bc3c3fadc16794373e972bf0eefb3fba1cc43c5f55feb16750965238           "/usr/bin/tini -- /tr"   3 days ago          Exited (0) 3 days ago                         archive.7792992.bm01-1.TRAIN.TRAINING
701b86ec3666        docker.synapse.org/syn7260217/dmg@sha256:fae57172bc3c3fadc16794373e972bf0eefb3fba1cc43c5f55feb16750965238           "/usr/bin/tini -- /pr"   3 days ago          Exited (0) 3 days ago                         archive.7792992.bm01-1.TRAIN.PREPROCESSING
989938bab567        docker.synapse.org/syn7323270/print_table@sha256:fd6fed6e0b781dc60ea18902382ba77a552cd77d7f4e295bed532f933be5db89   "/train.sh"              4 days ago          Exited (0) 4 days ago                         archive.7792653.bm01-1.TRAIN.TRAINING
fb949428cfeb        docker.synapse.org/syn7221819/test_demo@sha256:87b0c5c63b659ac7f8260476402f00e3d276bf95d099232dfe8787895bb14a51     "/train.sh"              4 days ago          Exited (0) 4 days ago                         archive.7791755.bm01-1.TRAIN.TRAINING
166373fc8980        docker.synapse.org/syn7221819/test_demo@sha256:87b0c5c63b659ac7f8260476402f00e3d276bf95d099232dfe8787895bb14a51     "/preprocess.sh"         4 days ago          Exited (0) 4 days ago                         archive.7791755.bm01-1.TRAIN.PREPROCESSING
168690670f98        docker.synapse.org/syn7221819/test_demo@sha256:dfa2cf11047833c37ca8b1dace16acf4b1d0dc26b0da703ddccb413637b4275d     "/train.sh"              4 days ago          Exited (0) 4 days ago                         archive.7777770.bm01-1.TRAIN.TRAINING
d6e971a28947        docker.synapse.org/syn7504740/method@sha256:cd0ede62748b00f80316ab115ec983abc50b4c0d7756d8fa36c9e5322b216644        "/train.sh"              4 days ago          Exited (0) 3 days ago                         archive.7791632.bm01-2.TRAIN.TRAINING
ba7134b41106        docker.synapse.org/syn7221819/test_demo@sha256:dfa2cf11047833c37ca8b1dace16acf4b1d0dc26b0da703ddccb413637b4275d     "/preprocess.sh"         4 days ago          Exited (0) 4 days ago                         archive.7777770.bm01-1.TRAIN.PREPROCESSING
b483befb5ef5        brucehoff/challengedockeragent                                                                                      "/bin/sh -c 'exec mvn"   4 days ago          Exited (1) 30 hours ago                       bm01-2-train
717b3f8cfbf8        brucehoff/challengedockeragent                                                                                      "/bin/sh -c 'exec mvn"   4 days ago          Exited (1) 30 hours ago                       bm01-1-train
e40fcd90b069        docker.synapse.org/syn5644795/nvml-statsd                                                                           "/bin/sh -c 'python /"   9 days ago          Up 30 hours                                   nvml-statsd
1da189bf7c32        sysdig/agent                                                                                                        "/docker-entrypoint.s"   9 days ago          Up 30 hours                                   sysdig-agent
34460236ff36        hello-world                                                                                                         "/hello"                 13 days ago         Exited (0) 13 days ago                        zen_mirzakhani

**Comment by tschaffter** [comment]
Because the machines have been very stable during Round 3, I'm closing all the tickets related to reboot that are more than one month old. If a new issue is raising an a machine, we can easily look at its history of issues on GitHub.
