### ISSUE TITLE
Streamline deployment of challenge agent

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#279]
Currently we have the challenge agent running on a handful of machines.  When we update the code we need to update the agent.  To update the agent requires a sequence of commands (docker stop, docker pull, docker run) run on each machine.  It would be ideal to have a easy way (one click?) to update the agent across machines.   We want to retain control over *when* the updates occur (vs. automatically deploying whenever there's a new version) but once we decide to update it would be helpful to stream line the process.   One deployment tool I've seen is https://www.distelli.com/ but there may be other approaches.

**Comment by tschaffter** [comment]
@brucehoff Is this thread still relevant?

**Comment by brucehoff** [comment]
Ziming provided a script which does this, https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/blob/master/updateAgents.sh
