### ISSUE TITLE
Add model state and inference to submission scored email

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/DigitalMammographyChallenge#281]
It would be very nice if the content of submission file can be put inside the scoring notification email (or any reference to it) as well so that we know exactly which submission file does it related too. Eg:
```
model_state=syn7798989
inference=docker.synapse.org/syn7502921/mik2015-keras-score@sha256:bc1b58a7d07a370ee83b40bde86165e8b4e4380395b3e6e989f86fdd0c70f96c
```

**Comment by tschaffter** [comment]
@thomasyu888 Is this still something that you suggest or does the email now include a information that allow to retrieve the submission file?
