### ISSUE TITLE
About predictions file

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#282]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1275

**Comment by tschaffter** [comment]
I've attempted to clarify one point of the question from the participant.

@thomasyu888 Please continue to monitor and answer the questions of the participant. If you need any precision from me, let me know.

**Comment by tschaffter** [comment]
@thomasyu888 Please also avoid copying/pasting large chunk of the documentation in the threads. Instead prefer a link that redirect to the documentation. If someone in the future follows the link, he will find there the latest version of the documentation.

**Comment by thomasyu888** [comment]
Right.  Sorry about that.  Thanks for following up.

**Comment by tschaffter** [comment]
Thanks to you! I really appreciate your help. :)
