### ISSUE TITLE
Detect and take care of stuck preprocessing/training submission

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#290]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1281

**Comment by brucehoff** [comment]
@tschaffter Please do not unassign Tom Yu.  I would like him to remain as the point-of-contact for the participant (unless he requests that I take it over from him).

My comments on this issue:

> My training submission's (id 7804074) log (regular lane)

This ran on bm17 (agent 1) which has not encountered any problems.  The submission is now closed.  The value for 'cancelRequested' is true so he may have stopped it himself.  This information is shown here:
https://www.synapse.org/#!Synapse:syn5644795/wiki/405302

> In ideal condition, what is the expected period of the log update (and upload)?

We nominally update the logs each 15 minutes.  You can see the history of his log files here:
https://www.synapse.org/#!Synapse:syn7804080
There are 68 versions meaning it ran for 17 hours.  Training started at 7:30AM on 11/30 so it ran through 12:30AM on 12/1.   That coincides with the 'last updated' column in the dashboard.  So his submission was never 'stuck' from our perspective.  His code may have stopped producing output while continuing to run (which would be 'stuck' from his perspective).

> How long is the suggested waiting time to observe my log for update before considering it stuck (and cancel it manually)?

I think the answer to give him is that he should click on the File History button for his accumulating log file.  If the file size is not increasing then his model is not producing output and he is welcome to cancel his submission if that is unexpected.

**Comment by thomasyu888** [comment]
Thanks, the information you gave me here was enough for me to answer his questions.  Slowly I am understanding more and more about the challenge.  Is there a way to give the admins access to the log files?

**Comment by brucehoff** [comment]
> Is there a way to give the admins access to the log files?
That's a good idea.  We have a "DM Administrators" team which I've just invited you to join.  I will change the challenge agent to share the upload folders with this team.

**Comment by thomasyu888** [comment]
He asked a follow up question that I don't know the answer to

**Comment by brucehoff** [comment]
I responded to him.
