### ISSUE TITLE
Job Status

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#294]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1290

**Comment by brucehoff** [comment]
@thomasyu888 Can you please address the follow-up question "you didn't address my other question, why I received no feedback from the test fast lane"

**Comment by brucehoff** [comment]
@thomasyu888   Please disregard my earlier request.  I have answered her.

**Comment by brucehoff** [comment]
Yuanfang asked me to "please delete" this content:
```
> why I received no feedback from the test fast lane

Not sure what you are asking here.  Here are your 'fast lane submissions':

${leaderboard?path=%2Fevaluation%2Fsubmission%2Fquery%3Fquery%3Dselect%2B%2A%2Bfrom%2Bevaluation%5F7500018%2Bwhere%2BSUBMITTER%253D%253D%25223319559%2522&paging=true&queryTableResults=true&showIfLoggedInOnly=false&pageSize=100&showRowNumber=false&jsonResultsKeyName=rows&columnConfig0=synapseid%2CentityId%2CentityId%3B%2CNONE&columnConfig1=none%2CSubmission ID%2CobjectId%3B%2CNONE&columnConfig2=synapseid%2CSubmission Folder%2CSUBMISSION%5FFOLDER%3B%2CNONE&columnConfig3=none%2CSubmission Status%2Cstatus%3B%2CNONE&columnConfig4=none%2C%2CSTATUS%5FDESCRIPTION%3B%2CNONE&columnConfig5=userid%2CSubmitted By%2CuserId%3B%2CNONE&columnConfig6=none%2C%2CUSER%5FID%3B%2CNONE&columnConfig7=none%2C%2CSUBMITTER%3B%2CNONE&columnConfig8=none%2CSubmission Name%2Cname%3B%2CNONE&columnConfig9=epochdate%2CCreation Date%252FTime%2CcreatedOn%3B%2CNONE&columnConfig10=none%2CScore%2CDM%5FSCORE%3B%2CNONE&columnConfig11=epochdate%2CTRAINING%255FSTARTED%2CTRAINING%5FSTARTED%3B%2CNONE&columnConfig12=epochdate%2CTRAINING%255FLAST%255FUPDATED%2CTRAINING%5FLAST%5FUPDATED%3B%2CNONE&columnConfig13=none%2CFailure Reason%2CFAILURE%5FREASON%3B%2CNONE&columnConfig14=none%2CServer ID%2CWORKER%5FID%3B%2CNONE&columnConfig15=none%2CTime Remaining %2528millisec%2529%2CTIME%5FREMAINING%3B%2CNONE}

Spot checking the latest, 7829364, our records show we sent you this feedback via email:
```
on 2016-12-09T19:11:46.353Z subject Submission Terminated

Dear Yuanfang Guan 小黄药师 (yuanfang.guan):

Your Submission to the Digital Mammography challenge, docker.synapse.org/syn7221819/sc1_pre_train@sha256:04794cbf7752c56656d61e629c560c9d26e71b59a6520bf1054ada86c80d8064 (submission ID 7829364) has stopped before completion.  The message is:

	Error encountered during training.

  Your log file is available here: https://www.synapse.org/#!Synapse:syn7829369 Please direct any questions to the challenge forum, https://www.synapse.org/#!Synapse:syn4224222/discussion .

Sincerely,

Challenge Administration
```

And the linked Synapse directory contains this log file:

```
STDERR: Using gpu device 0: Tesla K80 (CNMeM is enabled with initial size: 10.0% of memory, cuDNN 5103)
STDOUT: 46992
STDOUT: 65955
STDOUT: 24751
STDOUT: 31371
STDOUT: 15500
STDOUT: 82312
STDOUT: 6815
STDOUT: 32940
STDOUT: 42810
STDOUT: 80350
STDERR: Using gpu device 0: Tesla K80 (CNMeM is enabled with initial size: 10.0% of memory, cuDNN 5103)
STDERR: Traceback (most recent call last):
STDERR: File "on/1024cut/train.py", line 119, in <module>
STDERR: (fold_train_input, fold_train_label, fold_test_input, fold_test_label)=GS_split.GS_split(sys.argv[1],size)
STDERR: File "/on/1024cut/GS_split.py", line 28, in GS_split
STDERR: ratio=neg_count/pos_count
STDERR: ZeroDivisionError: integer division or modulo by zero
STDERR: cp: cannot stat 'fold0_params_50': No such file or directory
STDERR: python: can't open file 'predict_all_vis.py': [Errno 2] No such file or directory
STDERR: python: can't open file 'sc1.py': [Errno 2] No such file or directory
STDERR: on/1024cut/bash_tmp.sh: 19: on/1024cut/bash_tmp.sh: R: not found
STDERR: mv: cannot stat 'R.auc.txt': No such file or directory
STDERR: mv: cannot stat 'R.s.txt': No such file or directory
STDERR: mv: cannot stat 'list_test_sc1_pred': No such file or directory

```

This is the feedback the system is designed to return to you.
```

**Comment by brucehoff** [comment]
@thomasyu888 Please check whether your scoring app' sent Yuanfang her scores.

**Comment by thomasyu888** [comment]
Checked
