### ISSUE TITLE
Can't get email when submit preprocessing model to express lane

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#299]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1292

**Comment by thomasyu888** [comment]
He has exceeded time quota on the express lane, but he says he gets no email back about the error. He currently has a job running on the normal training lane.

**Comment by thomasyu888** [comment]
He said he had the notification allowed button checked all along.  His other team mates get the emails, so what else could be the problem?

**Comment by brucehoff** [comment]
Participant reports the problem has been solved.
