### ISSUE TITLE
Enable Docker storage using LVM-direct

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#3]
Docker uses by default thinpool files for its `data` and `metadata`. Docker log warns that this configuration is not suitable for production.

I have enabled LVM-direct on bm08 and Docker is running fine. The thinpool Logical Volume is created during the provisioning of the SoftLayer machines. After running `docker-machine create` to install the docker daemon on a SoftLayer machine, a script must be run to change the configuration of Docker and restart the service.
- Thomas: Provide Bruce with instruction to update the Docker configuration
- Bruce: Apply that step after running `docker-machine create`

**Comment by tschaffter** [comment]
Implement a 'clean' command: https://github.com/docker/docker/issues/928
New Data Management commands: https://github.com/docker/docker/pull/26108

@brucehoff You mentioned that the images associated to container that have recently stopped running should not be removed (most likely to backup a trained model)? Can you specify the specifications for the cleanup service? We must make sure that a trained model is never removed before pushing it to Synapse.

**Comment by brucehoff** [comment]
@tschaffter In reply to the previous comment:   The good news is that we do not 'snapshot' users' models.  There is no production data stored in containers.   (Sorry if my earlier comments were unclear.)  The only reasons not to remove images are: (1) If an image is being used by a running container then it shouldn't be removed.  (I imagine that Docker won't let you delete an image that's being used.); (2) The local copies of images act as a cache:  If a team submits similar models repeatedly then having large, reused layers speeds up the "docker pull" command.  This is a minor point, however, since the time to run docker pull is much less than the time to run a 'real' machine learning model.

**Comment by tschaffter** [comment]
Then I will create a Logical volume of 500 GB for Docker's data (thinpool) and write a crontab script that removes the images that are not used by a running container when the Used Size of the thinpool reaches 80%. Does that sound good?

**Comment by brucehoff** [comment]
Sounds great!

**Comment by brucehoff** [comment]
Just touching base on this issue.  Do we have the " instruction to update the Docker configuration" ?

**Comment by brucehoff** [comment]
Per Thomas I have to:
- stop the docker service
- insert something into docker config file
- restart service
He will send the script to run.

**Comment by tschaffter** [comment]
The new docker data thinpool (Logical Volume) is created during the provisioning of the SoftLayer machine. To enable it, the following command must be run after having instantiated the machine with `docker-machine create`:

```
# service docker stop
# sed -i 's:--storage-driver devicemapper:--storage-driver devicemapper --storage-opt=dm.thinpooldev=/dev/mapper/data-thinpool --storage-opt=dm.use_deferred_removal=true --storage-opt=dm.use_deferred_deletion=true:g' /etc/systemd/system/docker.service
# rm -fr /var/lib/docker/*
# service docker restart
```

**Comment by tschaffter** [comment]
Waiting for a confirmation from @brucehoff that the above instructions work as intended.

**Comment by tschaffter** [comment]
From @brucehoff :

I'm trying to set up bm21 but am having problems installing Docker:

```
docker-machine create --driver generic --generic-ip-address=bm21-dreamchallenge.sl851865.sl.edst.ibm.com --generic-ssh-key=/Users/bhoff/.ssh/id_rsa_docker-machine --generic-ssh-user=dreamuser bm21
Running pre-create checks...
Creating machine...
(bm21) Importing SSH key...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with redhat...
Error creating machine: Error running provisioning: Something went wrong running an SSH command!
command : sudo systemctl -f restart docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
```

**Comment by tschaffter** [comment]
The issue is related to the use of LVM for the thinpool. Docker is now running on bm21. I did two things:

- a bit of configuration but I think that it's optional

After that docker can still not be start with the same error that mentioned by Bruce. Then I did:

```
$ rm -fr /var/lib/docker/*
$ service docker start
```

And Docker is now running and using the thinpool.

@brucehoff First, can you tell me if you effectively ran `rm -fr /var/lib/docker/*` as instructed 1) after changing the settings of docker and 2) before restarting it? You have the correct privileges to do so. You can try with bm07, which is a clean provisioning.

**Comment by tschaffter** [comment]
I noticed that `docker-machine` is now installing docker 1.12.3.

```
$ docker --version
Docker version 1.12.3, build 6b644ec
```

**Comment by brucehoff** [comment]
> can you tell me if you effectively ran rm -fr /var/lib/docker/* as instructed 1) after changing the settings of docker and 2) before restarting it (you run the command only once)?

This is what I did:

#!/bin/bash
# Usage: ./setupNewServer.sh bm16
host=$1
docker-machine create --driver generic --generic-ip-address=${host}-dreamchallenge.sl851865.sl.edst.ibm.com --generic-ssh-key=/Users/bhoff/.ssh/id_rsa_docker-machine --generic-ssh-user=dreamuser ${host}
# https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/3#issuecomment-256758426
ssh ${host} sudo service docker stop
ssh ${host} sudo sed -i 's:--storage-driver devicemapper:--storage-driver devicemapper --storage-opt=dm.thinpooldev=/dev/mapper/data-thinpool --storage-opt=dm.use_deferred_removal=true --storage-opt=dm.use_deferred_deletion=true:g' /etc/systemd/system/docker.service
ssh ${host} sudo rm -fr /var/lib/docker/*
ssh ${host} sudo service docker restart
ssh ${host} sudo chmod 777 /etc/docker
scp ~/.docker/machine/certs/key.pem ${host}:/etc/docker/
scp ~/.docker/machine/certs/cert.pem ${host}:/etc/docker/
ssh ${host} sudo chmod 666 /etc/resolv.conf
ssh ${host} sudo "printf \"nameserver 10.0.80.11\nnameserver 10.0.80.12\noptions single-request\n\" >> /etc/resolv.conf"
ssh ${host} sudo "service network restart"
ssh ${host} sudo sysctl -w net.ipv4.ip_forward=1

echo ${host}
eval $(docker-machine env ${host})
if [[ $(docker-machine active) != ${host} ]]; then
	echo host is ${host} but active Docker Engine is $(docker-machine active)
	exit 1
fi

docker pull brucehoff/challengedockeragent

**Comment by tschaffter** [comment]
The content of `/etc/resolv.conf` is empty and so the machine has currently no access to internet. Did your script threw an error before arriving to `ssh ${host} sudo "printf \"nameserver 10.0.80.11\nnameserver 10.0.80.12\noptions single-request\n\" >> /etc/resolv.conf"`?

**Comment by tschaffter** [comment]
Can you try moving the code that I gave you after `ssh ${host} sudo sysctl -w net.ipv4.ip_forward=1`?

**Comment by brucehoff** [comment]
>  You can try with bm07, which is a clean provisioning.

Looks good:



[~/Desktop/Digital Mammography Challenge]  export host=bm07
[~/Desktop/Digital Mammography Challenge]  echo ${host}
bm07
[~/Desktop/Digital Mammography Challenge]  docker-machine create --driver generic --generic-ip-address=${host}-dreamchallenge.sl851865.sl.edst.ibm.com --generic-ssh-key=/Users/bhoff/.ssh/id_rsa_docker-machine --generic-ssh-user=dreamuser ${host}
Running pre-create checks...
Creating machine...
(bm07) Importing SSH key...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with redhat...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env bm07
[~/Desktop/Digital Mammography Challenge]  ssh bm07
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
c4:9f:ba:9f:71:83:d3:e0:03:90:64:5b:1b:0f:0c:a0.
Please contact your system administrator.
Add correct host key in /Users/bhoff/.ssh/known_hosts to get rid of this message.
Offending RSA key in /Users/bhoff/.ssh/known_hosts:124
RSA host key for bm07-dreamchallenge.sl851865.sl.edst.ibm.com has changed and you have requested strict checking.
Host key verification failed.
[~/Desktop/Digital Mammography Challenge]  ssh bm07
The authenticity of host 'bm07-dreamchallenge.sl851865.sl.edst.ibm.com (169.45.173.56)' can't be established.
RSA key fingerprint is c4:9f:ba:9f:71:83:d3:e0:03:90:64:5b:1b:0f:0c:a0.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'bm07-dreamchallenge.sl851865.sl.edst.ibm.com,169.45.173.56' (RSA) to the list of known hosts.
Last login: Mon Oct 31 12:14:39 2016 from 140.107.149.12
[dreamuser@bm07 ~]$ sudo service docker stop
Redirecting to /bin/systemctl stop  docker.service
[dreamuser@bm07 ~]$ sudo sed -i 's:--storage-driver devicemapper:--storage-driver devicemapper --storage-opt=dm.thinpooldev=/dev/mapper/data-thinpool --storage-opt=dm.use_deferred_removal=true --storage-opt=dm.use_deferred_deletion=true:g' /etc/systemd/system/docker.service
[dreamuser@bm07 ~]$ sudo rm -fr /var/lib/docker/*
[dreamuser@bm07 ~]$ sudo service docker restart
Redirecting to /bin/systemctl restart  docker.service
Warning: docker.service changed on disk. Run 'systemctl daemon-reload' to reload units.
[dreamuser@bm07 ~]$ sudo systemctl daemon-reload
[dreamuser@bm07 ~]$ sudo chmod 777 /etc/docker
[dreamuser@bm07 ~]$ exit
logout
Connection to bm07-dreamchallenge.sl851865.sl.edst.ibm.com closed.
[~/Desktop/Digital Mammography Challenge]  scp ~/.docker/machine/certs/key.pem ${host}:/etc/docker/
key.pem                                                                                                                     100% 1679     1.6KB/s   00:00    
[~/Desktop/Digital Mammography Challenge]  scp ~/.docker/machine/certs/cert.pem ${host}:/etc/docker/
cert.pem                                                                                                                    100% 1054     1.0KB/s   00:00    
[~/Desktop/Digital Mammography Challenge]  ssh ${host} sudo chmod 666 /etc/resolv.conf
[~/Desktop/Digital Mammography Challenge]  ssh ${host} sudo "printf \"nameserver 10.0.80.11\nnameserver 10.0.80.12\noptions single-request\n\" >> /etc/resolv.conf"
[~/Desktop/Digital Mammography Challenge]  ssh ${host} sudo "service network restart"
Restarting network (via systemctl):  
[  OK  ]
[~/Desktop/Digital Mammography Challenge]  ssh ${host} sudo sysctl -w net.ipv4.ip_forward=1
net.ipv4.ip_forward = 1
[~/Desktop/Digital Mammography Challenge]  eval $(docker-machine env ${host})
[~/Desktop/Digital Mammography Challenge]  echo $(docker-machine active) 
bm07
[~/Desktop/Digital Mammography Challenge]  docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
nvidia/cuda         latest              367795fb1051        10 days ago         1.615 GB
sysdig/agent        latest              b5600cdd6bcd        12 days ago         523.5 MB
hello-world         latest              c54a2cc56cbb        4 months ago        1.848 kB
[~/Desktop/Digital Mammography Challenge]  docker pull brucehoff/challengedockeragent
Using default tag: latest
latest: Pulling from brucehoff/challengedockeragent
a3ed95caeb02: Pull complete 
bac86908ce0f: Pull complete 
5feceb76101c: Pull complete 
eb51437d7378: Pull complete 
79b9df7b2bde: Pull complete 
65f8fdcc5fe7: Pull complete 
76183e43a254: Pull complete 
ac533b6202ac: Pull complete 
d1e04a858376: Pull complete 
ae5264b87952: Pull complete 
d92865074fe9: Pull complete 
Digest: sha256:d51744af346020524765ab955373cc455178e8166e327dc0b5f6eb5b7fccc7ca
Status: Downloaded newer image for brucehoff/challengedockeragent:latest


>  Can you try moving the code that I gave you after ssh ${host} sudo sysctl -w net.ipv4.ip_forward=1?

Yes.

**Comment by tschaffter** [comment]
I've just reseted the internet connection on bm21.

**Comment by tschaffter** [comment]
Docker on bm07 is not configured to use LVM.
Let's review the process together during the Hangouts at 2 pm.

**Comment by brucehoff** [comment]
I tried bm21 again and found the same problem as before:
```
[~/Desktop/Digital Mammography Challenge]  export host=bm21
[~/Desktop/Digital Mammography Challenge]  
[~/Desktop/Digital Mammography Challenge]  docker-machine create --driver generic --generic-ip-address=${host}-dreamchallenge.sl851865.sl.edst.ibm.com --generic-ssh-key=/Users/bhoff/.ssh/id_rsa_docker-machine --generic-ssh-user=dreamuser ${host}
Running pre-create checks...
Creating machine...
(bm21) Importing SSH key...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with redhat...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: Something went wrong running an SSH command!
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.


```

**Comment by brucehoff** [comment]
I think we have this working now.  Thomas, would you please close when you are done?
