### ISSUE TITLE
monitor submission in regular lane

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#301]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1294

**Comment by tschaffter** [comment]
@brucehoff We had several questions recently regarding the dashboard for the remaining submission queues. If there is nothing tricky, can you create a sub-wiki page for each missing dashboard?

**Comment by thomasyu888** [comment]
Right now they can see the status on the `Submitting to Models` page right?

**Comment by brucehoff** [comment]
> Right now they can see the status on the Submitting to Models page right?

Right!

**Comment by brucehoff** [comment]
Leaderboard dashboards are here: https://www.synapse.org/#!Synapse:syn4224222/wiki/401759
Express lane dashboards are here: https://www.synapse.org/#!Synapse:syn4224222/wiki/409764
