### ISSUE TITLE
No such file or directory: '/trainingData/146747.dcm'

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#333]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1290

@brucehoff Yuanfang Guan reported an issue without giving much precision regarding the submission ID. I check on bm01 and the missing image that she report is there. What is the machine on which she is running her submission?

**Comment by brucehoff** [comment]
Thomas:  The following page shows that her submissions have run on a number of machines.  This can happen if no preprocessing is used (in which case the submission can run anywhere).  The machines include bm16, bm01, bm21, bm02
https://www.synapse.org/#!Synapse:syn5644795/wiki/405302

**Comment by brucehoff** [comment]
Thomas:  If you could ask her for the Submission ID we could look in deeper.

**Comment by tschaffter** [comment]
Duplicate of #347.
