### ISSUE TITLE
bm08: Docker has stopped

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#336]
I can't connect with 'docker machine' and there are some stalled express lane jobs.

Note:  This email was sent by a challenge agent on bm08 last night:
```
Submission  to TRAIN failed. Agent: bm08-1 

 The message is:

	Submission ID: 7820868
/tempDir/7820868_my-example_preproccessing_logs.txt (No space left on device)

```
where `/tempDir` on the host is `/root/tempDir0`.

**Comment by brucehoff** [comment]
I tried logging in and running 'sudo service docker start' but it didn't help.  @tschaffter would you have a look?

**Comment by brucehoff** [comment]
I cleared the preprocessing slots and restarted the stalled submissions so that bm09 will pick them up and process them.

**Comment by tschaffter** [comment]
The first thing to test is make sure that the machine is reachable via ssh. If not, you can open a ticket and I'll check the status of the machine.

**Comment by brucehoff** [comment]
> The first thing to test is make sure that the machine is reachable via ssh.

Yes, I can connect via ssh (see below).

I could not connect via docker.  I restarted the docker daemon but there are no containers, running or otherwise.

> If not, you can open a ticket and I'll check the status of the machine.

Not sure what you mean by "you can open a ticket."

```
ssh bm08
Last login: Tue Dec 13 14:36:57 2016 from ec2-52-204-173-232.compute-1.amazonaws.com
[dreamuser@bm08 ~]$ exit
logout
Connection to bm08-dreamchallenge.sl851865.sl.edst.ibm.com closed.
ubuntu@ip-172-31-59-223:~$ eval  $(docker-machine env bm08)
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "bm08-dreamchallenge.sl851865.sl.edst.ibm.com:2376": dial tcp 169.45.173.51:2376: getsockopt: connection refused
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.

ubuntu@ip-172-31-59-223:~$ ssh bm08
Last login: Tue Dec 13 14:37:51 2016 from ec2-52-204-173-232.compute-1.amazonaws.com
[dreamuser@bm08 ~]$ sudo service docker start
Redirecting to /bin/systemctl start  docker.service
[dreamuser@bm08 ~]$ exit
logout
Connection to bm08-dreamchallenge.sl851865.sl.edst.ibm.com closed.
ubuntu@ip-172-31-59-223:~$ 
ubuntu@ip-172-31-59-223:~$ 
ubuntu@ip-172-31-59-223:~$ 
ubuntu@ip-172-31-59-223:~$ 
ubuntu@ip-172-31-59-223:~$ eval  $(docker-machine env bm08)
ubuntu@ip-172-31-59-223:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
ubuntu@ip-172-31-59-223:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
ubuntu@ip-172-31-59-223:~$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

```

**Comment by tschaffter** [comment]
I'm currently working on bm08. The progress are tracked in #262 .

> Not sure what you mean by "you can open a ticket."
Open a GitHub ticket as you did. If you restart the machine and cannot access it via ssh (for some reason some of your reboot don't go through), please let me know.

**Comment by brucehoff** [comment]
Closing as duplicate of #262.  Thank you, @tschaffter
