### ISSUE TITLE
submission quota exceeded

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#340]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1336

**Comment by thomasyu888** [comment]
What is the difference between an INVALID submission and a CLOSED submissions.  This participant is asking why we are counting failed submissions in the submission quota since I think earlier, I told them that we weren't counting INVALID submissions.

**Comment by brucehoff** [comment]
@thomasyu888:  This is my bad.  I responded on the forum and also fixed the code:
https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/e8e1609cf5eee5e90e4815912d0156c7a9daca48
