### ISSUE TITLE
Sub-challenge 2 express-lane scoring failed: training is not allowed

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#342]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1340

**Comment by thomasyu888** [comment]
Is training allowed when you are submitting to express lanes?

**Comment by brucehoff** [comment]
@thomasyu888 : No, it's not.  Please see my response on the forum.  I also updated the error message to make it clearer: https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/0eebe523918ab2fae88cf6a3f986f7b6ad073ebd
