### ISSUE TITLE
i encountered this error multiple times, each with different images, what could be the possible reason?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#347]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1347

**Comment by tschaffter** [comment]
@brucehoff Yuanfang Guan provided a submission ID. Can you tell me on which machine it ran? Thanks!

**Comment by brucehoff** [comment]
> @brucehoff Yuanfang Guan provided a submission ID. Can you tell me on which machine it ran? 

```
> ss<-synGetSubmission("7836368", downloadFile=F)
> ss@submissionContent@evaluationId
[1] "7213944"
> synGetEvaluation("7213944")@name
[1] "Digital Mammography Model Training"
```
So, this is the production submission queue.  We then visit this page:

https://www.synapse.org/#!Synapse:syn5644795/wiki/405302

and search for the submission ID 7836368.  (Scroll down to the 'All Submissions' table and click on 'objectId' which will make the table sort by submission id, descending, showing the most recent 100 submissions.)  For this submission "WORKER_ID" is "bm16-1" which means agent 1 of 2 on machine "bm16" ran the submission.

Since we keep the containers after running them you can inspect her output:
```
ubuntu@ip-172-31-59-223:~$ eval $(docker-machine env bm16)
ubuntu@ip-172-31-59-223:~$ docker ps -a
CONTAINER ID        IMAGE                                                                                                                      COMMAND                  CREATED             STATUS                         PORTS               NAMES
5bde7384c236        docker.synapse.org/syn7813569/tfexample@sha256:98d3c54139a784249979299b9bcb770ac74320f3319c41bfe1d8102eb17d8cbf            "/train.sh"              About an hour ago   Exited (1) About an hour ago                       archive.7836539.bm16-2.TRAIN.TRAINING
a71153196335        docker.synapse.org/syn7221819/sc1_pre_train@sha256:5e904d581deebf9177e02d630bf0a7ff8cf07cfa386b91287e484fb7f9a8b720        "/train.sh"              3 hours ago         Exited (1) 3 hours ago                             archive.7836368.bm16-1.TRAIN.TRAINING
3567dc7bdf75        brucehoff/challengedockeragent                                                                                             "/bin/sh -c 'exec mvn"   12 hours ago        Up 12 hours                                        bm16-train-2
aa1e4398400e        brucehoff/challengedockeragent                                                                                             "/bin/sh -c 'exec mvn"   12 hours ago        Up 12 hours                                        bm16-train-1
d910b0487c56        docker.synapse.org/syn7272737/dm_preprocessing_r@sha256:ec46478f87acb78bf173b0c58027439c0944fa790959e725b2a6db2923b50190   "/preprocess.sh"         2 days ago          Exited (0) 44 hours ago                            archive.7829414.bm16-1.TRAIN.PREPROCESSING
abfe5fdbc747        docker.synapse.org/syn7221819/sc1_pre_train@sha256:c4e33306dd20ea759c0b32bec71638da18f5bbab7166751bf67befefcec22a7f        "/train.sh"              3 days ago          Exited (1) 3 days ago                              archive.7828234.bm16-2.TRAIN.TRAINING
6e34b43c35bf        docker.synapse.org/syn7221819/sc1_pre_train@sha256:c4e33306dd20ea759c0b32bec71638da18f5bbab7166751bf67befefcec22a7f        "/train.sh"              3 days ago          Exited (1) 3 days ago                              archive.7828218.bm16-2.TRAIN.TRAINING
ae24de03c92b        docker.synapse.org/syn7221819/sc1_pre_train@sha256:8a7a41b83ffbd68a4ea7da357c39febaf37fe0ef7595c8a142969b829b5e35fb        "/train.sh"              4 days ago          Exited (0) 4 days ago                              archive.7824819.bm16-1.TRAIN.TRAINING
fcbd8840c085        docker.synapse.org/syn7221819/sc1_pre_train@sha256:d0b8028a397512f7403b47ed22ee32cb94bce80f975f70aab8c60d87d5ab0f82        "/train.sh"              5 days ago          Exited (0) 5 days ago                              archive.7818652.bm16-1.TRAIN.TRAINING
1d8049b6b6d3        docker.synapse.org/syn5644795/nvml-statsd                                                                                  "/bin/sh -c 'python /"   3 weeks ago         Up 3 weeks                                         nvml-statsd
961f8dfc5410        sysdig/agent                                                                                                               "/docker-entrypoint.s"   3 weeks ago         Up 3 weeks                                         sysdig-agent
ubuntu@ip-172-31-59-223:~$ docker logs archive.7836368.bm16-1.TRAIN.TRAINING
Using gpu device 0: Tesla K80 (CNMeM is enabled with initial size: 10.0% of memory, cuDNN 5103)
Traceback (most recent call last):
  File "test_code_cut_and_no_cut/main.py", line 91, in <module>
    (yup,ydown,xleft,xright,left_img_cut)=function_256cut.read_img_pix(PathDicom,left_img)
  File "/test_code_cut_and_no_cut/function_256cut.py", line 15, in read_img_pix
    d= dicom.read_file(os.path.join(PathDicom,figure))
  File "/usr/local/lib/python2.7/dist-packages/dicom/filereader.py", line 589, in read_file
    fp = open(fp, 'rb')
IOError: [Errno 2] No such file or directory: '/trainingData/593801.dcm'
max_performance_sep
Traceback (most recent call last):
  File "test_code/generate_gs_tmp.py", line 40, in <module>
    FILE=open('scratch/list_test_sc1_pred','r')
IOError: [Errno 2] No such file or directory: 'scratch/list_test_sc1_pred'
cut: scratch/list_test_sc1_pred: No such file or directory
Traceback (most recent call last):
  File "./eva_code/eva_image.py", line 9, in <module>
    y=np.loadtxt(gs_file)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 803, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: 'scratch/gs_tmp.txt'
```

Offhand I'd say the problem is that she omitted the leading "/", i.e., she used 'scratch/list_test_sc1_pred' when she should have used '/scratch/list_test_sc1_pred'.

**Comment by brucehoff** [comment]
Update: Looking more closely at her output I see that there are multiple errors.  I checked to see if the cited .dcm file is on bm16:
```
ubuntu@ip-172-31-59-223:~$ ssh bm16
Last login: Mon Nov 21 10:17:45 2016 from 52.204.173.232
[dreamuser@bm16 ~]$ cd /data/data/dm-challenge-dcm/training
[dreamuser@bm16 training]$ ls 593801.dcm
ls: cannot access 593801.dcm: No such file or directory
[dreamuser@bm16 training]$ pwd
/data/data/dm-challenge-dcm/training
[dreamuser@bm16 training]$ ls -1 | wc -l
59776
```
Not only is the file missing, but many .dcm files are gone. @tschaffter can you have a look?

**Comment by tschaffter** [comment]
@brucehoff 

The training set on bm16 is indeed missing images and I have no idea why. I've check all the other machines and they have the expected number of training/leaderboard images.

Before we continue investigating, can you move the participants on bm16 to another machines?

By any chance, is the second user who is reporting missing images also on bm16 (submission syn7829124)?

Thanks!

Thomas

**Comment by tschaffter** [comment]
See page 3 of https://docs.google.com/document/d/1loa8Y2hU6zhvN_lC_csSxL2_pm-4oVnvUYn41E647VY/edit#

**Comment by brucehoff** [comment]
> By any chance, is the second user who is reporting missing images also on bm16 (submission syn7829124)?

syn7829124 is the Synapse 'entity id' used in two submissions, both from Chao Huang (chaohuang), who opened this thread: https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1348  
Indeed those submissions run on bm16.

> Before we continue investigating, can you move the participants on bm16 to another machines?

Yes.  This query shows who is assigned to bm16:
https://www.synapse.org/#!Synapse:syn7214502/tables/query/eyJsaW1pdCI6MjUsICJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjcyMTQ1MDIgd2hlcmUgIHNlcnZlcj0nYm0xNiciLCAiaXNDb25zaXN0ZW50Ijp0cnVlLCAib2Zmc2V0IjowfQ==

The only one assigned to the machine is team 3343190, which is Chao's "Big-S2" team.

I stopped both agents as well as Chao's submitted container:

```
ubuntu@ip-172-31-59-223:~$ docker stop bm16-train-1
bm16-train-1
ubuntu@ip-172-31-59-223:~$ docker stop bm16-train-2
bm16-train-2
ubuntu@ip-172-31-59-223:~$ docker stop 7837056.bm16-2.TRAIN.PREPROCESSING
```

I removed Chao from bm16 in the slot assignment table.  Lastly I restarted Chao's submission:
```
> restart
function(id) {
ss<-synGetSubmissionStatus(id)
ss@status<-"RECEIVED"
synStore(ss)
}
> restart("7837056")
```

... and I notified him on the discussion thread.

**Comment by brucehoff** [comment]
Chao's submission is now running on bm23.

**Comment by tschaffter** [comment]
Awesome! I'll investigate a bit and redeploy the training set on bm16 (or maybe a leaderboard set to anticipate a peak of scoring in the last week of Round 1).

**Comment by tschaffter** [comment]
@brucehoff Can you please add to the README/wiki of this project the method that you described comprehensively above to figure out on which machine a submission has run?

**Comment by brucehoff** [comment]
> @brucehoff Can you please add to the README/wiki of this project the method that you described comprehensively above to figure out on which machine a submission has run?

Done.  Please review and/or edit as desired:  https://github.com/Sage-Bionetworks/DigitalMammographyChallenge
