### ISSUE TITLE
Round 1 extension?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#357]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1361

**Comment by thomasyu888** [comment]
Please respond to this thread

**Comment by tschaffter** [comment]
@thomasyu888 The original participant mentions that there is no one appearing in the leaderboard. Do we show the leaderboard somewhere?

**Comment by brucehoff** [comment]
@thomasyu888 : We have not displayed a leaderboard.

Closing this issue since @tschaffter responded to the (IMHO whiny) participants.
