### ISSUE TITLE
Submission runs fine locally but stops in express lane

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#358]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1362

**Comment by thomasyu888** [comment]
I tried my best to answer.  I think shes just going over to limit

**Comment by brucehoff** [comment]
>  I think shes just going over to limit

Then why does she get no log file output from her python script at all? To answer would take some in-depth sleuthing.  In any case I don't think it's a problem with our infrastructure.

**Comment by thomasyu888** [comment]
It seems that the 2nd script in her code doesn't run at all so it times out... Not sure how to proceed with this.

**Comment by brucehoff** [comment]
Her submission has been running for five days on bm07 without an evidence of a problem.  I asked her to explain if she thinks there's still a problem for us to look into. In the meantime I am closing this issue.
