### ISSUE TITLE
Submission in team  : has a conflicting submission

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#359]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1364

**Comment by tschaffter** [comment]
Can we add a message to notify INDIVIDUAL PARTICIPANTS ONLY that they will not be able to submit as part of a team if they submit their current job? We should not blindly accede to the request of individuals who may have used the system of hours or submitted N jobs and who now want to join a team.

**Comment by thomasyu888** [comment]
This is the best I can do without the help of the platform team to put an alert:

![image](https://cloud.githubusercontent.com/assets/10556275/21333940/5f0d3c78-c608-11e6-9003-da759245dc88.png)
