### ISSUE TITLE
Exception scoring submission Sub-Challenge 2 Express Lane: File "challenge.py", line 222 not enough arguments for format string

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#361]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1366

**Comment by thomasyu888** [comment]
There is an issue where:

it reports very clearly in my message that there no directory called output, while i run the exactly the same thing on fast lane it works fine.
