### ISSUE TITLE
Invalid literal error when parsing metadata file for Express Lane data

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#364]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1369

**Comment by brucehoff** [comment]
Tom:  I think this is addressed our documentation.  You might check with Thomas S.

**Comment by tschaffter** [comment]
This is related to the initial error in the Tensorflow script, which has been fixed since.
