### ISSUE TITLE
Scoring express lane no confirmation email or status update

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#370]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1380

**Comment by thomasyu888** [comment]
Are log files generated when participants submit to SC1, SC2 express lanes?

**Comment by brucehoff** [comment]
> Are log files generated when participants submit to SC1, SC2 express lanes?

No.  The only confirmation is from your code, Tom.  (There is another issue to provide log files for inference submissions to the *express lane* only, but that hasn't been implemented yet.)
