### ISSUE TITLE
What's the "VALIDATED" status and why is my job stuck?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#380]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1388

**Comment by thomasyu888** [comment]
Will all models submitted before the 23rd will run past the 23rd even when the queues are shut down?

**Comment by brucehoff** [comment]
> Will all models submitted before the 23rd will run past the 23rd even when the queues are shut down?

The official answer is that the round ends after 12/23 so all work on the servers should be completed by then.   Thomas S. and I plan to meet after the weekend to decide the disposition of any jobs that remain running.  We will likely gracefully terminate any training jobs and then try to let any scoring jobs keep running to completion.  I don't want to broadcast this plan, because then people will expect that we follow it to the letter.  I'd rather wait and see what's left running after the weekend.

Does that help?

**Comment by thomasyu888** [comment]
Thanks for the response. How should I respond to this thread then?

**Comment by brucehoff** [comment]
> Thanks for the response. How should I respond to this thread then?

Not sure how to phrase this politely but he is asking about a job he submitted on 12/18 along with the big spike, so he shouldn't assume that we have the resources to run it by 12/23.  We will run it if the currently running (and other queued) jobs finish in time.   If the server cluster doesn't get to his job then he can submit again at the start of round 2.

We have enough servers to process submissions spread out over 5 weeks but not enough to process a big last minute spike.

Can you think of a P.C. way to say this?
