### ISSUE TITLE
implementing modelState periodic update

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#386]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1394

**Comment by brucehoff** [comment]
I think the real issue here is that Yuanfang's code is not writing model state at the frequency that she thinks it is.  I responded on the forum, pursuing that part of the discussion.

@tschaffter you say:  "Nonetheless, I'll check Bruce to see if it's something that we can offer."  I didn't discuss this on the forum, but here I will comment that I *really* want to avoid doing what she asks -- if at all possible -- for two reasons:

1) Doing so would either (a) be a big data leak (e.g. if we permitted 1GB upload every 15 minutes), or (b) would dramatically reduce the permitted model state size (e.g. if we said you could upload 10 MB, each 15 minutes, up to 25 hours).

2) Doing so would mess with our model of reproducibility, because reproducing a submission would be a matter of knowing which of a series of model states the participant 'grabbed' and used in a scoring submission.  Admittedly we could address this by versioning (i.e. a scoring submission would include both the Synapse ID and version of a model state archive), but there's no telling what the rationale was for choosing one part of the series over another.

**Comment by tschaffter** [comment]
Model should not be updated the way she suggests, however a nice feature would be to allow the participant to retrieve the current state of their model "on demand". Retrieving the model would only be possible if its size is smaller than the available "data credit", which are then consumed. This would be a great solution to the 1 GB limit of the models, allowing participants to retrieve the model when they have the required "data credit". This approach would not lead to a data leak if the data credit increases through time.

In term of implementation, a lock should be put in place when the code of the participants update the model to /modelState. E.g. we could ask them to create an empty file /modelState/lock before saving the model, before removing it. Synapse could regularly archives the latest version of the model (using only a lock when reading it) and propose it to the participants, who can then download it if they have enough data credit.

The reproducibility of the training may already not be clear. Participant can get a trained model from a training run and resume from it in a following run. As we have previously agreed with Gustavo, the most important item we are interested in is the content of the docker containers that are submitted to the scoring submission queue.

I find this discussion very interesting and would appreciate your feedback on the above item. Both Yaron and Umar have recently contacted me for issue on the model size. For Umar, the limit was reached when using an off-the-shelf method on 500x500 images (he is now using smaller images). I think that it would be great if we could allow participants to retrieve models larger than 1 GB, thus avoiding to indirectly limit the inference capability of their method.

**Comment by brucehoff** [comment]
> a nice feature would be to allow the participant to retrieve the current state of their model "on demand".

Yes, that is an interesting idea.  I have had an unspoken assumption that models only improve with time, so that a participant only needs two choices: (1) halt training since a model isn't ever going to be valuable or (2) let it keep improving and get the final version.  This begs the question:  What is the scenario in which it's better to have *both* an early and a later version of the model state, rather than just the final one?

> The reproducibility of the training may already not be clear. 

Yes, you are right.   For example, any analysis done by the participant (e.g. choosing which of several trained models to submit for scoring) is not captured by us and so is not reproducible.  As you say, the only thing which we should expect to reproduce is the scoring submission itself.

> I think that it would be great if we could allow participants to retrieve models larger than 1 GB, thus avoiding to indirectly limit the inference capability of their method.

Yes, we should make discussing this an agenda item at the next group meeting and try to make a decision for round 2.  

Thanks.
