### ISSUE TITLE
How to cancel the running job?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#390]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1402

**Comment by thomasyu888** [comment]
Do we not have instructions for how to submit? Uploading file to synapse and then submitting to a challenge queue?

**Comment by brucehoff** [comment]
> Do we not have instructions for how to submit?

Yes, we have instructions on how to submit.

**Comment by thomasyu888** [comment]
Apologies, but maybe I'm not looking closely enough. I dont see any instructions on how to upload a file and then click tools and click submit to challenge anywhere.  There are also no instructions on how to submit to a challenge via the python client.  I have documentation waiting to be pulled into the doc site, but just wanted to make sure this was covered somewhere so I can point participants somewhere if they have questions.

**Comment by brucehoff** [comment]
> I dont see any instructions on how to upload a file and then click tools and click submit to challenge anywhere.


On this page: https://www.synapse.org/#!Synapse:syn4224222/wiki/401759
under "Pre-processing submission" (second to last paragraph) it says
```
clicking on the button Tools > Submit to Challenge. Indicate whether you are working individually or on behalf of a team (your selection must be the same for all submissions within a challenge round). Click Submit.
```
I do see the mistake that, just before this part, it says "...submitted to the training Express Lane..." when it should say "...submitted to the training queue..."  

Would you care to fix this error and to clarify the submission process generally?

> There are also no instructions on how to submit to a challenge via the python client. 

That's true, but I haven't seen a request to submit from Python.  If you think that's of interest it can certainly be added to the instructions.

**Comment by thomasyu888** [comment]
Thanks for clarifying. I mustve just missed it and no worries. I dont think its necessary for any instructions on submitting from our clients.
