### ISSUE TITLE
Validation Express lane error

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#397]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1412

**Comment by tschaffter** [comment]
@thomasyu888 Can you answer this thread? Thanks!

**Comment by thomasyu888** [comment]
Are the express lanes down?  I didn't think that there was a backup on the express lane training queue.

**Comment by thomasyu888** [comment]
There is just a big backlog of submissions for both express lanes and leaderboard lanes
