### ISSUE TITLE
VALIDATED limbo

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#400]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1414

**Comment by tschaffter** [comment]
Separately from the question, did we decided to replace VALIDATED by QUEUE or is VALIDATE clear enough?

**Comment by thomasyu888** [comment]
I think VALIDATED is clear enough, but we should answer their questions.  In past challenges as long as participants submit before the deadline, their models will be scored.  It seems unfair if we don't allow that for the DM challenge especially when training takes so long.
