### ISSUE TITLE
Are we allowed to use the trained models for academic research purposes after the competition?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#402]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1416

**Comment by thomasyu888** [comment]
I think the answer is yes but i want to confirm

**Comment by thomasyu888** [comment]
Please help answer this thread

**Comment by brucehoff** [comment]
@thomasyu888 : Please pass the question along to Justin and Gustavo.
