### ISSUE TITLE
What will happen the day after tomorrow?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#406]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1418

**Comment by tschaffter** [comment]
@brucehoff Can we stop the training submissions next week and easily make the agents return the current state of the model (as if the submission ended successfully)?

**Comment by brucehoff** [comment]
Yes: We can send a 'cancel request' to each running job, just as if the user pressed the 'cancel' button.   This will stop the container, zip up the model state and return it to them (as long as it does not exceed the data size limit).
