### ISSUE TITLE
bm14 all containers were lost

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#408]
containers were not just stopped but lost entirely.  This includes the challenge agents as well as two jobs that were running for a long time:  Submission IDs 7882642, 7874358.  These training jobs will have to be requeued.

**Comment by tschaffter** [comment]
Because the machines have been very stable during Round 3, I'm closing all the tickets related to reboot that are more than one month old. If a new issue is raising an a machine, we can easily look at its history of issues on GitHub.
