### ISSUE TITLE
bm15 lost agent and participants' containers

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#412]
These two submissions were in progress on bm15: 7889879, 7837056, but at the present time there are no agent or participant containers, running or stopped, on that machine:
```
docker ps -a
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS              PORTS               NAMES
2096b2964fc3        docker.synapse.org/syn5644795/nvml-statsd   "/bin/sh -c 'python /"   4 weeks ago         Up 13 hours                             nvml-statsd
9c07349272e4        sysdig/agent                                "/docker-entrypoint.s"   4 weeks ago         Up 13 hours                             sysdig-agent
```

**Comment by tschaffter** [comment]
I just saw that a few minutes ago when looking at the sysdig dashboard.
https://app.sysdigcloud.com/#/dashboards/l:10/11905

You can restart the agent on that machine.

**Comment by tschaffter** [comment]
Because the machines have been very stable during Round 3, I'm closing all the tickets related to reboot that are more than one month old. If a new issue is raising an a machine, we can easily look at its history of issues on GitHub.
