### ISSUE TITLE
scoring submissions are missing inference files

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#422]
@thomasyu888 reported that the following 32 submissions has status ACCEPTED but has no PREDICTIONS_FILE, so his scoring code marked them INVALID.

7453778 is sub-challenge 1, 7453793 is sub-challenge 2 (neither is the express lane).

I verified that no predictions files were uploaded for these submissions.

```
submission	evaluation	SUBMITTER	SUBMITTER	modifiedOn


7899217	7453778	SUBMITTER	3343123	2016-12-23T22:10:18.315Z
7899336	7453778	SUBMITTER	3346945	2016-12-23T22:10:28.925Z
7900460	7453778	SUBMITTER	3343123	2016-12-23T22:10:38.790Z
7900505	7453778	SUBMITTER	3345912	2016-12-23T22:10:48.938Z
7900506	7453778	SUBMITTER	3345912	2016-12-23T22:10:58.491Z
7900550	7453778	SUBMITTER	3345212	2016-12-23T22:11:29.130Z
7900699	7453778	SUBMITTER	3347757	2016-12-23T22:11:39.015Z
7901368	7453778	SUBMITTER	3346672	2016-12-23T22:11:48.541Z
7902116	7453778	SUBMITTER	3347757	2016-12-23T22:11:59.016Z
7904006	7453778	SUBMITTER	3347202	2016-12-23T22:12:08.920Z
7904009	7453778	SUBMITTER	3347202	2016-12-23T22:12:33.324Z
7904048	7453778	SUBMITTER	3347507	2016-12-23T22:12:42.174Z
7904493	7453778	SUBMITTER	3345912	2016-12-23T22:12:51.448Z
7904505	7453778	SUBMITTER	3345912	2016-12-23T22:13:00.344Z
7904575	7453778	SUBMITTER	3345464	2016-12-23T22:13:10.254Z
7904698	7453778	SUBMITTER	3346672	2016-12-23T22:13:41.406Z
7904768	7453778	SUBMITTER	3346672	2016-12-23T22:13:51.047Z
7904850	7453778	SUBMITTER	3345212	2016-12-23T22:14:01.237Z
7905051	7453778	SUBMITTER	3347516	2016-12-23T22:14:11.532Z
7905175	7453778	SUBMITTER	3345277	2016-12-23T22:14:20.815Z
7905339	7453778	SUBMITTER	3345277	2016-12-23T22:14:44.963Z
7905544	7453778	SUBMITTER	3345464	2016-12-23T22:14:53.863Z
7901603	7453793	SUBMITTER	3347757	2016-12-23T22:15:05.175Z
7902117	7453793	SUBMITTER	3347757	2016-12-23T22:15:14.379Z
7902649	7453793	SUBMITTER	3347537	2016-12-23T22:15:23.633Z
7904011	7453793	SUBMITTER	3347202	2016-12-23T22:15:46.788Z
7904012	7453793	SUBMITTER	3347202	2016-12-23T22:15:55.597Z
7904801	7453793	SUBMITTER	3319559	2016-12-23T22:16:05.573Z
7904997	7453793	SUBMITTER	3345212	2016-12-23T22:16:16.229Z
7905179	7453793	SUBMITTER	3345277	2016-12-23T22:16:25.369Z
7905332	7453793	SUBMITTER	3345212	2016-12-23T22:16:52.667Z
7905343	7453793	SUBMITTER	3345277	2016-12-23T22:17:02.001Z
```

**Comment by brucehoff** [comment]
Earlier today I introduced a scoring 'validator' which checks (but doesn't run) inference submissions, and changes their status from RECEIVED to VALIDATED or INVALID.  The problem would totally be explained if the scoring app' processes VALIDATED submissions as well as ACCEPTED ones.

**Comment by thomasyu888** [comment]
I think that is the issue.  My code looks for ACCEPTED to validate the prediction file and VALIDATED to score the prediction file

**Comment by brucehoff** [comment]
I introduced a problem by using "VALIDATED" to mean the runnable submission was valid but not yet run.  This totally explains the problem.  Don't change anything, I will come up with a workaround.

**Comment by thomasyu888** [comment]
Thanks Bruce!

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/49538e2d4a1d6a6e22c88319259ed9b99729fa62

**Comment by brucehoff** [comment]
I also reset the 32 submissions to RECEIVED so they will be processed again.

**Comment by thomasyu888** [comment]
Please also check for any submissions that have the submission status VALIDATED now? The list of 32 I gave you was just the ones that my scoring harness threw an error on.

**Comment by brucehoff** [comment]
@thomasyu888 I just checked:  There are no VALIDATED submissions in SC1 or SC2, in either the regular or express lane queues.  I reset 37 submissions to RECEIVED (your list of 32, plus four more in SC1 plus one more in SC2).

I am now using "OPEN" to represent the state that a submission has been validated but the container not yet run, this should not "collide" with your scoring app.

Whenever you're ready please restart the scoring app.

**Comment by thomasyu888** [comment]
Thanks Bruce! I just restarted the scoring app.
