### ISSUE TITLE
bm23: all containers lost

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#423]
including two running submissions: 7905242, 7904737

**Comment by tschaffter** [comment]
I had a look at the machine. You can restart the submission if you want.

Thanks!

**Comment by brucehoff** [comment]
I restarted the agents, and new submissions began but were lost in less than 10 minutes: 7905242, 7905295.  Since Round 1 is over there is not much point in restarting the submissions.

**Comment by tschaffter** [comment]
Because the machines have been very stable during Round 3, I'm closing all the tickets related to reboot that are more than one month old. If a new issue is raising an a machine, we can easily look at its history of issues on GitHub.
