### ISSUE TITLE
Errors - is there any hope?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#430]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1435

**Comment by thomasyu888** [comment]
Hey Bruce,

I know you sent me an email about this, but could you answer this participant on the forum.  I already responded him via email, but I'm not sure if you want us to broadcast our plans.  Maybe we should send a newsletter about our plans about looking through invalidated prediction files.

**Comment by brucehoff** [comment]
I responded on the forum.
