### ISSUE TITLE
Whenever a submission fails, store the reason as a submission annotation

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#433]
Especially for inference submissions.

**Comment by brucehoff** [comment]
As @thomasyu888 points out we already capture validation errors from the challenge agent.  The one, small omission in the challenge agent is capturing errors that occur while running the validated container, e.g. that the container stopped with an error code or that the container finished but produced no predictions file.

**Comment by thomasyu888** [comment]
I wrote code to add all validation errors for the prediction file to the FAILURE_REASON annotation.    I will be going through the INVALID submissions and adding the annotations.

**Comment by brucehoff** [comment]
> I will be going through the INVALID submissions and adding the annotations.

There are some submissions that have status INVALID and already have a FAILURE_REASON.  These would include submissions that failed the first validation stage (before the Docker container was run).  Please don't overwrite the existing FAILURE_REASON.

**Comment by thomasyu888** [comment]
Right, I will only be looking at INVALID submissions that don't have a FAILURE_REASON. Thanks for the reminder

**Comment by brucehoff** [comment]
I would look for INVALID submissions that have a PREDICTIONS_FILE annotation.  For such submissions you can conclude that it was your scoring code which set the submission to INVALID.  (There may be other submissions which are INVALID and have no FAILURE_REASON but were not set to INVALID by your scoring code.)  Thank you.

**Comment by thomasyu888** [comment]
Right. I will look for those.  There are only actually 8 submissions that fall under that criteria.  Just out of curiosity, how else could a submission be marked INVALID without having a FAILURE_REASON.

**Comment by brucehoff** [comment]
> Just out of curiosity, how else could a submission be marked INVALID without having a FAILURE_REASON.

Please see my first comment on this issue, which answers this question.

**Comment by thomasyu888** [comment]
Thanks Bruce.  I realized you had answered it already so I made an edit on my comment

**Comment by thomasyu888** [comment]
I'm ready to close this issue if you are Bruce

**Comment by brucehoff** [comment]
@thomasyu888 I have not yet made the related changes in the challenge agent.  I will remove you  as an assignee and close when I'm done.

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/5754334e92780570a36a467dbd31cc87d1e6205a
