### ISSUE TITLE
Validation error in submission to Digital Mammography Prediction - Sub-Challenge 1

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#437]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1440

**Comment by tschaffter** [comment]
@thomasyu888 Assuming that she didn't already scored 6 times (the limit for Round 1), can you score her submission as she requests and return her the three metrics? This submission should not be taken into account for the ranking of the participants. The scoring of her submission can wait until next week. :) Thanks!

**Comment by thomasyu888** [comment]
I scored and returned her three metrics.
