### ISSUE TITLE
Where do I send the submission file?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#444]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1449

**Comment by thomasyu888** [comment]
Should we highlight this information on the wiki or have a specific section on how to submit?  Unfortunately I currently have this in the works for the doc site, but it is still a pull request and needs lots of review.

**Comment by thomasyu888** [comment]
Done.
