### ISSUE TITLE
containers won't start or be removed on bm02

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#445]
Challenge agent received this error:
```
	Submission ID: 7988835
{"message":"containerd: container did not start before the specified timeout"}
```
On bm02 the 'directory cleaning' container did not start and now cannot be removed:
```
docker ps -a
CONTAINER ID        IMAGE                                                                                                                         COMMAND                  CREATED             STATUS                         PORTS               NAMES
0286177fd846        docker.synapse.org/syn5644795/dm-directory-clean                                                                              "/bin/bash /run.sh /d"   2 hours ago         Created                                            7988835.bm02-1.directory-cleaner
6b7e72da639f        docker.synapse.org/syn7540399/dm_challenge@sha256:0ac88f27971b5632d010afd082ee5082403cfa98d8b16ae1e8d302fab45d9422            "/train.sh"              4 hours ago         Exited (137) 2 hours ago                           archive.7988835.bm02-1.TRAIN.TRAINING
be0af9a7953d        docker.synapse.org/syn7540399/dm_challenge@sha256:02234d71d631f5acc7df92b012bea439d56047dea3e6ab6ba5c63b5c8c05df30            "/train.sh"              5 hours ago         Exited (137) 5 hours ago                           archive.7988812.bm02-1.TRAIN.TRAINING
992c517a9e73        docker.synapse.org/syn7221819/sc1_pre_train_recover@sha256:37acf8c8082ef2cfb8d1c3af76b3eff2fc77f84e9070131e9cfed9ef7cb4eb19   "/train.sh"              10 hours ago        Exited (1) 10 hours ago                            archive.7987934.bm02-1.TRAIN.TRAINING
6f36bfbe454a        docker.synapse.org/syn7364819/blue_training@sha256:e4333b0f6e9ce887b2a9baaf94bfdfc65b8c6258aee8162a4138fa8ebd773989           "/train.sh"              10 hours ago        Up 10 hours                                        7988398.bm02-2.TRAIN.TRAINING
e3e3cf96d98a        brucehoff/challengedockeragent                                                                                                "/bin/sh -c 'exec mvn"   10 hours ago        Up 10 hours                                        bm02-train-2
f0a9432a177d        brucehoff/challengedockeragent                                                                                                "/bin/sh -c 'exec mvn"   10 hours ago        Exited (1) About an hour ago                       bm02-train-1
ubuntu@ip-172-31-59-223:~$ docker rm 7988835.bm02-1.directory-cleaner
Error response from daemon: Unable to remove filesystem for 0286177fd8468d14a967abb10a0744517d15c23999be6f7425697cb575e0755f: remove /var/lib/docker/containers/0286177fd8468d14a967abb10a0744517d15c23999be6f7425697cb575e0755f/shm: device or resource busy
```

**Comment by tschaffter** [comment]
Why do you want to remove it?

**Comment by brucehoff** [comment]
> Why do you want to remove it?

In order to restore the system to an expected state.  I.e., there shouldn't be containers in the 'created' state which Docker was unable to 'start'.

**Comment by tschaffter** [comment]
Here is the command to see the docker logs:

```
# journalctl -u docker --since "3 days ago"
```

Below are the first entrees from Jan 3rd. Do that ring a bell?
```
Jan 03 22:27:31 bm02 docker[25939]: time="2017-01-03T22:27:31.920035236-06:00" level=error msg="Handler for GET /v1.24/containers/bm02-train-1/json returned error: No such container: bm02-train-1"
Jan 03 22:27:31 bm02 docker[25939]: time="2017-01-03T22:27:31.954719252-06:00" level=error msg="Handler for GET /v1.24/images/bm02-train-1/json returned error: No such image: bm02-train-1"
Jan 03 22:27:31 bm02 docker[25939]: time="2017-01-03T22:27:31.988249077-06:00" level=error msg="Error getting task bm02-train-1: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
Jan 03 22:27:31 bm02 docker[25939]: time="2017-01-03T22:27:31.988276823-06:00" level=error msg="Handler for GET /v1.24/tasks/bm02-train-1 returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
Jan 03 22:27:32 bm02 docker[25939]: time="2017-01-03T22:27:32.159982873-06:00" level=error msg="Handler for GET /v1.24/containers/bm02-train-2/json returned error: No such container: bm02-train-2"
Jan 03 22:27:32 bm02 docker[25939]: time="2017-01-03T22:27:32.193162442-06:00" level=error msg="Handler for GET /v1.24/images/bm02-train-2/json returned error: No such image: bm02-train-2"
Jan 03 22:27:32 bm02 docker[25939]: time="2017-01-03T22:27:32.226291681-06:00" level=error msg="Error getting task bm02-train-2: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
Jan 03 22:27:32 bm02 docker[25939]: time="2017-01-03T22:27:32.226338990-06:00" level=error msg="Handler for GET /v1.24/tasks/bm02-train-2 returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
Jan 04 04:18:22 bm02 docker[25939]: time="2017-01-04T04:18:22.352282313-06:00" level=info msg="Container be0af9a7953d4167b6f197d55dd11377a45c85728344007bb0559d5a47ebf813 failed to exit within 10 seconds of signal 15 - using the force"
Jan 04 07:20:39 bm02 docker[25939]: time="2017-01-04T07:20:39.003971625-06:00" level=info msg="Container 6b7e72da639fdf2cc94b9ce174e537266a2151a7560abd5efe80f3bbb09e5f49 failed to exit within 10 seconds of signal 15 - using the force"
Jan 04 07:22:49 bm02 docker[25939]: time="2017-01-04T07:22:49.785712842-06:00" level=error msg="containerd: start container" error="containerd: container did not start before the specified timeout" id=0286177fd8468d14a967abb10a0744517d15c23999be6f7425697cb575e0755f
Jan 04 07:22:49 bm02 docker[25939]: time="2017-01-04T07:22:49.786190204-06:00" level=error msg="Create container failed with error: containerd: container did not start before the specified timeout"
```

If not, Docker is current not very responsive. I've pulled the ubuntu image but wasn't able to start it due to a time out. I would recommend to restart docker.

**Comment by brucehoff** [comment]
> Below are the first entrees from Jan 3rd. Do that ring a bell?

The Jan 3 entries reflect my activity starting up the agents. (I assume the time zone is central time, which makes sense since the Softlayer data centers are in Texas.) The last three commands appear to match the error message found by the challenge agent.

> I would recommend to restart docker.

Is the recommended command for this `sudo docker service restart`?

**Comment by tschaffter** [comment]
> Jan 03 22:27:31 bm02 docker[25939]: time="2017-01-03T22:27:31.988249077-06:00" level=error msg="Error getting task bm02-train-1: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."

I don't know yet about "docker swarm". Is that something that you use?

> Is the recommended command for this sudo docker service restart?
Yes. If docker is not responsive, you can try to restart the machine.

**Comment by brucehoff** [comment]
> Is that something that you use?

Not explicitly, but the docker commands (docker create, docker start) may do so 'behind the scenes'.  Some time ago 'docker swarm' was a separate tool from Docker but as of last year they (along with some other tools) were merged together.

**Comment by brucehoff** [comment]
Now that the user containers are done running on bm02 I tried restarting docker:
```
[dreamuser@bm02 ~]$ sudo service docker restart
Redirecting to /bin/systemctl restart  docker.service
Failed to restart docker.service: Connection timed out
See system logs and 'systemctl status docker.service' for details.
[dreamuser@bm02 ~]$ 
```
Since this didn't work, what's the next step?  Can I `sudo reboot` the machine?

**Comment by tschaffter** [comment]
@brucehoff  All systemctl services are not responsive, including the reboot "service". I want to open a DST ticket so that they can study the machine in that state since this is not the first time that we have this issue. Can we move the users of that machine to another? It's likely going to take at least two days for the DST to troubleshot this issue.

**Comment by brucehoff** [comment]
> Can we move the users of that machine to another? 

Yes.  This an 'express lane' training machine.  We will use bm09 for now. Currently there is little activity on the express lane, but if we start to experience too big of a back log in processing express lane submissions we will have to revisit the machine allocation.

**Comment by tschaffter** [comment]
@brucehoff  bm02 is not listed as an express lane machine (https://docs.google.com/document/d/1loa8Y2hU6zhvN_lC_csSxL2_pm-4oVnvUYn41E647VY/edit#). Are you sure you don't mistake it for bm08, the second machine that has issue?

**Comment by tschaffter** [comment]
@brucehoff Let me know if I can contact the DST so that they have a look at bm02.

**Comment by tschaffter** [comment]
@brucehoff The silver lining is that the non-responsive system issue occurred early in Round 2 and provide us with a minimal setup to reproduce the error. Can you think to a way to "replay" all the submissions that have run on bm02 until the machine became unresponsive? We need to make sure the containers to run will be available and if possible use the same challenge agent version that the one used. Same comment for bm08 (crash).

**Comment by brucehoff** [comment]
> @brucehoff bm02 is not listed as an express lane machine 

Yes, you are right.  I was mixing up the two on going discussions.  bm02 is a leaderboard-training machine.

> @brucehoff Let me know if I can contact the DST so that they have a look at bm02.

Yes, thanks.

**Comment by brucehoff** [comment]
> Can you think to a way to "replay" all the submissions that have run on bm02 until the machine became unresponsive? 

We can certainly rerun the submissions that ran on the machine since the beginning of round 2.  These were (submission ID, entity ID):
Agent 1:
7987934 / syn7887989 (ran for just a few seconds)
7988812 / syn7835696 (was canceled by user after one hour)
7988835 / syn7835696 (was canceled by user after three hours)
Agent 2:
7988398 / syn7446291 (ran to completion over about 24 hours)

**Comment by brucehoff** [comment]
@tschaffter 
Yes, you recall correctly!  Agent 1 shut down while Agent 2 and submission 7988398 kept running.  I believe Agent 2 shut down after 7988398 was done and Agent 2 was trying to run the clean up container.  (There is a container 7988398.bm02-2.directory-cleaner which was created but never started.)

> If this submission is the one run by agent 2, is it correct that it run to completion? 

Yes, because it wasn't the participant's container that encountered an error but rather the clean-up container that came afterwards.

> Do you know also at what point the first agent shut down and for what reason?

Yes, the `docker ps -a` command prints out time stamps, so I know that the following happened in sequence:
1) 7987934 ran (just for a few seconds)
2) 7988812 ran (canceled by the submitter after an hour)
3) 7988835 ran (canceled by the submitter after three hours). 
4) Agent 1 created 7988835.bm02-1.directory-cleaner but was not able to run it.
5) Agent 1 sent a notification about the error and stopped itself.

**Comment by tschaffter** [comment]
The DST ticket (for reference): https://ticketing.dst.ibm.com/problem/view/194572

**Comment by tschaffter** [comment]
When the machine becomes accessible again:

- Update /root/dm-scripts/cleanup_docker_data.sh

**Comment by tschaffter** [comment]
@brucehoff The DST didn't find anything wrong with bm02, whose services became unresponsive at some point last week. We already encountered this issue in the past so it's worth continuing to troubleshoot it. The next step would be to rerun the submissions that were running at the time the issue occurred. Can you run these submissions locally (without using participant time quota, etc.)?

**Comment by brucehoff** [comment]
For now the machine is running.  Will revisit if/when the problem recurs.
