### ISSUE TITLE
Do undownloaded model states count towards quota?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#446]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1452

**Comment by tschaffter** [comment]
Is the available data quota visible to the participants?

**Comment by brucehoff** [comment]
No, not yet.

**Comment by brucehoff** [comment]
The answer to "Do undownloaded model states count towards quota?" is "YES"
