### ISSUE TITLE
Running Two TensorFlow Training Processes using Different GPU Cores

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#453]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1472

**Comment by tschaffter** [comment]
I don't have experience working with Tensorflow. I've redirected the question to Darvin Yi.

**Comment by tschaffter** [comment]
The participant reported that Darvin's answer fixes his issue.
