### ISSUE TITLE
preprocessing results in round 1 still available in round 2?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#462]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1485

**Comment by tschaffter** [comment]
Once the training submission of the participant has started, can he see on the dashboard that it "jumped" the pre-processing stage and is now training?

**Comment by brucehoff** [comment]
The training/preprocessing phase isn't shown explicitly in the dashboard but it can be inferred.  For example, we send a link to a folder where the log file is uploaded.  There are two log files, one for preprocessing and another for training.  If the submitter sees a log file for training with no file for preprocessing then he can infer that the pipeline reused cached preprocessing data.

**Comment by tschaffter** [comment]
@brucehoff The OP has updated the post. Can you answer him?

**Comment by brucehoff** [comment]
Oy, vey!
