### ISSUE TITLE
Stuck in validation mode....

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#463]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1488

**Comment by tschaffter** [comment]
@brucehoff Is he waiting because the machine is processing jobs from other participants? If yes, we should tell him that it's normal and that he may have to wait for other jobs on that machine to complete before he can run his job.

**Comment by brucehoff** [comment]
> @brucehoff Is he waiting because the machine is processing jobs from other participants?
Yes.  I have a script that answers this question (see below).  He is linked to bm18 which is running other users' submissions.  There are currently 12 jobs running across 8 servers, as you can see here:
https://www.synapse.org/#!Synapse:syn5644795/wiki/405302
We currently have 11 servers, so we can process 22 jobs at a time.

One action we can take is to 'blow away' the preprocessed data for the user on bm18 so some other machine picks up the job.  You can see the entry for the preprocessed data here:
https://www.synapse.org/#!Synapse:syn7214502/tables/query/eyJsaW1pdCI6MjUsICJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjcyMTQ1MDIgd2hlcmUgdGVhbUlkPTMzNDY0MzQiLCAiaXNDb25zaXN0ZW50Ijp0cnVlLCAib2Zmc2V0IjowfQ==
The rightmost column, preprocessDuration is 58173174 millisec, or sixteen hours.  So it would be bad to lose that work if one of the other jobs on bm18 will finish in sixteen hours or less.  Also there must be a free slot available on an idle machine.  This query shows that that is not a problem:
https://www.synapse.org/#!Synapse:syn7214502/tables/query/eyJsaW1pdCI6MjUsICJzcWwiOiJTRUxFQ1Qgc2VydmVyLCBjb3VudChzZXJ2ZXIpIEZST00gc3luNzIxNDUwMiBXSEVSRSBzZXJ2ZXIgaW4gKCdibTAxJywnYm0wNycsJ2JtMTAnLCdibTE0JywnYm0xNScsJ2JtMTcnLCdibTE4JywnYm0xOScsJ2JtMjAnLCdibTIxJywnYm0yMicpIGFuZCB0ZWFtSWQgaXMgbnVsbCBncm91cCBieSBzZXJ2ZXIiLCAiaXNDb25zaXN0ZW50Ijp0cnVlLCAib2Zmc2V0IjowfQ==

Script to analyze the wait queue:
```
library(synapseClient)
synapseLogin()
analyzeIntern<-function(subs, runningSubs, table) {
	runningSubmitters<-NULL
	if (length(runningSubs@results)>0) {
		for (i in 1:length(runningSubs@results)) {
			sub<-runningSubs@results[[i]]
			if (length(sub@submissionContent@teamId)==0) {
				submitter<-sub@submissionContent@userId
			} else {
				submitter<-sub@submissionContent@teamId
			}
			runningSubmitters<-c(runningSubmitters, submitter)
		}
	}

	for (i in 1:length(subs@results)) {
		sub<-subs@results[[i]]
		if (length(sub@submissionContent@teamId)==0) {
			submitter<-sub@submissionContent@userId
		} else {
			submitter<-sub@submissionContent@teamId
		}
		row<-which(table@values$teamId==submitter)
		id<-sub@submissionContent@id
		if (length(row)==0) {
			message("team sending submission ", id, " is not bound to any server.")
		} else if (length(row)>1) {
			message("submitter ", submitter, " is bound to multiple servers.")
		} else {
			alreadyRunning <- any(runningSubmitters==submitter)
			server<-table@values$server[row]
			if (alreadyRunning) {
				message("team sending submission ", id, " is bound to server ", server, " submitter: ", submitter, 
					" user ", sub@submissionContent@userId, " ** Another submission from this team is currently running **")
			} else {
				message("team sending submission ", id, " is bound to server ", server, " submitter: ", submitter, 
					" user ", sub@submissionContent@userId)
			}
		}
	}	
}
analyzeQueuedJobs<-function(evaluationId, tableId) {
	table<-synTableQuery(paste("SELECT * from ", tableId))


	runningSubs<-synGetSubmissions(evaluationId, status="EVALUATION_IN_PROGRESS", limit=100, offset=0)
	if (length(runningSubs@results)!=runningSubs@totalNumberOfResults) stop("didn't get all the submissions")

	subs<-synGetSubmissions(evaluationId, status="RECEIVED", limit=100, offset=0)
	if (length(subs@results)!=subs@totalNumberOfResults) stop("didn't get all the submissions")
	if (length(subs@results)>0) analyzeIntern(subs, runningSubs, table)

	subs<-synGetSubmissions(evaluationId, status="VALIDATED", limit=100, offset=0)
	if (length(subs@results)!=subs@totalNumberOfResults) stop("didn't get all the submissions")
	if (length(subs@results)>0) analyzeIntern(subs, runningSubs, table)	
}

#analyzeQueuedJobs("7500018", "syn7413559") # express lane
analyzeQueuedJobs("7213944", "syn7214502") # production
```
This script currently outputs:
```
team sending submission 8010099 is bound to server bm01 submitter: 3346341 user 3337428 ** Another submission from this team is currently running **
team sending submission 8012578 is bound to server bm18 submitter: 3346434 user 3343963
team sending submission 8013157 is bound to server bm17 submitter: 3344230 user 3345322
team sending submission 8014443 is bound to server bm02 submitter: 3347537 user 3347537
team sending submission 8014454 is bound to server bm01 submitter: 3345212 user 3345451
```

(The user who opened the discussion thread is 3343963.)
