### ISSUE TITLE
current lead time

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#468]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1497

**Comment by tschaffter** [comment]
Answered to the participant.

**Comment by tschaffter** [comment]
@brucehoff When participants have been waiting for a long time for a slot to become free on the machine where their pre-processed data are, it would be **really great** if we could give the participants the ability to notify the system that they prefer to get rid of their pre-processed data in exchange of moving as soon as possible to an open slot. Before are suggestions for how we could implement this:

- A unique checkbox or a two-state button somewhere that set the preference between "running submission sooner but recomputing the pre-processed dataset" or "reused the pre-processed dataset but possibly wait longer to start training".

- For the VALIDATED submissions in the Dashboard, add a button that allows participant to set their preference for this specific submission.

On the system side, I don't think that this information can be stored by a single boolean and that no significant modification of the implementation is required. Is that correct?

**Comment by tschaffter** [comment]
I started a parallel discussion on the feasibility of transferring pre-processed data from one machine to another: #486

**Comment by brucehoff** [comment]
I'm not sure moving preprocessed data is a good strategy.   I did a little bit of this in Round 1 (using rsync to migrate preprocessed data between servers) and found that it can take so long that the machine can become free faster than the data moves.  It's simply not possible to know whether it's more or less efficient to switch machines.

Having said that, there are two quick changes that I think will help:

(1) Per my request last night, please review the new user dashboards which show 'time remaining'.  There is one participant who has gone over his quota and is blocking the user who started this thread from running on bm01.  Once we display the time quota then we can enable the quota enforcement and unblock the waiting user.

(2) We can implement #464, allowing submissions the freedom to switch machines when their preprocessing method changes.  This has the dual benefit of (a) allowing submissions to naturally rebalance across servers, (b) give participants an explicit mechanism to detach themselves from their current server (i.e., by changing the repository or digest of their preprocessing method).

**Comment by tschaffter** [comment]
> There is one participant who has gone over his quota and is blocking the user
Has his job been killed?

**Comment by brucehoff** [comment]
> Has his job been killed?

No.  Before I do that I want him to be able to see that he's gone over quota.

To do that I want to update the dashboard to show that information.

Earlier you had asked to review the revised dashboards before they were published.

So if you would please review the revised dashboards I will then publish them, notify the user in question that his job(s) will be killed (giving him a chance to terminate them) and then, finally, turn on the quota enforcement.

**Comment by brucehoff** [comment]
> (2) I thought this was already the case (see my answer here).

No, your response to him is inaccurate.  If we implement #464 then the system will behave as you describe to him.

**Comment by tschaffter** [comment]
> If we implement #464 then the system will behave as you describe to him.
How long before we can have this feature?

**Comment by brucehoff** [comment]
> How long before we can have this feature?

I started working on it some time ago:

https://github.com/Sage-Bionetworks/ChallengeDockerAgent/compare/issue-464?expand=1

It's not a huge code change must needs careful testing because it would be very dangerous to get wrong.  So I don't want to try to do it quickly.

**Comment by tschaffter** [comment]
Thanks! Meanwhile I'll correct my answer on the discussion forum.

**Comment by tschaffter** [comment]
@brucehoff Is that correct that if there is no pre-processing (or pre-processing included in train.sh), the submission will be run on the first machine available?

**Comment by brucehoff** [comment]
Yes!

**Comment by tschaffter** [comment]
@brucehoff But in that case he doesn't have access to the 10 TB to save his pre-processed data...

**Comment by brucehoff** [comment]
Correct!  The way to address this is to store the 10 TB data on network file storage instead of on one server, with the associated bandwidth issues.

**Comment by tschaffter** [comment]
So we cannot recommend him to get rid of preprocess.sh, unless his pre-processed data take less than 200 GB (scratch). This starts to make a lot of conditions so I'm reluctant to suggest this to him.

**Comment by brucehoff** [comment]
Please note, at this time, the submission has been running for nearly 13 hours.  There are no queued submissions from his team. Further, there is plenty of time in the round for him to use the remaining 9 days of his 14 day quota.

**Comment by tschaffter** [comment]
Corrected the information I gave to the participant regarding the pre-processing protocol.

**Comment by tschaffter** [comment]
Thanks to Bruce, the tip previously advertise is now available. I notified the participant of this feature.
