### ISSUE TITLE
Round1 Result/LeaderBoard 

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#475]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1505

**Comment by thomasyu888** [comment]
This is still an issue.  Their submission 7902117 is still marked as INVALID and was not re-run?  Looks like the PREDICTION_FILES annotation wasn't added.  Can you look into this?

**Comment by brucehoff** [comment]
I responded on the forum.
