### ISSUE TITLE
file access error, Express Training queue

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#478]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1508

**Comment by thomasyu888** [comment]
No idea how to respond to this.

**Comment by brucehoff** [comment]
I see that he has successful submissions after the failed one two days ago.  I posted a reply, asking him to confirm that he's moved past this problem.

> No idea how to respond to this.

There a number of ways to respond:
- You can ask him for a small, reproducible example along with source code so you can dig deeper.
- You can reach out (or suggest that he reach out) to other challenge participants, esp. Caffe users.
- You can engage those who created sample Caffe model(s) for the DM challenge.

**Comment by tschaffter** [comment]
Participant found a solution to his issue.
