### ISSUE TITLE
ERROR_ENCOUNTERED_WHILE_SCORING: but no STDERR in the provided logs

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#483]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1517

**Comment by thomasyu888** [comment]
Thanks for responding.

**Comment by tschaffter** [comment]
Bruce has already answered to the participant.

Do we effectively return the entire log file for the submission sent to the predictions Express Lane?

**Comment by brucehoff** [comment]
> Do we effectively return the entire log file for the submission sent to the predictions Express Lane?

Yes.

**Comment by brucehoff** [comment]
I'm labeling this with Server Instability because (1) the Docker error codes imply the user's containers ran out of memory, (2) the user ran the same container on the leaderboard without having the same problem.  On both the leaderboard and express lane we run their containers using the`--memory=""` option, setting it to 200 GB.

**Comment by brucehoff** [comment]
I was wrong about the cause.  The "error" is just that the submission exceeded 20 minutes and was stopped.  Here is the fix:  https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/9ee5b579c67cdd0f440442a434483d43a128fb5e
