### ISSUE TITLE
Transfer pre-processed data from one machine to another?

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#486]
The purpose of this thread is to discuss a possible implementation and limitation of the transfer of pre-processed data from one machine to another in order to harness at best the available computational power.

So far, we decided to not consider the transfer of pre-processing data because they can be as big as 10 TB, which may take approximatively between 1 and 5 days depending on whether the source and target machines are transferring other pre-processed data (up to 5 pre-processed dataset can be transferred at the same time because we have 5 user slots/machine). However, if the pre-processed data are much smaller for a reason or another, it may become interesting to consider implementing a transfer of the pre-processed data. 

Before going any further, it would be great if we could have an idea of what the size of the pre-processed data are. Have the agents been collecting this information?

**Comment by brucehoff** [comment]
> Have the agents been collecting this information?

No.  In principle one could write a script to run on each server to see the size of the data in each slot.

We do collect how *long* it took to create each preprocessing result, here: https://www.synapse.org/#!Synapse:syn7214502/tables/query/eyJsaW1pdCI6MjUsICJzcWwiOiJTRUxFQ1QgdGVhbUlkLCBwcmVwcm9jZXNzRHVyYXRpb24gRlJPTSBzeW43MjE0NTAyIiwgImlzQ29uc2lzdGVudCI6dHJ1ZSwgIm9mZnNldCI6MH0=

**Comment by tschaffter** [comment]
> In principle one could write a script to run on each server to see the size of the data in each slot.

Yes, I'm doing it in my monitori

**Comment by tschaffter** [comment]
> In principle one could write a script to run on each server to see the size of the data in each slot.

Yes, this is part of the monitoring script I'm writing. I hope to have a chance to finalize it in the next few days.

**Comment by tschaffter** [comment]
No longer useful.
