### ISSUE TITLE
Allow retrieving 5GB of logs and model state per 5 days

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#488]

**Comment by tschaffter** [comment]
## Tentative specifications
Participants start the round with 5 GB of data quota. The remaining data quota (30 GB) are credited every dT (e.g. 5-15 minutes)  as time goes. At any time, a participant should not be given access to download more data than his remaining time quota allow him. If he has enough data credit, first the credit is reduced and then the access to the data is given to the team.

## Log files
The amount of log files returned depends on the available data credit. If there are more data than the team can afford, return only the N first lines or characters that the teams can afford.

OR

Logs could be also implemented on an On Demand basis. However, I encourage the fact to systematically return it to them to push them to keep a eye on their submission.

##Model state
Participants have requested that we allow them to retrieve their model On Demand. This will provide them with more flexibility to check the progress of their running jobs without having to wait until its completion. There would be a button in the dashboard to "Buy" the current state of the model (content of `/modelState`).

**Comment by brucehoff** [comment]
In our design each participant gets 2 weeks of server time during a 5 week period.  To use the server time completely it would have to be saturated with submissions from the beginning of the 5 weeks.  In such a case one team might use all their time in the first 2 weeks.  This is an extreme edge used to illustrate the thought that we shouldn't increase the quota gradually over the course of 5 weeks, a few participants might use all their server quota early in the round and wish to download their 35 GB during that time too.

An alternative would be to simply say that each team can retrieve up to 35 GB per 5 weeks and up to 5 GB per day.  They can use their whole quota in the first 7 days or spread it out as they see fit.

**Comment by brucehoff** [comment]
Replacing this issue with https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/644
