### ISSUE TITLE
ERROR_ENCOUNTERED_WHILE_SCORING

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#489]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1522

**Comment by thomasyu888** [comment]
I'm not sure how to answer these.  It says ERROR_ENCOUNTERED_WHILE_SCORING, but I'm not sure if thats due to my scoring harness or due to the scoring inference step from the docker agent.  Did we implement log files for inference submissions?

**Comment by brucehoff** [comment]
> I'm not sure how to answer these. It says ERROR_ENCOUNTERED_WHILE_SCORING, but I'm not sure if thats due to my scoring harness or due to the scoring inference step from the docker agent.

Please ask the participant to paste into the discussion the contents of the email the system sent them.  This should help answer your questions.

> Did we implement log files for inference submissions?
Yes, for the *express lane*.  For the leaderboard we include only the tail of the log file, at the end of the email we send out.

**Comment by thomasyu888** [comment]
I can't see anything wrong with the log file that he uploaded.  Is there a log file size limit for inference log files?

**Comment by brucehoff** [comment]
@thomasyu888 No, there is no log file size limit for inference files.

To see more info go to this page

https://www.synapse.org/#!Synapse:syn5644795/wiki/409861

and look for his submission ID.  Under STATUS_DESCRIPTION it says, ERROR_ENCOUNTERED_WHILE_SCORING which means that his container stopped itself with a non-zero status code.   The page shows that the container ran on bm04, so you can connect to the docker daemon on that machine, find the container and inspect it:
```
ubuntu@ip-172-31-59-223:~$ docker inspect archive.8041422.bm04-1.SCORE_SC_1.SCORING
[
    {
        "Id": "90d769cbd5caef708bd0937e0209440f4902c920cc323c3840dfc1bd4e1d3031",
        "Created": "2017-01-19T00:06:31.083771672Z",
        "Path": "/sc1_infer.sh",
        "Args": [],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 137,
            "Error": "",
            "StartedAt": "2017-01-19T00:06:31.390542934Z",
            "FinishedAt": "2017-01-19T00:32:10.891324016Z"
        },
...
```
The exit code is 137 which is an out-of-memory issue, accoding to this blog: https://bobcares.com/blog/error-137-docker/

**Comment by thomasyu888** [comment]
The error message that participants get when this error occurs is not informative.  Is there a way to tell participants that it is an out-of-memory issue in the email sent back?

**Comment by brucehoff** [comment]
> Is there a way to tell participants that it is an out-of-memory issue in the email sent back?

We can return the container error code:

https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/504

**Comment by brucehoff** [comment]
I responded on the forum.
