### ISSUE TITLE
Submission EXCEEDED TIME QUOTA

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#490]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1523

**Comment by tschaffter** [comment]
@thomasyu888 Can you please remind the participant what the time quota apply to.
@brucehoff Can you answer him regarding his time quota usage?
Thanks!

**Comment by brucehoff** [comment]
I responded on the forum.

**Comment by tschaffter** [comment]
Thanks a lot Bruce!

**Comment by thomasyu888** [comment]
The participant did state that he used up a lot of the quota trying the tensor flow example which actually had a few bugs in it.  Should we allow him to have more quota time?

**Comment by tschaffter** [comment]
@thomasyu888 No. It's his duty to check the log file and stop the container when he thinks that there is a problem. You can remind him that the examples on the GitHub repository [dm-docker](https://github.com/tschaffter/dm-docker) are provided without any guarantee.

**Comment by brucehoff** [comment]
@tschaffter and @thomasyu888 :  We should probably stay firm on the quota but when speaking to him but please keep in mind that we only started *displaying* the quota-remaining information after he had exceeded his.  So he had no indication that he was rapidly consuming his quota.  (We had to start enforcing the quota because others were waiting for the machine he was dominating.)
