### ISSUE TITLE
 No space left on device: 

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#491]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1524

**Comment by tschaffter** [comment]
Which machine?

**Comment by brucehoff** [comment]
@tschaffter To find out the machine, first ask for the submission ID and whether it's on the leaderboard or express lane then look up the submission, for the leaderboard here:
https://www.synapse.org/#!Synapse:syn5644795/wiki/409766
or for the express lane here:
https://www.synapse.org/#!Synapse:syn5644795/wiki/409766

Each table shows the agent ID, "bmXX-X" where "bmXX" is the server on which the submission ran.

**Comment by tschaffter** [comment]
Participant was trying to write to `/preprocessedData` during inference.
