### ISSUE TITLE
Maintenance between Round 2 and 3

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#492]
## SoftLayer
- Update firmewares (BIOS, harddrive, etc.)
- `yum update`in accordance with instructions from DST
- Clean docker data space
- Remove old agent temp directories in `/root/`
- `crontab -e`
- reboot

### All machines
- Resize `/data/scratchX` for every agent to 200 GB
   - `lvresize --resizefs --size 200GB /dev/mapper/data-scratch0`
   - `lvresize --resizefs --size 200GB /dev/mapper/data-scratch1`
- Resize `/data/modelX` for every agent to 20 GB
   - `lvresize --resizefs --size 20GB /dev/mapper/data-model0`
   - `lvresize --resizefs --size 20GB /dev/mapper/data-model1`
- Create 50 GB `/data/tempDirX` for every agents
- Do not mount extra model partitions
   - `lvremove /dev/mapper/data-model2`
   - `lvremove /dev/mapper/data-model3`
   - `lvremove /dev/mapper/data-model4`

### Challenge Training machines
Typical partition structure:

```
[root@bm02 ~]# df -h
Filesystem                   Size  Used Avail Use% Mounted on
/dev/sda3                     99G  7.1G   92G   8% /
devtmpfs                     252G     0  252G   0% /dev
tmpfs                        252G     0  252G   0% /dev/shm
tmpfs                        252G   82M  252G   1% /run
tmpfs                        252G     0  252G   0% /sys/fs/cgroup
/dev/sda1                    248M  231M   18M  94% /boot
/dev/mapper/data-dataset0     10T  2.2T  7.3T  24% /data/dataset0
/dev/mapper/data-dataset1     10T  228G  9.2T   3% /data/dataset1
/dev/mapper/data-dataset4     10T  3.0G  9.5T   1% /data/dataset4
/dev/mapper/data-dataset3     10T  3.7G  9.5T   1% /data/dataset3
/dev/mapper/data-dataset2     10T  653M  9.5T   1% /data/dataset2
/dev/mapper/data-model1       20G  5.4M   19G   1% /data/model1
/dev/mapper/data-model0       20G  5.4M   19G   1% /data/model0
/dev/mapper/data-data        8.0T  6.6T 1023G  87% /data/data
/dev/mapper/data-scratch1    493G   70M  470G   1% /data/scratch1
/dev/mapper/data-tempDir1     50G   53M   47G   1% /data/tempDir1
/dev/mapper/data-tempDir0     50G   53M   47G   1% /data/tempDir0
/dev/mapper/data-scratch0    493G   70M  470G   1% /data/scratch0
tmpfs                         51G     0   51G   0% /run/user/0
```

### Challenge Inference machines

- Create 50 MB `/data/inferenceX` for every agents

### Machines Ready
- [x] bm01
- [x] bm02
- [x] bm03
- [x] bm04
- [x] bm05 (admin machine; firmware updated)
- [x] bm06 (firmware updated; OS Reload > Validation training)
- [x] bm07
- [x] bm08
- [x] bm09 (debug machine; firmware updated)
- [x] bm10
- [x] bm11
- [x] bm12 (firmware updated and `yum update`)
- [x] bm13
- [x] bm14
- [x] bm15
- [x] bm16 (firmware updated; OS Reload > Leaderboard training)
- [x] bm17
- [x] bm18
- [x] bm19
- [x] bm20
- [x] bm21
- [x] bm22
- [x] bm23

## General
- [ ] Ask the DST if there are packages that must be updated.
- [ ] Update Docker examples (publish only once the round has ended in order to avoid interference)
   - [ ] Framework images
   - [ ] Pre-processing and training images (test)
      - [ ] Fix Darvin's broken Tensorflow example
- [ ] Deploy custom monitoring tool
- [ ] Prepare newsletter
   - [ ] Decide on final baseline scores to use
   - [ ] Keep a record of the baseline method(s)
   - [ ] Rules to be invited to the Collaborative Phase and rules to be eligible for the Cash prize in SC1 and SC2
   - [ ] Prepare check list for valid final submissions (#565)
   - [ ] New inference cancel button (remind them to check carefully their submissions before sending them)
   - [ ] Precise amount of computation time (do we use 5 or less user slots?)
   - [ ] Docker container smaller than 10 GB
- [ ] Update the documentation (including Cheat Sheet)
- [ ] Implement time limit strategy for submission (#616)
- [x] Allow participant to see progress of their inference method
- [x] Review number of training and inference machines

**Comment by tschaffter** [comment]
@brucehoff Just to confirm, have bm03 and bm13 been set to no longer accept new inference jobs (these machines still need to be updated)?

**Comment by brucehoff** [comment]
yes

**Comment by tschaffter** [comment]
All the machines have been updated. Getting now ready for the last maintenance that will start in a week.
