### ISSUE TITLE
computational quota

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#495]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1531

**Comment by brucehoff** [comment]
@thomasyu888 Can you look into this?  Can you verify that the quota computation is correct?

**Comment by thomasyu888** [comment]
Was this resolved?  I see that you tweaked with the code.  Can you give me the command you use to execute the script so I can look further into this issue?

**Comment by brucehoff** [comment]
> Was this resolved?

I would like to see OP agree with the analysis before we consider the issue resolved.

> Can you give me the command you use to execute the script 

The command is shown here:
https://github.com/Sage-Bionetworks/DM-Challenge-Quota-Application/blob/master/README.md

**There is a related issue for you to look at:**  When you made this commit:  
https://github.com/Sage-Bionetworks/DM-Challenge-Quota-Application/commit/c2a3d8c690a63b0aeaf19e19bc3260804e71e489

you introduced a visible bug:  The variable 'training_update_ms' is only meaningful from lines 116 to 124 but you use it after the 'for subIds' loop on line 134.

**Comment by thomasyu888** [comment]
Apologies for that bug.... I really can't think of the logic of why I added that initially, so I think it is fine that you commented those lines out.  People can't submit to the queue after the round ends anyhow, so theres no reason to have that logic embedded.
