### ISSUE TITLE
Why my job is killed?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#501]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1537

**Comment by tschaffter** [comment]
@thomasyu888 Ask him for the regular additional information (submission ID, error log, etc.).

**Comment by thomasyu888** [comment]
It seems that his training script was killed but his training completed?  The status of his submission Id is ACCEPTED.  This is the line of error in the log file:

```
STDERR: /train.sh: line 57:    17 Killed                  python run_cnn_k_mil_new.py
```

**Comment by brucehoff** [comment]
@thomasyu888  I responded on the forum.
