### ISSUE TITLE
bm17 cannot start new containers

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#503]
```
docker rm 8043026.bm17-1.directory-cleaner
Error response from daemon: Unable to remove filesystem for f9b09d7a1d85a876249cf76250f8550dcc15d7d0903e4063bff5cca5255fe87c: remove /var/lib/docker/containers/f9b09d7a1d85a876249cf76250f8550dcc15d7d0903e4063bff5cca5255fe87c/shm: device or resource busy
```

**Comment by tschaffter** [comment]
@brucehoff Can you please specify the ID of the teams in https://docs.google.com/spreadsheets/d/16smwWa9UvueyuJbda98poNAe9DbVySC04uRq4s6Ghgg/edit#gid=0 that were running a container at the time of the crash?

**Comment by brucehoff** [comment]
User https://www.synapse.org/#!Profile:3345509 has requested job 8057962 to stop, but Docker can't stop the job.

**Comment by tschaffter** [comment]
```
[root@bm17 ~]# docker stop 8057962
Error response from daemon: No such container: 8057962
```

**Comment by brucehoff** [comment]
This issue should be our top priority.   There is one user trying to cancel his current job on bm17 and get his model state back.  Of the three currently queued jobs, two are waiting to access preprocessed data on bm17:
```
team sending submission 8053740 is bound to server bm14 submitter: 3343937 user 3345381 preprocessing is same 
team sending submission 8058465 is bound to server bm17 submitter: 1973395 user 1973395 preprocessing is same 
team sending submission 8058745 is bound to server bm17 submitter: 3344230 user 3344012 preprocessing is same 
```

**Comment by tschaffter** [comment]
Restarted the machine.

**Comment by brucehoff** [comment]
I restarted the agents.

**Comment by tschaffter** [comment]
Because the machines have been very stable during Round 3, I'm closing all the tickets related to reboot that are more than one month old. If a new issue is raising an a machine, we can easily look at its history of issues on GitHub.
