### ISSUE TITLE
Preprocess chaining

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#507]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1541

**Comment by tschaffter** [comment]
We already had this question about allowing subsequent pre-processing of the pre-processing data. This has not been a top priority so far but it is still interesting to consider it once again. Assume that we allow participants to specify a list of pre-processing containers to run sequentially named for simplicity A, B and C.

An important constraint is that the submission file should uniquely describe a submission.

When submitting this submission file, the system handles the following cases:

- No pre-processing data exists: the system run, A, B, and C
- Pre-processed data are A: the system run B and C
- Pre-processed data are C: nothing to pre-process

Participant now submits a submission file that include C and D for pre-processing while the cached version is C. 


- If the system remembers that the sequence that led to the cached C is {A,B,C} (which currently we don't want it to remember): the system should process the data from scratch by applying C and D.

- If the system does not remember that the cached C is the product of {A,B,C}, the system would likely just process D but then the submission file no longer reflect the pre-processed data on the system.

The above examples show that its not possible to have a submission file that describes entirely a submission and allow participants to further process their pre-processed data.

Any thoughts?

**Comment by tschaffter** [comment]
A solution may be to keep track of an additional digest.

1. Participant submits {A,B,C}. The cached data are C and the system saves a digest that includes the information A>B>C
2. Participant submits only C. The system compares the current additional digest that include the information "A>B>C" with the additional digest computed from the current submission file ("C"). Because they do not match, the system starts the pre-processing from scratch and run only C, which is what the participant wants.

@brucehoff What do you think?

**Comment by brucehoff** [comment]
> @brucehoff What do you think?

A simple way to support the participant would be to give him larger scratch space, to hold the output of 'B'. (We'd have to give him ~10TB rather than the current 1/2 TB.)  There would be no caching for future submissions but he could execute the sequence that he would like.

I don't think there is time left in the challenge to do a substantial redesign of the submission processing pipeline.  (Our priority should be to stabilize the existing system.)

To support more complex workflows (e.g., in future challenges) we should consider existing workflow engines, of which there are many (Galaxy, SevenBridges, Arvados, Toil, ...) rather than 'rolling our own.'  When evaluating those engines we should examine how they cache intermediate results.

**Comment by brucehoff** [comment]
I responded on the forum.

**Comment by tschaffter** [comment]
Thanks!
