### ISSUE TITLE
Six Softlayer machines rebooted in past two days

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#530]
I'm omitting bm17, which we intentionally rebooted.
Three machines have rebooted in the last day and three more within the last two days.

bm02 < 1 day
bm14 < 1 day -- See https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/528
bm15  2 days
bm16  2 days
bm19  2 days
bm22 5 hours -- See https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/529

```
[~]  ssh bm01 uptime
 13:25:14 up 29 days, 23:14,  0 users,  load average: 3.11, 2.63, 2.47
[~]  ssh bm02 uptime
 13:25:24 up 23:49,  0 users,  load average: 47.39, 47.29, 41.10
[~]  ssh bm03 uptime
 13:25:30 up 29 days, 21:48,  0 users,  load average: 146.25, 144.55, 140.33
[~]  ssh bm04 uptime
 13:25:35 up 31 days, 21:02,  0 users,  load average: 0.01, 0.02, 0.05
[~]  ssh bm06 uptime
 13:25:41 up 19 days, 17 min,  0 users,  load average: 2.03, 2.04, 2.11
[~]  ssh bm07 uptime
 13:25:46 up 27 days, 14:36,  0 users,  load average: 2.00, 2.01, 2.05
[~]  ssh bm08 uptime
 13:25:57 up 5 days, 18:27,  0 users,  load average: 0.00, 0.71, 2.89
[~]  ssh bm09 uptime
 13:26:01 up 5 days, 43 min,  0 users,  load average: 0.00, 0.01, 0.06
[~]  ssh bm10 uptime
 13:26:06 up 27 days, 14:44,  0 users,  load average: 26.49, 28.53, 28.36
[~]  ssh bm14 uptime
 13:26:15 up 15:38,  0 users,  load average: 24.20, 24.15, 24.19
[~]  ssh bm15 uptime
 13:26:24 up 2 days, 21:46,  0 users,  load average: 2.01, 2.04, 2.05
[~]  ssh bm16 uptime
 13:26:29 up 2 days, 21:49,  0 users,  load average: 1.35, 1.68, 1.66
[~]  ssh bm18 uptime
 13:26:32 up 31 days, 20:13,  0 users,  load average: 19.95, 20.36, 19.39
[~]  ssh bm19 uptime
 13:26:47 up 2 days, 14:35,  0 users,  load average: 48.50, 49.62, 48.40
[~]  ssh bm20 uptime
 13:26:52 up 9 days, 18:03,  0 users,  load average: 2.03, 2.01, 1.97
[~]  ssh bm21 uptime
 13:27:23 up 5 days, 14:55,  0 users,  load average: 2.41, 2.29, 2.25
[~]  ssh bm22 uptime
 13:27:26 up  4:57,  1 user,  load average: 1.11, 1.11, 5.49
[~]  ssh bm23 uptime
 13:27:31 up 18 days,  4:49,  0 users,  load average: 87.81, 86.06, 87.16
[~]  
```

**Comment by brucehoff** [comment]
@tschaffter  Do you have any thoughts on investigating why these machines have recently rebooted?

**Comment by tschaffter** [comment]
bm02: ?
bm14: SL interface says that a Hard Reboot occurred 24 hours ago.
bm15: SL interface says that a Hard Reboot occurred 3 days ago.
bm16: SL interface says that a Hard Reboot occurred 3 days ago.
bm19: ?
bm22: ?

I don't remember whether I rebooted these machines. If you didn't ask them to be rebooted, then I don't think that I did it.

**Comment by brucehoff** [comment]
@tschaffter Let's pick bm14 which was "hard reboot"ed at 7:48PM central time / 8:48 eastern on Saturday (1/28).  I did not ask you to reboot it and if you don't remember then, since it was so recent, you probably did not reboot it. Can you look into why it was Hard Rebooted?  E.g. does the console say anything and/or can you ask Softlayer for any records of what they might have done?  What are the mechanisms by which a Hard Reboot can occur?  Is there an automated process that can be triggered by the system state (high CPU / low memory), or is it always a manual action?

**Comment by brucehoff** [comment]
According to this:
https://www.ibm.com/blogs/cloud-computing/2015/01/guide-monitoring-ibm-softlayer-environment/
Softlayer provides 'Automatic server reboot when system failure is detected'.  Is there a way to tell if a system failure preceded the hard reboot on bm14?

**Comment by tschaffter** [comment]
Actually I think that we had a couple of machines that bumped into the issue where `systemctl` was not responding (i.e. when you cannot remove containers). In that case the only solution is to reboot the machine, which I may have done without you asking specifically for it.

**Comment by brucehoff** [comment]
@tschaffter Can we agree to log any reboots (hard or otherwise) in Github issues and/or the tracking spreadsheet?

**Comment by tschaffter** [comment]
@brucehoff Yes. A nice solution will be to track the output of the `reboot` command in ELK (the monitoring framework that I'm testing when I have free time).

**Comment by tschaffter** [comment]
> According to this:
https://www.ibm.com/blogs/cloud-computing/2015/01/guide-monitoring-ibm-softlayer-environment/
Softlayer provides 'Automatic server reboot when system failure is detected'. Is there a way to tell if a system failure preceded the hard reboot on bm14?

The SoftLayer interface doesn't show the "owner" of a reboot.

**Comment by tschaffter** [comment]
Because the machines have been very stable during Round 3, I'm closing all the tickets related to reboot that are more than one month old. If a new issue is raising an a machine, we can easily look at its history of issues on GitHub.
