### ISSUE TITLE
bm01 cannot start or stop containers

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#532]
```
docker rm -f 8078749.bm01-1.directory-cleaner
Error response from daemon: Unable to remove filesystem for a285d1e1c0c8617cd2d2dbac980f5b705439e36ce5b8716e19ffd5ace0b15d5d: remove /var/lib/docker/containers/a285d1e1c0c8617cd2d2dbac980f5b705439e36ce5b8716e19ffd5ace0b15d5d/shm: device or resource busy
```

**Comment by brucehoff** [comment]
Some investigation:  As per our summary spreadsheet, team 1973395 seems to have 'crashed' multiple servers. 
https://docs.google.com/spreadsheets/d/16smwWa9UvueyuJbda98poNAe9DbVySC04uRq4s6Ghgg/edit#gid=0
In this case their submission is 8078749.  Note that it finished *successfully*.  Here is the tail of the logs:
```
ubuntu@ip-172-31-59-223:~$ docker logs archive.8078749.bm01-1.TRAIN.TRAINING --tail 20
440s - loss: 0.5947 - acc: 0.7043 - val_loss: 0.5767 - val_acc: 0.7414
Epoch 12/20
439s - loss: 0.5984 - acc: 0.6964 - val_loss: 0.5405 - val_acc: 0.7697
Epoch 13/20
440s - loss: 0.5950 - acc: 0.6979 - val_loss: 0.5773 - val_acc: 0.7390
Epoch 14/20
438s - loss: 0.5869 - acc: 0.7058 - val_loss: 0.5573 - val_acc: 0.7555
Epoch 15/20
434s - loss: 0.5973 - acc: 0.7153 - val_loss: 0.5644 - val_acc: 0.7492
Epoch 16/20
429s - loss: 0.5878 - acc: 0.7216 - val_loss: 0.5682 - val_acc: 0.7453
Epoch 17/20
429s - loss: 0.5739 - acc: 0.7311 - val_loss: 0.5594 - val_acc: 0.7524
Epoch 18/20
433s - loss: 0.5826 - acc: 0.7240 - val_loss: 0.5597 - val_acc: 0.7516
Epoch 19/20
429s - loss: 0.5781 - acc: 0.7232 - val_loss: 0.5641 - val_acc: 0.7484
Epoch 20/20
420s - loss: 0.5827 - acc: 0.7311 - val_loss: 0.5648 - val_acc: 0.7492
2017-01-30 02:49		done training, dumping to disk!
```
It's worth looking at the output, especially to the 'model state' folder, but also 'scratch'.

**Comment by brucehoff** [comment]
Another idea worth investigating is that the problem occurs *between* the successful completion of the training job and the start of the directory cleaner.  E.g. when the model is zipped and uploaded.

**Comment by brucehoff** [comment]
8078749 was last updated (with 'ACCEPTED' status) on 01/29/2017 06:55:02PM Pacific Time.
So it got through line 615 of Training.java w/o error:
```
		ContainerCompletionStatus status = updateJob(job, SubmissionPhase.TRAINING, trainingImageName, TRAINING_LOGS_SUFFIX);

```

The code bet. lines 615 and 655 is the code to upload model state.

**Comment by brucehoff** [comment]
I have a hypothesis about the root cause:  The folder `/data/model0` is mounted as `/modelState` on the agent.  When the agents seeks to zip content for upload to Synapse it creates the .zip file *in the parent folder of the folder to be zipped*.  In this case, since the folder to be zipped is `/modelState`, the parent folder is `/`, which is *inside the container itself.*  So we are copying about 1GB of files into the container as part of creating the zip.  

To investigate the problem we should look at model state sizes from various models.  If models causing our Docker problems have large model state file sizes then we have support for this hypothesis.

One way to fix the problem is to have the model write its state not into `/data/model0` but rather into `/data/model0/UUID` (`/modelState/UUID` in the agent) after which the agent can zip into `/data/model0/foo.zip` (`/modelState/foo.zip` in the agent).

**Comment by tschaffter** [comment]
> I have a hypothesis about the root cause: The folder /data/model0 is mounted as /modelState on the agent. When the agents seeks to zip content for upload to Synapse it creates the .zip file in the parent folder of the folder to be zipped. In this case, since the folder to be zipped is /modelState, the parent folder is /, which is inside the container itself. So we are copying about 1GB of files into the container as part of creating the zip.

@brucehoff I don't see what the problem is. Where you expecting to save the zip file outside of the agent container? Yet, how do you explain that all the containers stop?

The only problem that I can see related to that is that the agent container will crash if the container reaches about 10 GB. This may be a problem for sure if we allow participants to retrieve larger models during during later on. However even in that case, only the agent container would stop, not all the containers.

**Comment by brucehoff** [comment]
Update:  Though the results are not conclusive, there indeed seem to be some large model states for teams that encountered problems:
https://docs.google.com/spreadsheets/d/16smwWa9UvueyuJbda98poNAe9DbVySC04uRq4s6Ghgg/edit#gid=1748110002

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/6e09af126929fb1803d676cb5759bb8e091e774f

**Comment by brucehoff** [comment]
> Where you expecting to save the zip file outside of the agent container?

Yes.

> Yet, how do you explain that all the containers stop?

I can't.  It may be wishful thinking that this is the cause of the problem.  

>  However even in that case, only the agent container would stop, not all the containers.

Yes, that may well be true.  In any case I have deployed the code change and if the instability goes away it will suggest this was indeed the problem.

**Comment by brucehoff** [comment]
Note:  I rebooted bm01 since I cannot get any containers to start.

**Comment by tschaffter** [comment]
Before and after the patch, were you able to reproduce one of the issues by running one of the suspicious containers?

**Comment by brucehoff** [comment]
> Before and after the patch, were you able to reproduce one of the issues by running one of the suspicious containers?

No.   I tried several submissions but did not find a way to reproduce the problem.  8064768 was running on bm02 but the submitter canceled it.

**Comment by brucehoff** [comment]
For now the machine is running.  Will revisit if/when the problem recurs.
