### ISSUE TITLE
Log file of running job has not changed in the last 22 hours

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#547]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1627

**Comment by thomasyu888** [comment]
I tried to figure out what the issue was, but I'm unsure how to reply now.

**Comment by brucehoff** [comment]
I responded on the forum.  Looking at later submissions I *think* the participant figured out his problem himself.
