### ISSUE TITLE
**URGENT, PLEASE READ: **8115015 costed 12 hours with little log update for a very very long time

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#553]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1637

**Comment by thomasyu888** [comment]
Is there an issue with speed of processing right now?

**Comment by tschaffter** [comment]
We should check first if there was an issue detected on the machine she is using.

**Comment by brucehoff** [comment]
The machine is bm14.  We saw no problem running submissions.  There was no reboot and I see no problem with disk usage (see below).  She is not the first to say that the servers suddenly became very slow.  
```
ubuntu@ip-172-31-59-223:~/DigitalMammographyChallenge$ ssh bm14 uptime
 13:42:07 up 4 days, 15:54,  0 users,  load average: 4.39, 3.94, 4.66
ubuntu@ip-172-31-59-223:~/DigitalMammographyChallenge$ ssh bm14 df -h
Filesystem                 Size  Used Avail Use% Mounted on
/dev/sda3                  893G   35G  858G   4% /
devtmpfs                   252G     0  252G   0% /dev
tmpfs                      252G     0  252G   0% /dev/shm
tmpfs                      252G  322M  252G   1% /run
tmpfs                      252G     0  252G   0% /sys/fs/cgroup
/dev/sda1                  248M  217M   32M  88% /boot
/dev/mapper/data-model0    976M   49M  861M   6% /data/model0
/dev/mapper/data-scratch1  197G  497M  187G   1% /data/scratch1
/dev/mapper/data-scratch0  197G   61M  187G   1% /data/scratch0
/dev/mapper/data-model2    976M  2.6M  907M   1% /data/model2
/dev/mapper/data-model4    976M  2.6M  907M   1% /data/model4
/dev/mapper/data-model1    976M  2.5M  907M   1% /data/model1
/dev/mapper/data-data      8.0T  6.6T  1.1T  87% /data/data
/dev/mapper/data-model3    976M  2.6M  907M   1% /data/model3
/dev/mapper/data-dataset0   10T  380G  9.1T   4% /data/dataset0
/dev/mapper/data-dataset3   10T   63G  9.4T   1% /data/dataset3
/dev/mapper/data-dataset1   10T  764G  8.7T   8% /data/dataset1
/dev/mapper/data-dataset4   10T   44G  9.4T   1% /data/dataset4
/dev/mapper/data-dataset2   10T  362G  9.1T   4% /data/dataset2
tmpfs                       51G     0   51G   0% /run/user/1000
```

Snippet from 'top' on bm14:
```
15387 root      20   0  0.540t 0.011t 169928 R 163.5  2.1 355:29.16 python                                                                                                    
22255 root      20   0 12.339g 9.373g   2980 D  39.2  1.9  18:50.85 python                                                                                                    
22257 root      20   0 12.340g 9.374g   2976 R  29.9  1.9  18:56.03 python                                                                                                    
22253 root      20   0 12.339g 9.373g   2976 D  23.3  1.9  20:09.48 python                                                                                                    
22247 root      20   0 12.350g 9.378g   2976 D  20.6  1.9  18:55.14 python                                                                                                    
22260 root      20   0 12.339g 9.372g   2976 D  18.6  1.9  17:22.76 python                                                                                                    
22258 root      20   0 12.339g 9.372g   2976 D  17.3  1.9  18:31.65 python 
```

**Comment by thomasyu888** [comment]
So there is no issue with speed?  Its just her code that is taking a long time to run?

**Comment by tschaffter** [comment]
@thomasyu888 @brucehoff First try to resubmit her submission has it is to see if the problem is reproducible. If not, there is not much we can do.

**Comment by brucehoff** [comment]
> So there is no issue with speed?

I'm not saying that.  I'm just saying that there's no problem that we know about.  The open question is: How do you check that a system is not "running slowly".

> First try to resubmit her submission has it is to see if the problem is reproducible

We would have to run it on multiple machines and compare them.  I.e. we need a baseline/benchmark.  It's a non-trivial effort to investigate.  Would be appreciative if one of you had the time to do a deep dive.

**Comment by tschaffter** [comment]
@brucehoff If the log file was containing inserted regularly, we would only need to run the submission on a test machine and compare the rate at which it process the data.

As previously discussed, you don't want to insert the time stamp in the prefix of every lines in the log file. I think that the concern was mainly aesthetic. It's also more data to count towards the team's data quota but I thing that this is negligible once compressed.

It would however be great to insert runtime information inside the script (e.g. one line inserted inside the logs each time the logs are being sent to Synapse). E.g. current time on the server plus optionally the time since the job started. What do you think about that?

**Comment by thomasyu888** [comment]
I am happy to re-submit her submissions but should I submit it to the dry run queues to test her submission?

**Comment by brucehoff** [comment]
I have updated the challenge agent to add time stamps to every line of log files.  https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/877d82127a36e3e92dd9276f33f38a165f7e5f85

**Comment by brucehoff** [comment]
> I am happy to re-submit her submissions but should I submit it to the dry run queues to test her submission?

The 'dry run queues' have been reclaimed by @tschaffter to help with the challenge.  We do have some resources set aside for investigating issues.  Please coordinate with him for any investigations.

**Comment by thomasyu888** [comment]
She says this issue has been fixed.
