### ISSUE TITLE
Can you please cancel submission 8118422 to SC1?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#554]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1638

**Comment by thomasyu888** [comment]
Please help me cancel this submission

**Comment by tschaffter** [comment]
@thomasyu888 I usually can't help with this type of issue, which is more related to Synapse submissions.

**Comment by brucehoff** [comment]
@thomasyu888  You can do it, just change the status from OPEN (validated but not yet run) to INVALID.

**Comment by thomasyu888** [comment]
Great. Thanks!
