### ISSUE TITLE
Reconfigure SL Express Lanes machines as Challenge machines

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#556]
- [x] bm04: training
- [x] bm08: training
- [x] bm09: training

**Comment by tschaffter** [comment]
@brucehoff bm08 is ready to be added to the Challenge Lane as a training machine (setupNewServer.sh has already been run).

**Comment by brucehoff** [comment]
bm08 is now up and running training submissions

**Comment by tschaffter** [comment]
@brucehoff bm09 is ready as a training machine for **debugging troublesome submissions** (setupNewServer.sh has already been run).
