### ISSUE TITLE
Model State exceeded 1GB per day quota: can I access it the next day

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#574]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1648

**Comment by tschaffter** [comment]
Related to On Demand access to trained models (#488)

**Comment by tschaffter** [comment]
@brucehoff Can you answer the OP?

**Comment by brucehoff** [comment]
I responded on the forum.
