### ISSUE TITLE
Submission on hold for two days - can you please check

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#583]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1657

**Comment by tschaffter** [comment]
@thomasyu888 Can you check the two submissions of the OP? If they are validated and not yet running, just tell him the usual explanation about the queue + that the servers are extremely busy in the last few days of the round.

**Comment by thomasyu888** [comment]
Answered
