### ISSUE TITLE
At what time does Round 2 close on Feb. 7?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#589]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1662

**Comment by tschaffter** [comment]
@brucehoff The time that you gave me for the start of Round 3 is "2017-02-13 00:00" (GMT or Pacific Time?). Shouldn't it be "2017-02-14 00:00" according to the Challenge timeline?

https://www.synapse.org/#!Synapse:syn4224222/wiki/401751

**Comment by tschaffter** [comment]
For me 0 hours refers to the beginning of a day. Is it the opposite in the US?

**Comment by tschaffter** [comment]
@brucehoff The above timestamp is actually not the end of Round 2. Can you give it to me? Thanks!

**Comment by thomasyu888** [comment]
End of round 2 is Feb 7: 23:59:59 (PST)

**Comment by brucehoff** [comment]
@thomasyu888 Please do the following:
(1) Ensure that the precise times are listed for all such event on the challenge wiki: https://www.synapse.org/#!Synapse:syn4224222/wiki/401751
(2) Let me know when that's done and I will ensure that the cut-offs on the evaluation queues are set accordingly.

**Comment by thomasyu888** [comment]
Does this suffice: https://www.synapse.org/#!Synapse:syn4224222/wiki/401751?

**Comment by brucehoff** [comment]
Yes, thank you.  Just to double check:  We are saying that Round 2 ends at the *end* of 2/7 which is actually 8AM UTC on 2/8.  Round 3 will start 6 days later at the *beginning* of 2/14.  So the rounds are actually 36 days long and the 'hiatus weeks' 6 days, yes?  I think this is fine.  We are basically taking the strategy of giving people a little extra time during each round..  It's inconsequential to the challenge but has the benefit of reducing complaints on the forum.

**Comment by brucehoff** [comment]
Here's my double-check of the start and end dates.  Note that I actually started Round Two 8 hours early, midnight UTC on Jan. 3, making the round 36 days, 8 hours (36.333 days):
```
> showRoundStartAndEnd<-function(evalId) {
+ eval<-synGetEvaluation(evalId)
+ cat("Start date-time: ", eval@quota@firstRoundStart, "\n")
+ cat("End date-time: ", format(strptime(eval@quota@firstRoundStart, format="%Y-%m-%dT%H:%M:%OSZ", tz="UTC")+(eval@quota@roundDurationMillis/1000), "%Y-%m-%dT%H:%M:%OSZ", tz="UTC"), "\n")
+ cat("Round duration: ", eval@quota@roundDurationMillis/1000/3600/24, " days\n")
+ }
> showRoundStartAndEnd("7213944")
Start date-time:  2017-01-03T00:00:00.000Z 
End date-time:  2017-02-08T08:00:00Z 
Round duration:  36.33333  days
> showRoundStartAndEnd("7453778")
Start date-time:  2017-01-03T00:00:00.000Z 
End date-time:  2017-02-08T08:00:00Z 
Round duration:  36.33333  days
> showRoundStartAndEnd("7453793")
Start date-time:  2017-01-03T00:00:00.000Z 
End date-time:  2017-02-08T08:00:00Z 
Round duration:  36.33333  days
> 
```

**Comment by thomasyu888** [comment]
> Yes, thank you. Just to double check: We are saying that Round 2 ends at the end of 2/7 which is actually 8AM UTC on 2/8. Round 3 will start 6 days later at the beginning of 2/14. So the rounds are actually 36 days long and the 'hiatus weeks' 6 days, yes? I think this is fine. We are basically taking the strategy of giving people a little extra time during each round. It's inconsequential to the challenge but has the benefit of reducing complaints on the forum.

Yes, that is correct.
