### ISSUE TITLE
Cancel scoring submission

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#592]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1665

**Comment by tschaffter** [comment]
@brucehoff There has been a large amount of request for cancelling jobs recently. Is it because they cannot cancel jobs that have not started running? They should be able to cancel any jobs by themselves without the need to contact us.

**Comment by brucehoff** [comment]
> Is it because they cannot cancel jobs that have not started running? 

I don't think so.  I think they want to cancel *inference* submissions. We did not provide a cancel button because there is no time quota, but it seems a cancel button is needed.  We have an open issue to provide it:  https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/559
