### ISSUE TITLE
sc1 express lane has been 'RECEIVED' for a long time, can you check what happened?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#593]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1666

**Comment by tschaffter** [comment]
p28x01 seems running fine.
p28x02 has been recently removed from the express lane to become an inference machine.
p28x03 has a problem of docker image cleanup (#594)

**Comment by thomasyu888** [comment]
Are there only 3 machines running express lanes?

**Comment by tschaffter** [comment]
Currently only one (p28x01).
