### ISSUE TITLE
Submission was killed 

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#602]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1673

**Comment by thomasyu888** [comment]
Is this a memory issue?

**Comment by tschaffter** [comment]
> Is this a memory issue?

What makes you think that it's a memory issue?

**Comment by thomasyu888** [comment]
The status of that submission is ACCEPTED even though the script exited out.  Shouldn't it be invalid if it was something wrong with the script?

**Comment by brucehoff** [comment]
> Shouldn't it be invalid if it was something wrong with the script?

If the model failed the status should be CLOSED.

@thomasyu888 Would you please look at his log file and verify that you see in the log file the same line that he reported in the discussion thread.

**Comment by thomasyu888** [comment]
Already did :) The log file does indeed have that line:

```
STDOUT: Non-trainable params: 0
STDERR: /train.sh: line 30:    17 Killed                  python run_cnn_k_mil_new.py
STDOUT: ______________________________________________________after preprocess
STDOUT: this script is train.sh
```

**Comment by brucehoff** [comment]
I'm not sure what other action to take.  I responded on the forum.
