### ISSUE TITLE
stop agents and clean up images

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#603]
We found that the extra tagging step prevents the automatic clean up script from working right.  Need to stop the leaderboard machines (training and scoring), clean up the unused containers and images, then restart the agents. We do NOT need to do this in the express lane, which is already cleaned up.

**Comment by tschaffter** [comment]
It seems that the update of the agents fixes the issue and that the cleanup script works fine.

**Comment by brucehoff** [comment]
Best news I've heard all day!!

**Comment by brucehoff** [comment]
Per Thomas, this is done.
