### ISSUE TITLE
More capacity?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#611]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1680

**Comment by tschaffter** [comment]
@thomasyu888 Before answering him, can you tell me the time of his first submission to the cloud?

**Comment by thomasyu888** [comment]
His first training submission is: 	01/05/2017 03:12:04PM But he doesnt seem to have any inference submissions....

**Comment by tschaffter** [comment]
@thomasyu888 Submitted or scored? We can then suggest him to submit earlier in Round 3. :)

**Comment by thomasyu888** [comment]
He has one ACCEPTED training 02/02/2017 05:51:09PM.  He should probably submit to the inference lanes to get results though...

**Comment by thomasyu888** [comment]
I responded, but not sure if thats a good response.

**Comment by tschaffter** [comment]
@thomasyu888 There are a few typos in your answer that makes it a little confusing (e.g. "If you submit in the earlier rounds" > "If you submit earlier in the 3rd round"). Otherwise your answer is good. Thanks!
