### ISSUE TITLE
Log file of (submission ID 8220999)

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#613]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1682

**Comment by tschaffter** [comment]
@brucehoff Can you have a look?

**Comment by brucehoff** [comment]
@tschaffter This is simply an express lane submission which had timed out. Would you please let @thomasyu888 do the first round of triage on questions like this.  He can then forward actual infrastructure issues to me.  Thanks.

**Comment by tschaffter** [comment]
@brucehoff I've realised that and started to forward more issues to Tom since today.
