### ISSUE TITLE
Please.. cancel all old submissions except last one

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#615]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1684

**Comment by tschaffter** [comment]
@brucehoff Can you have a look?

**Comment by tschaffter** [comment]
Related to #559

**Comment by brucehoff** [comment]
@thomasyu888 Can you handle inference cancelation requests for now using the script I mentioned earlier?  In the future we will add a 'cancel' button so users can do this themselves.

**Comment by thomasyu888** [comment]
Yup.  I can do the cancellation.

**Comment by brucehoff** [comment]
Thanks!
