### ISSUE TITLE
implement a time limit for inference submissions

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#616]
submission 8112333 started on 02/01/2017 12:42:22PM and is still running, nearly six days later.  We need to implement a hard cut-off to ensure a single submission doesn't tie up a machine with unproductive work.  We should look at the distribution of cycle times for Round 1 and Round 2 (to date) then decide on a extra 'margin'.  We should then announce the hard cut-off to the participant community and implement it.

**Comment by tschaffter** [comment]
I have the following suggestion:

My custom monitoring script identifies the type of the container (pre-processing, training or inference) and collect custom metrics accordingly. For inference containers, the script is counting the number of unique (subjectID + "_" + laterality) to provide a sense of the progressing of the inference script. In the next newsletter and checklist (#565), we stress that participant should systematically save the predictions to file after processing a subject. That we will have the progress rate of the inference container and can evaluate how long it's going to take to process all the subject. Based on this information, we can cancel the submission automatically if we identify that the container would take more than N days to complete. This allows to predict and cancel inference submissions instead of having them running for the N days and result in an incomplete submission.

**Comment by brucehoff** [comment]
@tschaffter I like the idea. I would just word it such that there is an incentive for the user to write their output continually.  Instead of saying, "Writing prediction values continually allows us to extrapolate your completion date and cancel slow running submissions," I would phrase it as, "We reserve the right to cancel long running submissions.  If you provide incremental output we can detect that a long running submission nears completion to allow it to keep running."  

> For inference containers, the script is counting the number of unique (subjectID + "_" + laterality) to provide a sense of the progressing of the inference script.

I would suggest writing the % completion to a submission annotation.  This would allow us to show the progress to the user.

**Comment by tschaffter** [comment]
Here is a thread on the forum related to this item.

https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1295

**Comment by tschaffter** [comment]
Hopefully, tracking the progress rate should allow us to stop early submissions that would take too long to process.

**Comment by brucehoff** [comment]
We've gotten pretty far without enforcing a cutoff so, for now, I am removing the "Major" label.

**Comment by brucehoff** [comment]
Having finished Round 2 we have found that most inference submissions finish in 1-2 days but a few have kept running well over a week.  We are manually cutting off inference submissions that go over *8 days*.  This script shows how long inference submissions have been running:
```
library(synapseClient)
synapseLogin()
totalNumberOfResults<-99999999
offset<-0
pageSize<-20
#evaluationId<-"7453778" # SC
evaluationId<-"7453793" # SC2
while (offset<totalNumberOfResults) {
	result<-synRestGET(paste0("/evaluation/submission/query?query=select+status%2C+objectId%2C+SUBMITTER%2C+TRAINING_STARTED%2C+TRAINING_LAST_UPDATED+from+evaluation_", evaluationId,
		"+where+status%3D%3D%22EVALUATION_IN_PROGRESS%22%20ORDER%20BY%20objectId%20DESC%20LIMIT%20", pageSize, "%20OFFSET%20", offset))
	totalNumberOfResults<-result$totalNumberOfResults
	subIdIndex<-which(result$headers=="objectId")
	teamIdIndex<-which(result$headers=="SUBMITTER")
	startedIndex<-which(result$headers=="TRAINING_STARTED")
	updatedIndex<-which(result$headers=="TRAINING_LAST_UPDATED")
	for (row in result$rows) {
		subId<-row$values[[subIdIndex]]
		teamId<-row$values[[teamIdIndex]]
		runtimeMillis<-as.numeric(row$values[[updatedIndex]])-as.numeric(row$values[[startedIndex]])
		runtimeDays<-runtimeMillis/3600000/24
		cat("ID: ", subId, " Team: ", teamId, " Runtime (days): ", runtimeDays, "\n")
	}
	offset<-offset+pageSize
}
```
This script times out submissions that have been running for too long:
```
timeout<-function(ids) {
	for (id in ids) {
		ss<-synGetSubmissionStatus(id)
		n<-length(ss@annotations@longAnnos)
		la<-new("LongAnnotation")
		la@key<-"TIME_REMAINING"
		la@value<-0
		ss@annotations@longAnnos@content[[n+1]]<-la
		synStore(ss)
	}
}
```

I don't know that we need to implement automatic cutoff but if we decide to it's a simple matter to duplicate the express lane time limit script, seen here: http://ec2-50-112-143-48.us-west-2.compute.amazonaws.com:8080/job/DM%20Express%20Lane%20Time%20Limit%20for%20Evaluation%207500024/configure, replacing 30 minutes with 8 days

**Comment by tschaffter** [comment]
Done
