### ISSUE TITLE
Please delete my submission id 8203512, because it does not pass the express line. Thanks!

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#618]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1686

**Comment by tschaffter** [comment]
The spike in cancelation requests is partially due to the fact that the express lane was down for 1-2 days. Now the express lane may be stacked and participants are sending their submissions before the deadline.
