### ISSUE TITLE
Cancel Round 2 Training Submissions after Round 2 ends

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#626]
As of this time there are 13 training submissions running and 5 queued up.  We are justified in stopping them all but it would be 'nice' to let them run.  There is a need to complete the training submissions in a timely manner to address maintenance issues on the Softlayer servers.  A compromise is to cancel just the queued submissions.  Note:  All queued submissions are from teams already running submissions:
```
team sending submission 8156094 is bound to server bm19 submitter: 3343061 user 3343061 preprocessing is same, took  0.13 hours to complete. ** Another submission from this team is currently running **
team sending submission 8210558 is bound to server bm20 submitter: 3342897 user 3342896 preprocessing has CHANGED.  ** Another submission from this team is currently running **
team sending submission 8210805 is bound to server bm19 submitter: 3346918 user 3347393 preprocessing is same, took  43.94 hours to complete. ** Another submission from this team is currently running **
team sending submission 8219975 is bound to server bm23 submitter: 3342863 user 3346114 preprocessing has CHANGED.  ** Another submission from this team is currently running **
team sending submission 8224371 is bound to server bm23 submitter: 3342863 user 3346114 preprocessing has CHANGED.  ** Another submission from this team is currently running **
```

**Comment by brucehoff** [comment]
```
requestCancelation<-function(ids) {
	for (id in ids) {
		ss<-synGetSubmissionStatus(id)
		ss@cancelRequested<-TRUE
		synStore(ss)	
	}
}

requestCancelation(c("8156094", "8210558", "8210805", "8219975", "8224371"))
```

**Comment by brucehoff** [comment]
In addition to canceling queued submissions, I updated the time limit code to include the hiatus week allowing it to update the submissions we've let run past the end of the round.  The Jenkins job is here:
http://ec2-50-112-143-48.us-west-2.compute.amazonaws.com:8080/job/DM%20Leaderboard%20Training%20Time%20Limit/
and the change is as shown:
```
#!/bin/bash
# original settings for round 2
#python /home/ubuntu/DM-Challenge-Quota-Application/quota.py -u evaluationstatistics -p xxxxx --start '2017-01-03 00:00' --quota 1209600000 --cumulation 3139200000 --numrounds 1  7213944
# increased round from 36 1/3 days to 43 days so we can run past the end of round 2
python /home/ubuntu/DM-Challenge-Quota-Application/quota.py -u evaluationstatistics -p xxxxx --start '2017-01-03 00:00' --quota 1209600000  --cumulation 3715200000 --numrounds 1  7213944

```

**Comment by tschaffter** [comment]
We could have kept the queued submissions, stop training machines to process new submissions and do the update of the machine at the first occasion, then restart then so that they continue to process the queue. Anyway, cancelling the training submission also works for me. We can decide to resubmit then or let the participants do it.

**Comment by tschaffter** [comment]
@brucehoff As discussed, you can cancel all remaining training submissions from Round 2 first thing on Monday. I'll then upgrade the machines and they will be ready for Round 3. This ticket can be closed once all training submissions have been halted.

**Comment by brucehoff** [comment]
There are four submissions still running.  We use 'docker stop' to stop them which triggers the agent to clean up and notify the submitter.
8211177 bm01
8210962 bm07
8096789 bm19
8122684 bm19
