### ISSUE TITLE
Team-up policy?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#627]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1695

**Comment by thomasyu888** [comment]
Can you submit as part of a new team every round?  Or does synapse flag that as an error?

**Comment by brucehoff** [comment]
Team participation is fixed during each round.  See "Submission restriction rule" here:
https://sagebionetworks.jira.com/wiki/display/PLFM/Submission+with+Teams
(we need to add this verbiage to our API documentation for Submission)

**Comment by thomasyu888** [comment]
Please help answer this thread.  She states:

> other teams have a huge advantage, because they can split even in the 3rd round and double and even triple their hours, and then combine in the final round. A team of 5 people can practically have 1800 hours, while I only have 350! They have 15 submission tests, while I have 3.

**Comment by tschaffter** [comment]
I understand her question better now:

> Before the beginning of round 3 or before the beginning of final submission round?

This is a situation that we need indeed to clarify. The answer should be that participants have until the beginning of Round 3 (Monday Feb 7, 23:59) to change the composition of their team. Once Round 3 is completed, there is no reason to allow further team modification as the Validation Phase should mainly consists in training the model once (unless we prevent it, participants would currently be able to train multiple times before submitting the model that they think achieves the best performance) and then evaluate it once against the scoring set.

@thomasyu888 Can you reproduce below the elements from the documentation that refers to team composition, in particular element specific to the Challenge?

Then I'll send an email to Gustavo and Justin, who will then most likely send a remainder to the participants to change team before Feb 7 if it's the deadline that they agree on.

**Comment by thomasyu888** [comment]
Here is the rules for Teams: https://www.synapse.org/#!Synapse:syn4294018/wiki/232126 It is under the teams section.

**Comment by tschaffter** [comment]
Thanks Tom. I've sent an email to Gustavo and Justin (I learned meanwhile that you did the same). Waiting for an update from them.
