### ISSUE TITLE
inference submission limit was set to 6, not 3, for round 2

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#630]
I just noticed that one participant has four submissions in Round 2.  This should not be possible!  The reason is that we accidentally left the submission limit set to six, a change made for Round 1.  I have changed the limit back to three but we have to check how many participants have gone over the limit, then decide what to do with the extras.

**Comment by thomasyu888** [comment]
I think we should let all the submissions run and just take the best 3 after they have all completed running.

**Comment by tschaffter** [comment]
I don't think that this would be fair for participants who stopped sending submissions after three.

@brucehoff Do we display somewhere the remaining number of shots against the scoring set?

If the above answer is yes, we don't really have a problem as everyone could have used six submissions. If not, we should only consider the first three submissions. Do you all agree?

**Comment by brucehoff** [comment]
> I don't think that this would be fair for participants who stopped sending submissions after three.

I abolutely agree with @tschaffter . Beyond our effort to be 'fair' we would have an alarming exposure to criticism if we let some teams submit more than others, especially with large cash prizes on the line.  We must avoid even slightest appearance of doing anything which does not treat all participants equally.

> @brucehoff Do we display somewhere the remaining number of shots against the scoring set?

Yes, in the sense that there is a dashboard showing how many submissions each participant has sent in.  They can count the rows and subtract from '3'.


Here's the actual data:  In sub-challenge 1 we have three teams that went over the 3 submission limit  In sub-challenge 2 we have NO teams that exceeded the limit.  Here are the results for sub-challenge 1:

3346341 {u'OPEN': 4}   
This is team Yussuf, https://www.synapse.org/#!Team:3346341
3319922 {u'SCORED': 2, u'RECEIVED': 1, u'INVALID': 2, u'EVALUATION_IN_PROGRESS': 1}
This is team Clinical Persona, https://www.synapse.org/#!Team:3319922
3347527 {u'SCORED': 6, u'INVALID': 4}
This is team CSC490, https://www.synapse.org/#!Team:3347527

> we should only consider the first three submissions.
I agree with this, as it would bring the system back to the originally intended state.  To implement this correction:
1) We would invalidate the fourth, pending submission from team Yussuf (let the first 3 run);
2) We wold invalidate the fourth, pending submission from team Clinical Persona (let the currently running one complete);
3) Invalidate the last three of the six already scored for team CSC490.  This is the only step that's not 'invisible' to the participants, since they've already received their scores.

**Comment by tschaffter** [comment]
> Yes, in the sense that there is a dashboard showing how many submissions each participant has sent in. They can count the rows and subtract from '3'.

@brucehoff Just to make sure, in Round 2, there is nothing that indicates a team that they can submit more than the three submissions/sub-challenge that we have announced? The teams who got 6 submissions just tried their luck with a forth submission and saw it running and scored?

**Comment by brucehoff** [comment]
@tschaffter  Yes, that is correct.

**Comment by tschaffter** [comment]
@brucehoff This is perfect! That way we can effectively cancel the last three submissions from team CSC490 without having them coming at us and say that they planned their inference submissions across the duration of Round 2 because they knew that they had six submissions.

**Comment by brucehoff** [comment]
Details on the proposed course of action:
1) For team Yussuf, here are the submissions, all of which are pending:
8222835
8223009
8223049
8223097 <<< we will change the status to INVALID

2) For team Clinical Persona, here are the submissions which are *not* invalid:
8074996 (scored)
8129608 (scored)
8129441 (evaluation in progress)
8112333 (received) <<< we will change the status to INVALID

3) For team CSC490  here are the six scored submissions along with their AUROC values:
8044508 0.5
8058003 0.5
8066088 0.4967
8085938 0.5411<<< we will change the status to INVALID
8085974 	0.5578<<< we will change the status to INVALID
8104337 0.5<<< we will change the status to INVALID

**Comment by brucehoff** [comment]
It's done:   I used this script to invalidate the five submissions:
```
invalidate<-function(ids) {
	for (id in ids) {
		ss<-synGetSubmissionStatus(id)
			ss@status<-"INVALID"
			n<-length(ss@annotations@stringAnnos)
			failureReasonFound<-F
			for (i in 1:n) {
				if (ss@annotations@stringAnnos@content[[i]]@key=="STATUS_DESCRIPTION") ss@annotations@stringAnnos@content[[i]]@value<-"OVER SUBMISSION LIMIT"
				if (ss@annotations@stringAnnos@content[[i]]@key=="FAILURE_REASON") {
					failureReasonFound<-T
					ss@annotations@stringAnnos@content[[i]]@value<-"OVER SUBMISSION LIMIT"
				}
			}
			if (!failureReasonFound) {
				sa<-new("StringAnnotation")
				sa@key<-"FAILURE_REASON"
				sa@value<-"OVER SUBMISSION LIMIT"
				ss@annotations@stringAnnos@content[[n+1]]<-sa
			}
			synStore(ss)
	}
}
> invalidate("8223097")
> invalidate("8112333")
> invalidate("8085938")
> invalidate("8085974")
> invalidate("8104337")
```
