### ISSUE TITLE
submission limit question

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#633]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1698

**Comment by thomasyu888** [comment]
How did you guys pick which submissions to make invalid?

**Comment by brucehoff** [comment]
> How did you guys pick which submissions to make invalid?

Please see my response on the forum.  Additional details are here: https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/630
