### ISSUE TITLE
retrieve / publish container progress

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#639]
Mount a writable file to each running container.  Retrieve the first 3 characters, check that it's a number between 0 and 100, and push to a public annotation.

**Comment by brucehoff** [comment]
Per Thomas:  The file need not be mounted by `docker run`.  Instead we would ask participants to write to `/progress.txt` and then read the contents via:
```
docker exec <container> cat /progress.txt
```

**Comment by tschaffter** [comment]
Considering the larger number of items to process (images during
pre-processing, breast during inference, etc.), I propose to ask
participants to write a number between 0 and 100. When reading the file, we
take only the first 5 characters and display in the dashboard a number with
two decimals (e.g. #.##, ##.## and 100). Because the file is saved inside
their container, there is no issue regarding file size.

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/639

**Comment by brucehoff** [comment]
TODO:
- deploy modified agent
- mirror wikis (to display new dashboard column)
- announce to participants

**Comment by tschaffter** [comment]
@brucehoff Des the implementation follow the format that I suggested (for the documentation)? 

What have you decide for when there is an error (file not found, value is not a double, etc.)?

**Comment by brucehoff** [comment]
We read the first five characters of the "/progress.txt" file, parse as a float and 'publish' the value to the dashboard.  If the file is missing or if the <=5 characters are not a number then no number is published.

**Comment by tschaffter** [comment]
Great!

**Comment by brucehoff** [comment]
From the Docker command line:
```
ubuntu@ip-172-31-59-223:~/DigitalMammographyChallenge$ docker exec 9a07b4274e8b cat /progress.txt
69.04761904761905

```
but from within the agent:
```
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - execOutput: STDOUT: rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"cat /progress.txt\": stat cat /progress.txt: no such file or directory"

```

**Comment by brucehoff** [comment]
You can also use the container name in place of the container ID:
```
ubuntu@ip-172-31-59-223:~$ docker exec 8259231.p28x02-1.TRAIN.TRAINING cat /progress.txt
90.47619047619048
```

**Comment by brucehoff** [comment]
I can duplicate the problem I have with the Docker Java client like so:
```
ubuntu@ip-172-31-59-223:~$ docker exec ecc8ff6bdeb3381b680f7aec23c1562584d46316cf38fc0b251ade4fa801550c "cat /progress.txt"
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"cat /progress.txt\": stat cat /progress.txt: no such file or directory"
```

**Comment by tschaffter** [comment]
Does it works if you use `/usr/bin/cat`instead of `cat`?

**Comment by tschaffter** [comment]
which lead me to think: what if `/usr/bin/cat` is not available in the container of the participants? Because we don't control the container of the participant, it may be safer/easier to save the progress to file. Did you say that the agent would shutdown if their temp directory is becoming full? If yes, let keep `/data/tempDir` for the submissions and use `/data/tempAgentDir` for the agents.

**Comment by brucehoff** [comment]
@tschaffter I got it working now.  There was just a small issue in passing the shell command to the Docker Java client.  

I think it's OK to assume the 'cat' command, since the images are all built on some Unix base image.  If not the progress value simply does not appear.  If it becomes a problem we can use a different approach (mount a writable file) without changing any user instructions.

Of the previous remaining tasks:

DONE >>>> deploy modified agent
DONE >>> asked @thomasyu888  to mirror wikis (to display new dashboard column)

announce to participants:
@tschaffter will you add a description of this feature to your draft newsletter (or point me to the doc and I will add it).

**Comment by tschaffter** [comment]
@brucehoff One can see `/progress.txt` as a window to stream data out of the locked Leaderboard dataset. A participant could make its program streaming a different value every 30 minutes while still complying with the value staying in [0,100].

Do you agree with the following test:

- Check that the value is in [0,100] (most likely already done)
- Check that the value is larger than the previous value (a property inherent to progress value)?

**Comment by brucehoff** [comment]
> One can see /progress.txt as a window to stream data out of the locked Leaderboard dataset. 

Yes, the potential for data leak is why the feature is so restrictive:  You can only output five characters and they must be numeric, 0->100.  For a submission that runs for 48 hours the potential data leak is only 14KB.

**Comment by tschaffter** [comment]
> For a submission that runs for 48 hours the potential data leak is only 14KB.

For training that's not an issue, however for inference we are in the configuration that no data should go out. Currently, data can be obtained by making the submission exit with status != 0 to collect the last N bytes of the log file (what's the current value)?

Checking that the current value is >= than the previous value virtually reduce the data leak to 0. Agent can keep the previous value in a temp file. If the condition is violated, we display an invalid status in the dashboard.

**Comment by tschaffter** [comment]
Reopened because we have agreed to implement the test that the new value must be larger or equal to the previous value (see previous messages).

**Comment by tschaffter** [comment]
@brucehoff I'll let you close this ticket if you think that we are done with this feature (with or without the last test that I suggested). Thanks!
