### ISSUE TITLE
KeyError when running tensorflow example

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#64]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1115

**Comment by brucehoff** [comment]
Thomas:  I believe this question is regarding the challenge metadata.  Could you respond?
> Also, may I asked what is the meaning of '.'? Does it mean that the data set is incomplete? Or does it have a special meaning?

**Comment by tschaffter** [comment]
'.' represents missing data.

**Comment by brucehoff** [comment]
Thanks, Thomas.
