### ISSUE TITLE
about Feb 12, 2017 news letter

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#640]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1704

**Comment by thomasyu888** [comment]
Forwarded to Gustavo/Justin

**Comment by thomasyu888** [comment]
I'm not sure if this thread is finished?

**Comment by tschaffter** [comment]
Yes, this ticket should be kept open.

**Comment by tschaffter** [comment]
They should put the "Close and comment" button in red...

**Comment by thomasyu888** [comment]
Yeah.... Agreed

**Comment by tschaffter** [comment]
I've reviewed the last questions on this thread and consider that recent data given to the participants answer the questions.
