### ISSUE TITLE
Cached file is in the directory, but can not be opened by training script

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#653]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1726

**Comment by thomasyu888** [comment]
Do you guys clean the disks up inbetween rounds?  Do participants have to re-run preprocessing?

**Comment by tschaffter** [comment]
@thomasyu888 We don't clean the pre-processing data. Please remind the participant that we don't guarantee that the pre-processing data are always available. If there are more participants than the total number of `/preprocessedData` partitions, the consistency of their data is not guaranteed.

**Comment by brucehoff** [comment]
I wouldn't say "the consistency is not guaranteed".  (Sounds like their data can be corrupted.  Perhaps the "constancy" is not guaranteed. )  Anyway, I'd just say that we do our best to cache your preprocessing results and only remove the cached files if administrative tasks require it and such tasks do not occur very often.
