### ISSUE TITLE
Container security

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#665]
In a discussion unrelated to the challenge I learned that when we run containers as root (which is the default when running a container) this is the same user as root on the host machine, providing an 'attack surface.'  We should consider how to change this.  I'm using this issue to collect the information I've gathered.

https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.12.0_Benchmark_v1.0.0.pdf
says "ensure that the docker daemon is running with --userns-remap flag"

p. 165
Start a container as below:
docker run <run-options> --security-opt=no-new-privileges <IMAGE> <CMD>

More on namespace mapping here:
https://www.linkedin.com/pulse/docker-110-security-features-part-3-user-namespace-amir-jerbi

Another reference:
https://dev.arvados.org/projects/arvados/wiki/Docker_security

**Comment by brucehoff** [comment]
Per Thomas:  Let's try some security modifications on the express lane and check that that nothing breaks:
1) docker run --security-opt=no-new-privileges 
2) create a user on the host and map container user (root?) to that user

**Comment by tschaffter** [comment]
@brucehoff Is there any progress regarding that issue?

**Comment by brucehoff** [comment]
not yet, will post progress here

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/7528495184666a23a541ee40804e3f15e5d8c092
