### ISSUE TITLE
plot cumulative model state download across entire challenge over time

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#673]
this is to check for users creating fake accounts to download data

- how many teams have downloaded more than, say, 80% of their data?
- what is the total data download?

**Comment by brucehoff** [comment]
To answer this question, for each team:  Create an ordered list of (timestamp, filesize) from (1) contents of team data table (this is the log file data), (2) submissions in which MODEL_STATE_UNLOCKED annotation is public (use the TRAINING_LAST_UPDATED and MODEL_STATE_SIZE_BYTES) annotations.   Now graph the cumulative data downloaded over time.

To answer the specific questions posed above, list the team names of those who have reached (80%)*35GB and sum up the downloaded data across all teams.

**Comment by brucehoff** [comment]
A preliminary solution can be seen here: https://www.synapse.org/#!Synapse:syn7986624/wiki/411310
(Scroll about halfway down, to the end of the stat's on the training queue.)
This only shows the model state downloaded.  Still need to add the size of the returned log files.

**Comment by tschaffter** [comment]
Thanks! This is great. It seems that the teams are behaving and none of them are trying to steal big chunk of the dataset.
