### ISSUE TITLE
Preprocessing is GONE and rerunning

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#687]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1786

**Comment by brucehoff** [comment]
Please see my reply:  The participant is switching back and forth between preprocessing methods, causing the system to replace his cached preprocessing results with each submission.

**Comment by tschaffter** [comment]
@brucehoff Thanks for having investigated this.
