### ISSUE TITLE
Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#69]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1128

From the log shared by the user:
...
time="2016-10-25T18:42:23.201334114Z" level=error msg="Upload failed, retrying: net/http: TLS handshake timeout" 
time="2016-10-25T18:42:34.845226099Z" level=debug msg="Pushing layer: sha256:4ce5da20b321f736cfca575ff81f920ccc670b41321a8845201157e162fb067f" 
time="2016-10-25T18:42:38.203237817Z" level=debug msg="Pushing layer: sha256:38ece981f0d9e415bdb13c3f4c0b30f3808b9c7b1a9ea91131376c93da293296" 
time="2016-10-25T18:42:48.069611034Z" level=error msg="Upload failed, retrying: net/http: TLS handshake timeout" 
time="2016-10-25T18:43:02.806650505Z" level=error msg="Upload failed, retrying: net/http: TLS handshake timeout" 
time="2016-10-25T18:43:08.075196300Z" level=debug msg="Pushing layer: sha256:4ce5da20b321f736cfca575ff81f920ccc670b41321a8845201157e162fb067f" 
time="2016-10-25T18:43:22.808827661Z" level=debug msg="Pushing layer: sha256:38ece981f0d9e415bdb13c3f4c0b30f3808b9c7b1a9ea91131376c93da293296" 
time="2016-10-25T18:43:23.077284883Z" level=error msg="Upload failed: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2016-10-25T18:43:23.078402528Z" level=debug msg="Pushing layer: sha256:a0dc2eaec3c374bcdd40b18e4020374bb392224cdf090ab912ebd1cbb2945333" 
time="2016-10-25T18:43:38.080782494Z" level=error msg="Upload failed: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" 
time="2016-10-25T18:43:38.081875390Z" level=debug msg="Pushing layer: sha256:ca20b906b87c8498d6e9759ea4fa0f3283ac83006e2db468761831706966543f" 
time="2016-10-25T18:43:51.443739695Z" level=error msg="Upload failed, retrying: net/http: TLS handshake timeout" 
time="2016-10-25T18:43:56.445530276Z" level=debug msg="Pushing layer: sha256:a0dc2eaec3c374bcdd40b18e4020374bb392224cdf090ab912ebd1cbb2945333" 
time="2016-10-25T18:44:04.613524974Z" level=error msg="Upload failed, retrying: net/http: TLS handshake timeout" 
time="2016-10-25T18:44:09.620303432Z" level=debug msg="Pushing layer: sha256:ca20b906b87c8498d6e9759ea4fa0f3283ac83006e2db468761831706966543f" 
time="2016-10-25T18:44:19.594890787Z" level=debug msg="Increasing token expiration to: 60 seconds" 
time="2016-10-25T18:44:41.944186354Z" level=debug msg="Assembling tar data for 6db38a47dd961cec7a9b220d8057ef5ec63c671511282d02720ab57027706f47" 
time="2016-10-25T18:44:42.135082011Z" level=debug msg="Assembling tar data for f20a359e7d2af3f1234185e939b919e11ed11e1fe20affbd37e787f9a1b3cf23" 
time="2016-10-25T18:45:41.676219158Z" level=debug msg="uploaded layer sha256:a0dc2eaec3c374bcdd40b18e4020374bb392224cdf090ab912ebd1cbb2945333 (sha256:764adac6e54f6b3bf6166faa9b041cf55ce9bace74864f7b0036e39e325eb945), 14433 bytes" 
time="2016-10-25T18:45:41.735402052Z" level=debug msg="Pushing layer: sha256:30596d6a4f4c7b351708a9e233c9becbb1000801de46aa3d0df5ce31f0fd7ba3" 
time="2016-10-25T18:45:56.740957585Z" level=error msg="Upload failed, retrying: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2016-10-25T18:46:01.743254671Z" level=debug msg="Pushing layer: sha256:30596d6a4f4c7b351708a9e233c9becbb1000801de46aa3d0df5ce31f0fd7ba3" 
time="2016-10-25T18:46:16.748723050Z" level=error msg="Upload failed, retrying: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2016-10-25T18:46:26.750990627Z" level=debug msg="Pushing layer: sha256:30596d6a4f4c7b351708a9e233c9becbb1000801de46aa3d0df5ce31f0fd7ba3" 
time="2016-10-25T18:46:40.974658336Z" level=error msg="Upload failed, retrying: net/http: TLS handshake timeout"

**Comment by brucehoff** [comment]
I recommend closing this issue:  The user had a particularly slow internet connection and was able to resolve the problem himself by moving his client to a cloud provider having better connectivity.
