### ISSUE TITLE
Dependency failed for /data/datasetXX on p28x02 (Express Lane Inference)

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#702]
p28x02 (Express Lane Inference) shows many similar issues in `/var/log/messages`:

```
Mar 12 03:21:25 p28x02 systemd: Starting Network Manager Script Dispatcher Service...
Mar 12 03:21:25 p28x02 dbus[2419]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Mar 12 03:21:25 p28x02 dbus-daemon: dbus[2419]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Mar 12 03:21:25 p28x02 systemd: Started Network Manager Script Dispatcher Service.
Mar 12 03:21:25 p28x02 nm-dispatcher: req:1 'dhcp4-change' [eth0]: new request (3 scripts)
Mar 12 03:21:25 p28x02 nm-dispatcher: req:1 'dhcp4-change' [eth0]: start running ordered scripts...
Mar 12 03:22:56 p28x02 systemd: Job dev-disk-by\x2duuid-6eff5a51\x2df91a\x2d45f3\x2d9be8\x2d7a6b31af6bc6.device/start timed out.
Mar 12 03:22:56 p28x02 systemd: Timed out waiting for device /dev/disk/by-uuid/6eff5a51-f91a-45f3-9be8-7a6b31af6bc6.
Mar 12 03:22:56 p28x02 systemd: Dependency failed for /data/dataset53.
Mar 12 03:22:56 p28x02 systemd: Job data-dataset53.mount/start failed with result 'dependency'.Mar 12 03:22:56 p28x02 systemd: Dependency failed for File System Check on /dev/disk/by-uuid/6eff5a51-f91a-45f3-9be8-7a6b31af6bc6.
Mar 12 03:22:56 p28x02 systemd: Job systemd-fsck@dev-disk-by\x2duuid-6eff5a51\x2df91a\x2d45f3\x2d9be8\x2d7a6b31af6bc6.service/start failed with result 'dependency'.
Mar 12 03:22:56 p28x02 systemd: Job dev-disk-by\x2duuid-6eff5a51\x2df91a\x2d45f3\x2d9be8\x2d7a6b31af6bc6.device/start failed with result 'timeout'.
Mar 12 03:22:56 p28x02 systemd: Job dev-disk-by\x2duuid-94adacc9\x2d99f1\x2d44c1\x2db0d5\x2dd2dd6a68e7f8.device/start timed out.
Mar 12 03:22:56 p28x02 systemd: Timed out waiting for device /dev/disk/by-uuid/94adacc9-99f1-44c1-b0d5-d2dd6a68e7f8.
Mar 12 03:22:56 p28x02 systemd: Dependency failed for File System Check on /dev/disk/by-uuid/94adacc9-99f1-44c1-b0d5-d2dd6a68e7f8.
Mar 12 03:22:56 p28x02 systemd: Dependency failed for /data/dataset38.
Mar 12 03:22:56 p28x02 systemd: Job data-dataset38.mount/start failed with result 'dependency'.
Mar 12 03:22:56 p28x02 systemd: Job systemd-fsck@dev-disk-by\x2duuid-94adacc9\x2d99f1\x2d44c1\x2db0d5\x2dd2dd6a68e7f8.service/start failed with result 'dependency'.
Mar 12 03:22:56 p28x02 systemd: Job dev-disk-by\x2duuid-94adacc9\x2d99f1\x2d44c1\x2db0d5\x2dd2dd6a68e7f8.device/start failed with result 'timeout'.
Mar 12 03:22:56 p28x02 systemd: Job dev-disk-by\x2duuid-40304b8e\x2d5419\x2d4c1d\x2db05d\x2d953f1d257032.device/start timed out.
Mar 12 03:22:56 p28x02 systemd: Timed out waiting for device /dev/disk/by-uuid/40304b8e-5419-4c1d-b05d-953f1d257032.
Mar 12 03:22:56 p28x02 systemd: Dependency failed for /data/dataset86.
Mar 12 03:22:56 p28x02 systemd: Job data-dataset86.mount/start failed with result 'dependency'.
Mar 12 03:22:56 p28x02 systemd: Dependency failed for File System Check on /dev/disk/by-uuid/40304b8e-5419-4c1d-b05d-953f1d257032.
Mar 12 03:22:56 p28x02 systemd: Job systemd-fsck@dev-disk-by\x2duuid-40304b8e\x2d5419\x2d4c1d\x2db05d\x2d953f1d257032.service/start failed with result 'dependency'.
Mar 12 03:22:56 p28x02 systemd: Job dev-disk-by\x2duuid-40304b8e\x2d5419\x2d4c1d\x2db05d\x2d953f1d257032.device/start failed with result 'timeout'.
```

**Comment by tschaffter** [comment]
@brucehoff Inference machines do not have the partitions `/data/datasetXX`. Do the agents do something wrong by trying to refer to these partitions?

**Comment by tschaffter** [comment]
@brucehoff See above message. We need to take p28x02 out. Can you make so that the agents don't accept new submissions then turn off?

**Comment by brucehoff** [comment]
@tschaffter p28x02 is offline now

**Comment by tschaffter** [comment]
@brucehoff Inference machines do not have the partitions /data/datasetXX. Do the agents do something wrong by trying to refer to these partitions?

**Comment by brucehoff** [comment]
> Do the agents do something wrong by trying to refer to these partitions (see above)?

At present Docker will mount the non-existent partition to the agent (we can fix this if necessary).   Since it doesn't exist, Docker will create `/data/datasetXX` on the host machine.  The agent won't *do* anything with the created directory and won't mount it to the submitted inference submission.

**Comment by tschaffter** [comment]
@brucehoff If this doesn't require to much work, it's preferable to not have the scoring agents mounting unnecessary volumes. `/var/log/messages` is currently painted with red errors related to missing `/data/datasetXX`, making the identification of real errors more difficult. Once this is fixed, the machine can be put back online.

**Comment by tschaffter** [comment]
@brucehoff Any update?

**Comment by tschaffter** [comment]
Another issue is that, in addition to the errorsin /var/log/messages, empty directories are created, which is confusing. For example, the EFS `fs-4b1eba02.efs.us-east-1.amazonaws.com` host the Leaderboard Inference Set:

- /data/data/dm-challenge-dcm/SC1_leaderboard/*.dcm
- /data/data/dm-challenge-dcm/SC1_leaderboard/*.dcm
- /data/data/metadata/

The following empty directories are found on the same EFS but but they should not exist.

- /data/data/images/SC1_leaderboard/ (empty)
- /data/data/images/SC2_leaderboard/ (empty)
- /data/data/images/training/ (empty)

**Comment by brucehoff** [comment]
I changed the start-up scripts to mount just the volumes relevant to the 'role' (training or scoring).

https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/commit/3934dc9e20dfb9616998b4acdb4962574e4fd8ba


https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/commit/1ab997118bebe7a7a69da62abe2b09ee80089638
