### ISSUE TITLE
Why my existing preprocessing was reruned?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#705]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1830

**Comment by tschaffter** [comment]
The participant made two submissions and is asking why the pre-processing container started in the second submission.

Submission 1:
```
$ python lookupSubmission.py -u XXX -p XXX -s 8444525
Welcome, Thomas Schaffter!

8444525  has a preprocessing step.
	Use docker.synapse.org/syn7887972/8444525/preprocessing@sha256:e8c7928c3cf4b06bbdce26da08bc6388db1df8b818f88756a7357082142ba884
8444525  does NOT have a training step
```

```
$ python lookupSubmission.py -u XXX -p XXX -s 8456196
Welcome, Thomas Schaffter!

8456196  has a preprocessing step.
	Use docker.synapse.org/syn7887972/8456196/preprocessing@sha256:e8c7928c3cf4b06bbdce26da08bc6388db1df8b818f88756a7357082142ba884
8456196  has a training step
	but there is no archived submission
```

Note that the digest of the pre-processing container is the same same but the repository name is different.

@brucehoff 

- Question 1: My understanding is that the digest define uniquely a container. Is that correct? Therefore the pre-processing container should not have started the second time.
- Question 2: The script `lookupSubmission.py` is not giving the repository name or the digest of the training container. Is this a bug?

Thanks!

**Comment by brucehoff** [comment]
> My understanding is that the digest defines uniquely a container. Is that correct? 
To be precise:  The repository name (`docker.synapse.org/syn7887972/8456196/preprocessing`) and digest (`sha256:e8c7928c3cf4b06bbdce26da08bc6388db1df8b818f88756a7357082142ba884`) together uniquely define an *image*.  (A container is a running image.)

> Therefore the pre-processing container should not have started the second time.
Please remember that the name/digest you see is a secondary tag that we create to refer to the user's submitted image.  The logic to decide whether to rerun preprocessing is based on the name+digest submitted by the user.  If the user repeats exactly the name+digest from their previous submission then we do not rerun preprocessing.  You can modify the 'lookupSubmission.py' script to print out the name+digest submitted by the user.


> The script lookupSubmission.py is not giving the repository name or the digest of the training container. Is this a bug?

No (though perhaps you could argue it's a design flaw in the agent).  The challenge agent only creates the 'secondary tag' for an image when it pulls it to run.  If a submission does not require rerunning preprocessing then the agent does not pull the image and hence does not tag it. You might check earlier submissions to find a secondary tag for the preprocessing image.

**Comment by tschaffter** [comment]
@brucehoff 

> The repository name (docker.synapse.org/syn7887972/8456196/preprocessing) and digest (sha256:e8c7928c3cf4b06bbdce26da08bc6388db1df8b818f88756a7357082142ba884) together uniquely define an image.

Are BOTH repository name and digest required to uniquely identify an image, or is it just the way that you have implemented it the agents? It seems to me that the digest should be enough to uniquement identify any Docker image but I didn't find a clear answer.

> Thomas: The script lookupSubmission.py is not giving the repository name or the digest of the training container. Is this a bug?
> Bruce: You might check earlier submissions to find a secondary tag for the preprocessing image.

This is still a bit confusing to me. To summarise, does that means that `lookupSubmission.py`:

1. does not report the repository name + digest specified by the participant but the "copied" reference of the image (because I suggested that we should make a copy of the images submitted in case the participant deletes them) AND
2. shows only the repository name + digest if the corresponding container has been run?

**Comment by tschaffter** [comment]
In addition, if a participant give two Submission IDs, can `lookupSubmission.py` be used to determine if he submitted the same pre-processing image?

**Comment by brucehoff** [comment]
> Are BOTH repository name and digest required to uniquely identify an image, or is it just the way that you have implemented it the agents? 

The latter.

> does not report the repository name + digest specified by the participant but the "copied" reference of the image

Yes that is its purpose.  In the process it also retrieves the name+digest submitted by the participant but, at the moment, does not print it out.  Printing out that information is a simple change you can make if you require that information.

> shows only the repository name + digest if the corresponding container has been run?

The script shows only the repository name + digest of the "copied" image if the container was retrieved and run.  Again, it retrieves the original, submitted name+digest and you can print that out if it is of interest.

**Comment by tschaffter** [comment]
@brucehoff The participant asked you a question. Can you answer him?

I've added an item to the Staging FAQ regarding why a pre-processing Docker image may be run again. Can you please have a look at it and if it's OK, ask Tom to mirror the change?

**Comment by brucehoff** [comment]
Done!
