### ISSUE TITLE
Stuck in validated mode

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#708]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1835

**Comment by thomasyu888** [comment]
@brucehoff I see on the dry run queue page that the participant created her submission before some of the ones that are already running.  Is it in random order that the submissions are started?

**Comment by brucehoff** [comment]
>  Is it in random order that the submissions are started?

No, the agents go through the list of available submissions by submission ID, oldest to newest.  But there are lots of reasons a newer submission might run before an older one.  A big factor is the location of the cached preprocessing result:  If an older submission reuses cached preprocessed data, then it will wait for the server to become available on which the preprocessed data resides.  Other, later submissions from other teams which do not reuse preprocessing results will simply run on whatever server is available.  They will generally run more quickly than jobs that reuse previous results.
