### ISSUE TITLE
Several questions about Final Round

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#710]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1838

**Comment by thomasyu888** [comment]
Is the inference quota 8 days for the final round?

**Comment by tschaffter** [comment]
@thomasyu888 The answer to your question is 18 days. However I'll take care of answering this thread now that we have agreed on the format of the Validation Phase.
