### ISSUE TITLE
Inference submission after 3rd round deadline.

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#718]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1852

**Comment by thomasyu888** [comment]
The participant states: "So the submission will guarantee to finish? Some threads I read are saying that those submission might get cut anytime due to computer maintenance."

I thought that all valid submissions submitted before the deadline is GUARANTEED to be accepted.
