### ISSUE TITLE
error, which occurred while trying to unzip 

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#723]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1856

**Comment by tschaffter** [comment]
@brucehoff Can you have a look?

```
{"fileSizeBytes":96554,"submissionId":"8486051","fileEntityId":"syn8487564","teamId":"3345069","expiresOn":"2017-03-22.08:00:00","createdOn":"2017-03-19.15:45:40"}8B939pgBCTI1ACmGSayG7KY4T4o=
```

How many days have the participants to unlock a model before it expires? We had a similar question from another participant, who was thinking that the expiration period is too short.

**Comment by tschaffter** [comment]
See #724

**Comment by brucehoff** [comment]
> How many days have the participants to unlock a model before it expires?
The expiration is the end of Round 3.  @tschaffter when do you think the expiration should be?

**Comment by tschaffter** [comment]
This is correct and this should be the same for the Validation Phase (end of the Phase). Then did participants had issues with the expiration date or was it due to something else?

**Comment by brucehoff** [comment]
> Then did participants had issues with the expiration date or was it due to something else?

It was something else.  The content of the signed "token" was modified, either by the participant or by their email client, so that our token parser was not able to separate the token and signature.
