### ISSUE TITLE
ModelState Download Failed

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#724]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1857

**Comment by tschaffter** [comment]
@brucehoff Has Synapse experience difficulties, e.g. related to S3, at the time the participant posted the message?

**Comment by brucehoff** [comment]
@tschaffter I know of no problem with Synapse or S3 that would explain the phenomenon.  I have answered the OP.
