### ISSUE TITLE
stop a running submission

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#731]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1866

**Comment by thomasyu888** [comment]
Don't participants have the ability to cancel inference submissions?

**Comment by brucehoff** [comment]
I stopped the submissions.  FYI the way to do it is:
1) Look up the name of the machine where the submission is running, under WORKER_ID here: https://www.synapse.org/#!Synapse:syn5644795/wiki/409766
2) log into the 'dmclient' machine
3) `eval $(docker-machine env <machine name>)`
4) `docker ps`
5) In the list of running containers find the one whose name contains the submission ID of interest
6) `docker stop <container name>`

**Comment by tschaffter** [comment]
I've copied/pasted your instructions here: https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/wiki/Managing-submissions
