### ISSUE TITLE
Improve lookupSubmission.py

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#732]
As discussed on Monday, I'd like to have `lookupSubmission.py` improved to meet the following specifications. This script will be useful for future experiments and debugging submissions.

### Note regarding immutable images archiving

Note that the submission files submitted by participants include the repository name + digest of images owned by the participants. Because they can remove these images anytime, `lookupSubmission.py` must return the reference of immutable images that will always be available, even if the participants remove their own images.

### Pre-processing only submission
Given a Submission ID, return the repository name + digest of the immutable pre-processing image. If the container was not run because the data were already cached, still return the reference to the immutable pre-processing image that reflect the state of the of the cache. It is assumed that the cached data are the result of a fully successful pre-processing container.

### Training only submission
Returns the reference to the corresponding immutable training image.

### Pre-processing + training submission
Returns the reference of both immutable pre-processing and training images. See "Pre-processing only submission" and "Training only submission".

### SC1 or SC2 submission
Returns the reference to the corresponding immutable inference image.

**Comment by tschaffter** [comment]
Once the script is ready, I'll use it to investigate the slow submissions reported by a couple of users.

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/commit/d9602451f37b32ee819aba2c5223153e34bbaddd

Output from looking up training submission 8501017.  Note that the script finds previous submission 8478440 which used the same preprocessing step.
```
8501017 has a preprocessing step docker.synapse.org/syn8282795/sub_1@sha256:b81843fc29aa4451940ade8c619ff8df0eada6e3f94649b72f89a8693f579ed9
	Use docker.synapse.org/syn7887972/8478440/preprocessing@sha256:b81843fc29aa4451940ade8c619ff8df0eada6e3f94649b72f89a8693f579ed9
8501017 has a training step docker.synapse.org/syn8282795/sub_2_training@sha256:4f215d493bcb7330f1dfb0967a5c7ccc6bad51819c54722d6e47ad966218a6e0
	Use docker.synapse.org/syn7887972/8501017/training@sha256:4f215d493bcb7330f1dfb0967a5c7ccc6bad51819c54722d6e47ad966218a6e0
8501017 does NOT have a inference step
8501017 does NOT have a scoring step
```

Output for 8496855:
```
8496855 does NOT have a(n) preprocessing step
8496855 does NOT have a(n) training step
8496855 does NOT have a(n) inference step
8496855 has a(n) scoring step docker.synapse.org/syn7272737/dm_score_quick@sha256:b0308f3afb2744cbab8e68cb617b8452d6ee3169ce86144ab04d09486eb56c2d
	Use docker.synapse.org/syn7887972/8496855/scoring@sha256:b0308f3afb2744cbab8e68cb617b8452d6ee3169ce86144ab04d09486eb56c2d
```
Note that we allow submitters to use the keyword 'inference' or 'scoring' in their submission so we have to check for both.  When the output says "does NOT have an inference step ... has a scoring step"  it's just saying under what tag the result is found.
