### ISSUE TITLE
model state file NA associated with submission NA

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/DigitalMammographyChallenge#735]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1858

**Comment by brucehoff** [comment]
I responded to the OP.  FYI:  The problem is that there's a carriage return between the JSON part and the digital signature which, if omitted, causes the email parser to fail.  The solution is simply for the participant to forward the email we generate without modification.
