### ISSUE TITLE
 Is intermediary logs available?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#739]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1870

**Comment by thomasyu888** [comment]
Is there a way to look at earlier logs?

**Comment by brucehoff** [comment]
@thomasyu888 For training submissions logs are uploaded each half hour.  For scoring submissions logs are not returned.

**Comment by tschaffter** [comment]
@brucehoff I thought that it was every minutes. Can you confirm that it's 30 minutes?

**Comment by brucehoff** [comment]
@tschaffter Yes I can confirm.   To be clear we are talking about how often we upload the *log file*.  We also check each running submission and update it's "last updated" timestamp each *minute*.
