### ISSUE TITLE
Connecting machines to Validation submission queues

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#760]
## Overview

This thread describes what machines to connect to which submissions queues for the launch of the Validation Phase. There are two categories:

- Dry Run Validation
- Challenge Validation

Each category has three submission queues:

- Training
- SC1 Inference
- SC2 Inference

**Note**:
- [ ] The Express Lane stays the same as during the Leaderboard Phase. We should however update the packages on it and update docker (Thomas S. once Bruce says that it's safe to update the machines).

### Training
- /data/data/dm-challenge-dcm/training/*.dcm
- /data/data/metadata/training_exams_metadata.tsv
- /data/data/metadata/training_images_crosswalk.tsv

### SC1 Inference
- /data/data/dm-challenge-dcm/SC1_test/*.dcm
- /data/data/metadata/SC1_test_images_crosswalk.tsv

### SC2 Inference
- /data/data/dm-challenge-dcm/SC2_test/*.dcm
- /data/data/metadata/SC2_test_exams_metadata.tsv
- /data/data/metadata/SC2_test_images_crosswalk.tsv

### Notes
- The agents must give access to the correct files (the keyword "leaderboard" in filenames is replaced by "test")
- The names of the metadata files exposed by the agents to the submissions must be the same than during the Leaderboard. Idea for the path to the directory that include the DICOM images.

## Dry Run Validation
I start with the Dry Run Validation queues because the infrastructure is already in place, however it must be checked and ensure that the agents are running.

**Important**: Dry Run submission queues for internal use only.

### Training
Name: Digital Mammography Model Training Dry Run

- [x] The current name of the queue is "Digital Mammography Model Training Final". Rename it to "Digital Mammography Model Training Dry Run"

Machines:
- bm06
- bm16

### SC1 and SC2 Inference
Names:
- Digital Mammography Prediction - Sub-Challenge 1 Dry Run
- Digital Mammography Prediction - Sub-Challenge 2 Dry Run

- [x] Rename the queues "Digital Mammography Prediction - Sub-Challenge 1 Final" to "Digital Mammography Prediction - Sub-Challenge 1 Dry Run"

Machines:
- p28x20

## Challenge Validation
The following submission queues have been used for the Leaderboard Phase:

- Digital Mammography Model Training
- Digital Mammography Prediction - Sub-Challenge 1
- Digital Mammography Prediction - Sub-Challenge 2

**Questions**:
- Can we reused them (jobs sent to them will be redirected to machines with the Validation dataset) or do we need to create new submission queues (are the Leaderboard tables for Round 1, 2, and 3 linked somehow to a submission queue)?
- Should we use the name queues names than during the Leaderboard Phase or should we add a suffix to the name to make clear that the data behind these queues are different?
- If we reuse existing submission queues, make sure that they are not visible to the participants before the opening of the Validation Phase.

### Training
Name: Digital Mammography Model Training

Machines:
- bm02

**Notes**:
- More machines will be added very soon.
- The above list should not include a machine that is include in the list of machines reported as being slow (Bruce is building the list).

### SC1 and SC2 Inference

Names:
- Digital Mammography Prediction - Sub-Challenge 1
- Digital Mammography Prediction - Sub-Challenge 2

Machines:
- p28x26

### Thomas S.
- [x] Start the Sysdig agents on the Validation Inference machines (Thomas S.). Make sure that the options passed to Sysdig are correct.
  - [x] p28x20 (Dry Run)
  - [x] p28x26
  - [x] p28x27
### Bruce
- [x] Set the agents to use 4 user slots instead of 5.
- [x] Delete the references to existing pre-process data (new training set means that all the participants must redo the pre-processing of the data).
- [x] Check that CloudWatch is running on all the machines.
### Thomas Yu
- [x] Test both Dry Run and Challenge Validation Training/Inference submission queues using the Docker container of the SC2 baseline method. Check that the AUROC and other metrics are identical on both Dry Run/Challenge queues:

Performance using Dry Run queues:
```
AUC:
pAUC:
Specificity at Sensitivity (0.8):
```
Performance using Challenge queues:
```
AUC:
pAUC:
Specificity at Sensitivity (0.8):
```

- [x] Check/complete the section "Submission Queues" with Dry Run/Challenge queue at https://www.synapse.org/#!Synapse:syn5644795/wiki/415850

**Comment by tschaffter** [comment]
Related to #744

**Comment by tschaffter** [comment]
@brucehoff @thomasyu888 Please update this ticket.

**Comment by brucehoff** [comment]
@tschaffter Done!

**Comment by thomasyu888** [comment]
Just waiting for the submission to run on the validation queue then I can check the last 2

**Comment by brucehoff** [comment]
@thomasyu888 Note:  We have no validation machines running right now.  @tschaffter I see on the Cloud Status sheet that you labeled p28x20, p28x26, and p28x27 as "Validation Inference".  Are these set up for the public challenge with the validation inference data set?

**Comment by tschaffter** [comment]
> I see on the Cloud Status sheet that you labeled p28x20, p28x26, and p28x27 as "Validation Inference". Are these set up for the public challenge with the validation inference data set?

@brucehoff Yes

@thomasyu888 Once the above agents are up and running on the above machines, can you please run the SC2 baseline algorithm to verify that we obtain the expected AUC and check the corresponding checkbox? Thanks!

**Comment by brucehoff** [comment]
p28x20, p28x26, and p28x27  are now on-line, running validation submissions.  @thomasyu888 's submission is in progress.

**Comment by thomasyu888** [comment]
Done! They are identical!

**Comment by tschaffter** [comment]
Thanks for your help!
