### ISSUE TITLE
Update Express Lane machines

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#763]
In two batches:
- [x] p28x01 (training) and p28x02 (inference)
- [x] p28x13 (training) and p28x14 (inference)

Tasks:
- update packages
- put dataset on an EFS (inference only)

**Comment by tschaffter** [comment]
@brucehoff p28x01 and p28x02 have been updated. Next are p28x13 and p28x14.

**Comment by tschaffter** [comment]
@brucehoff Bruce, can I update p28x13 and p28x14?

**Comment by brucehoff** [comment]
@tschaffter yes, p28x13 and p28x14 are off line now.

**Comment by tschaffter** [comment]
@brucehoff p28x13 and p28x14 have been updated. Can you please close this ticket once the agents have been restart? Thanks!

**Comment by brucehoff** [comment]
p28x13 and p28x14 are back on line
