### ISSUE TITLE
p28x06 and p28x07: no space left on device

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#766]
```
ubuntu@ip-172-31-59-223:~$ ssh p28x06 df -h
Filesystem                                 Size  Used Avail Use% Mounted on
/dev/xvda2                                 200G  200G   20K 100% /
devtmpfs                                   241G     0  241G   0% /dev
tmpfs                                      240G     0  240G   0% /dev/shm
tmpfs                                      240G  4.2G  235G   2% /run
tmpfs                                      240G     0  240G   0% /sys/fs/cgroup
/dev/mapper/data-inference0                 47M  1.1M   42M   3% /data/inference0
/dev/mapper/data-model0                     21G   45M   20G   1% /data/model0
/dev/mapper/data-model1                     21G  357M   20G   2% /data/model1
/dev/mapper/data-tempDir0                   50G   53M   47G   1% /data/tempDir0
/dev/mapper/data-inference1                 47M  1.6M   42M   4% /data/inference1
/dev/mapper/data-tempDir1                   50G   53M   47G   1% /data/tempDir1
/dev/mapper/data-scratch0                  197G   61M  187G   1% /data/scratch0
/dev/mapper/data-scratch1                  197G   65M  187G   1% /data/scratch1
fs-82cf6ccb.efs.us-east-1.amazonaws.com:/  8.0E  4.2T  8.0E   1% /data/data
tmpfs                                       48G     0   48G   0% /run/user/1000
ubuntu@ip-172-31-59-223:~$ ssh p28x07 df -h
Filesystem                                 Size  Used Avail Use% Mounted on
/dev/xvda2                                 200G  200G   20K 100% /
devtmpfs                                   241G     0  241G   0% /dev
tmpfs                                      240G     0  240G   0% /dev/shm
tmpfs                                      240G  4.2G  235G   2% /run
tmpfs                                      240G     0  240G   0% /sys/fs/cgroup
/dev/mapper/data-inference1                 47M  1.9M   41M   5% /data/inference1
/dev/mapper/data-model1                     21G   45M   20G   1% /data/model1
/dev/mapper/data-model0                     21G   45M   20G   1% /data/model0
/dev/mapper/data-tempDir1                   50G   53M   47G   1% /data/tempDir1
/dev/mapper/data-tempDir0                   50G   53M   47G   1% /data/tempDir0
/dev/mapper/data-scratch0                  197G   61M  187G   1% /data/scratch0
/dev/mapper/data-scratch1                  197G   64M  187G   1% /data/scratch1
/dev/mapper/data-inference0                 47M  1.8M   41M   5% /data/inference0
fs-82cf6ccb.efs.us-east-1.amazonaws.com:/  8.0E  4.2T  8.0E   1% /data/data
tmpfs                                       48G     0   48G   0% /run/user/1000

# for comparison

ubuntu@ip-172-31-59-223:~$ ssh p28x03 df -h
Filesystem                                 Size  Used Avail Use% Mounted on
/dev/xvda2                                 200G   49G  152G  25% /
devtmpfs                                   241G     0  241G   0% /dev
tmpfs                                      240G     0  240G   0% /dev/shm
tmpfs                                      240G  138M  239G   1% /run
tmpfs                                      240G     0  240G   0% /sys/fs/cgroup
/dev/mapper/data-inference1                 47M  2.6M   41M   7% /data/inference1
/dev/mapper/data-tempDir0                   50G   53M   47G   1% /data/tempDir0
/dev/mapper/data-tempDir1                   50G   53M   47G   1% /data/tempDir1
/dev/mapper/data-model1                     21G   45M   20G   1% /data/model1
/dev/mapper/data-scratch0                  197G   61M  187G   1% /data/scratch0
/dev/mapper/data-scratch1                  197G   61M  187G   1% /data/scratch1
/dev/mapper/data-inference0                 47M  1.2M   42M   3% /data/inference0
/dev/mapper/data-model0                     21G   45M   20G   1% /data/model0
fs-4b1eba02.efs.us-east-1.amazonaws.com:/  8.0E  4.2T  8.0E   1% /data/data
tmpfs                                       48G     0   48G   0% /run/user/1000
```

**Comment by brucehoff** [comment]
@tschaffter Is it expected that the 200GB share would fill up?  Do we have a clean up script that removes old containers and images as the shares get full?

**Comment by tschaffter** [comment]
@brucehoff Docker images are taking all the space. The cleanup script is there. If it was not able to clean, maybe we have again the issue where the agents were creating duplicates of the images that was unremovable because not "dangling"?

We have to take p28x06 and p28x07 offline because the system won't even let me delete files because no more space available. We also don't know the effect that this issue could have on the containers.

- 8503967.p28x06-1.SCORE_SC_1.SCORING
- 8504010.p28x07-2.SCORE_SC_2.SCORING

**Comment by brucehoff** [comment]
> We have to take p28x06 and p28x07 offline because the system won't even let me delete files 

I was hoping to avoid this, as we will lose four submissions.  8509096 is actually *done*, it's just that the agent can't finish up.

I've deleted a bunch of log files on p28x06 but it doesn't seem to free up any space.  (From what I've read on-line this may happen if a process still has a lock on a deleted file.)

> We also don't know the effect that this issue could have on the containers.

If the submissions haven't crashed then can't we assume that they are still healthy?

**Comment by brucehoff** [comment]
Here's the % use of the 200GB root volume on each of the machines used for inference submissions:
p28x03 25%
p28x05 100%
p28x06 100%
p28x07 100%
p28x09 9%
p28x10 14%
p28x11 15%
p28x12 13%
p28x16 100%
p28x22 100%
p28x24  9%
p28x34 16%
p28x35  14%
p28x36 100%

**Comment by tschaffter** [comment]
```
p28x16:

172G	/var/lib/docker/containers/f8c7b898566900485f5ef3a9ca411c37d599220cf12a3c11be19cd2156a5360e
8504018.p28x16-1.SCORE_SC_1.SCORING

p28x22:

169G	/var/lib/docker/containers/37cc52ffdb6a73629fc6f1af40a1e73cabcbcd1ba1d4c22b0f7285abb4c8bc44
8503938.p28x22-2.SCORE_SC_2.SCORING

p28x36:

184G	/var/lib/docker/containers/a4e3a20a196a17307182a098f2b37837bdbd9fbf52f4db26e5644eb691c8f235
8503970.p28x36-2.SCORE_SC_2.SCORING
```

**Comment by brucehoff** [comment]
I stopped the agents on the six affected machines, since they will have to be cleaned up before continuing.

**Comment by tschaffter** [comment]
@brucehoff The next step for me will be to reset the following six machines once we have done everything you wanted to do.

```
p28x05 100%
p28x06 100%
p28x07 100%
p28x16 100%
p28x22 100%
p28x36 100%
```

**Comment by brucehoff** [comment]
I restarted the three submissions *paired* with (affected by) the problematic submissions:
"8503119", "8509096", "8505126"
Since we have four free slots (one each on p28x03, p28x12, p28x24, and p28x34) they will start running immediately.
I also captured the predictions.tsv file from 8509096, just in case.  (To be careful we are simply rerunning all the affected submissions.)
@tschaffter At this time there is nothing more to do with the six affected machines.  You are free to reset them.

**Comment by brucehoff** [comment]
@tschaffter I have changed the challenge agent to limit the size of the collected log files and am ready to restart Peter Brooks' submissions.  We just need to start three more machines for this purpose.  If you are in the process of resetting the six affected machines, then I will wait for you to tell me they are ready and I will start the agents to run Peter's submissions.

**Comment by tschaffter** [comment]
@brucehoff I will not have the time to reset the six machines today so it's better to restart the submissions right now on different machines.

**Comment by brucehoff** [comment]
Very well.  I will bring back on line:
p28x04
p28x08
p28x25

**Comment by brucehoff** [comment]
All submissions have been restarted elsewhere.  I'll leave this issue open just for the remaining task of cleaning up the six affected machines.

**Comment by brucehoff** [comment]
One last thing:  We want to make sure that no other submissions run on the affected servers failed due to running out of disk space.  I checked all submissions run on SC1 or SC2 on each of the six servers, looking for submissions that failed after 3/21 (though we actually believe the disk didn't fill until 3/28-29).  I found three submissions, but none seem to have failed due to lack of disk space:
8501900 on p28x05 (ran out of memory)
8508718 on p28x16 (looks like a software bug)
8508740 on p28x16 ("Could not open file /modelState/caffe_googlenet_iter_50000.caffemodel")

**Comment by tschaffter** [comment]
> I found three submissions, but none seem to have failed due to lack of disk space

This is a good news!

**Comment by tschaffter** [comment]
@brucehoff I terminated the following six machines that had their filesystem full.

```
p28x05 100%
p28x06 100%
p28x07 100%
p28x16 100%
p28x22 100%
p28x36 100%
```

I don't think there is a need to instantiate these machines again. I've removed them from the Cloud Status document.

https://docs.google.com/document/d/1loa8Y2hU6zhvN_lC_csSxL2_pm-4oVnvUYn41E647VY/edit#

**Comment by brucehoff** [comment]
Just realized that what we need is disk space monitoring.  Reopening until we do this: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/mon-scripts.html

**Comment by brucehoff** [comment]
Here are tools for pushing disk usage and memory to CloudWatch: 
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/mon-scripts.html

**Comment by brucehoff** [comment]
I just checked the machines re-running the problematic submissions and am happy to report that their root volumes are not filling up:
p28x08 - 6%
p28x15 - 6%
p28x34 - 17%

**Comment by tschaffter** [comment]
@brucehoff Thanks for the update!
