### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#78]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1135

**Comment by thomasyu888** [comment]
He provided a log file of his output, and there are still errors.  Im not completely sure that I understand what is going on, because he is using the exact same folder that he uploaded and unzipped to build the docker container

**Comment by brucehoff** [comment]
His session is truncated, so you can't see what he actually did.    I think you asked the right question, asking for him to "ls -al" in the build directory.

**Comment by thomasyu888** [comment]
This problem is related to the nvidia-docker version. The problem goes away when docker is restarted by:
 ```
sudo service docker restart
 ```
There is a thread about this error here:
https://github.com/docker/docker/issues/25925

**Comment by brucehoff** [comment]
> Should this be documented somewhere?

Can you please coordinate with Thomas Schaffter who had taken the lead on writing user documentation.

**Comment by thomasyu888** [comment]
I added this in the documentation here https://www.synapse.org/#!Synapse:syn4219927/wiki/406528
