### ISSUE TITLE
extremely slow docker upload

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#793]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1969

**Comment by tschaffter** [comment]
Has Synapse experienced bandwidth issues?

**Comment by brucehoff** [comment]
@thomasyu888 You can ask him to push to DockerHub and see if it's faster.  If it is, and if the Synapse problem persists, then he can simply share his DockerHub image with the DockerHub user 'dreamchall' and reference that image in his submission.
