### ISSUE TITLE
enhance precondition checking in challenge agent

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#795]
Instead of checking the if the directory/file exist on the host, the agents could check the following for each sub-challenge specified:
- the mounted images directory is not empty
- the mounted files are files (docker always mount empty *directory* if the file doesn't exist on the host)

**Comment by tschaffter** [comment]
@brucehoff Has this enhancement been implemented?

**Comment by brucehoff** [comment]
@tschaffter This has not yet been done.  Is it still needed?

**Comment by tschaffter** [comment]
@brucehoff No, I'm fine closing it. Thanks!
