### ISSUE TITLE
 cancel these inference submissions

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#812]

**Comment by brucehoff** [comment]
cancel these two inference submissions that are currently evaluating:  9604831 and 9604832?

**Comment by brucehoff** [comment]
Step 1: Find the submission here: https://www.synapse.org/#!Synapse:syn5644795/wiki/416394
Step 2: Find the WORKER_ID, e.g. it's 	p28x30-1 for 9604831 and p28x33-2 for 9604832.
Step 3: `ssh ubuntu@52.204.173.232`
Step 4: `eval $(docker-machine env p28x30)`
      (replace p28x30 with the prefix of the worker ID from Step 2)
Step 5: `docker ps`
     Look for the container name containing the submission ID of interest.  There should be only one.
Step 6: docker stop <container name>
     E.g. `docker stop 9604831.p28x30-1.SCORE_SC_1.SCORING`
Step 7: Return to the page used in Step 1 and check that the submission(s) are now marked INVALID.

**Comment by thomasyu888** [comment]
To be specific, `eval $(docker-machine env p28x30-1)`?

**Comment by brucehoff** [comment]
@thomasyu888 No: `eval $(docker-machine env p28x30)`

**Comment by thomasyu888** [comment]
Ok. Thanks for clarifying

**Comment by thomasyu888** [comment]
Can we leave this open so I have the instructions to reference to
