### ISSUE TITLE
run copies of remaining validation inference submissions

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#824]

**Comment by brucehoff** [comment]
On May 9 we decided that to mitigate the risk of one of the remaining, long running inference submissions failing and delaying the close of the competitive challenge, we would run a second copy of each of the remaining submissions.  As of May 10 there are 8 such submissions.  The entity ID and version of each is:
SC-1:
syn9639731     7
syn9632916     1
syn7899011     1

SC-2:
syn7899011     1
syn9726819     4
syn8073639     1
syn9632916     1
syn9726915     1

We will restart the challenge agents on bm19, bm20, bm22 and bm23 then submit these 8 submissions.

**Comment by tschaffter** [comment]
@brucehoff We should restart the submissions on a different submission queue. It's easier to run the submissions on the correct machines and easier to extract the results from the challenge. The resubmitted submissions should not be visible to the participants.

**Comment by brucehoff** [comment]
@tschaffter Good idea.

Here's an R script that will create the submissions:
```
library(synapseClient)
synapseLogin() # use admin credentials
sc1Eval<-synGetEvaluation("8533482") # or replace with new queue
file<-synGet("syn9639731", version=7, downloadFile=F)
submit(sc1Eval, file, "duplicate of 9604253")

file<-synGet("syn9632916", version=1, downloadFile=F)
submit(sc1Eval, file, "duplicate of 9605465")

file<-synGet("syn7899011", version=1, downloadFile=F)
submit(sc1Eval, file, "duplicate of 9604644")


sc2Eval<-synGetEvaluation("8533484")  # or replace with new queue

file<-synGet("syn7899011", version=1, downloadFile=F)
submit(sc2Eval, file, "duplicate of 9605342")

file<-synGet("syn9726819", version=4, downloadFile=F)
submit(sc2Eval, file, "duplicate of 9606702")

file<-synGet("syn8073639", version=1, downloadFile=F)
submit(sc2Eval, file, "duplicate of 9607576")

file<-synGet("syn9632916", version=1, downloadFile=F)
submit(sc2Eval, file, "duplicate of 9606640")

file<-synGet("syn9726915", version=1, downloadFile=F)
submit(sc2Eval, file, "duplicate of 9606705")

```

**Comment by tschaffter** [comment]
> easier to extract the results from the challenge

Actually it's not really relevant.

**Comment by brucehoff** [comment]
To start the agents I ran
```
./updateAgents.sh score ./dmagent-duplicateValidation.sh bm19 bm20 bm22 bm23
```
where `dmagent-duplicateValidation.sh` is a copy of dmagentprod.sh replacing the evaluation IDs with the new, isolated ones.
