### ISSUE TITLE
write-up validator fails

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#832]
Per @tschaffter:
```
The following action must be taken by you or Tom asap: run the validator on 9612960, 9612961,9613098 (previous processing of these submissions by the validator led them to be evaluated as INVALID due to the permission issue reported). The expected output is to have the status of the submissions 9612960, 9612961,9613098 VALIDATED and the submissions archived.```

**Comment by brucehoff** [comment]
The submissions can be seen here:
https://www.synapse.org/#!Synapse:syn5644795/wiki/427127
There are 13 "invalid" submissions, including the three cited in the original issue.

**Comment by brucehoff** [comment]
In @thomasyu888 's May 13 email he says:
```
I set up the write-up archiver on machine bm23.

The command I ran is:

docker run --name archiveWriteup --restart=unless-stopped -d -e SYNAPSE_USERNAME=$SYNAPSE_USERNAME -e SYNAPSE_PASSWORD=$SYNAPSE_PASSWORD -e CHALLENGE_NAME=DMthomasvyu/dm-challenge-writeup-copytool /runTool.sh

Looking here:
https://hub.docker.com/r/thomasvyu/dm-challenge-writeup-copytool/
we can see that the source code is here:
https://github.com/Sage-Bionetworks/DM-Challenge-Writeup-Copytool
```

**Comment by brucehoff** [comment]
I cloned the source code repo to have a look in my IDE.  I see this function:
```
def validate_submission(syn, evaluation, submission, public=False, admin=None):
    """
    Find the right validation function and validate the submission.

    :returns: (True, message) if validated, (False, message) if
              validation fails or throws exception
    """
    try:
        if public:
            ent = syn.getPermissions(submission['entityId'])
            assert "READ" in ent and "DOWNLOAD" in ent, "Please share your private directory (%s) with the `Public` with `Can Download` permissions." % submission['entityId']
        if admin is not None:
            ent = syn.getPermissions(submission['entityId'], admin)
            assert "READ" in ent and "DOWNLOAD" in ent, "Please share your private directory (%s) with the `Public` with `Can Download` permissions." % submission['entityId']            
    except SynapseHTTPError as e:
        if e.response.status_code == 403:
            raise AssertionError("Please share your private directory (%s) with the Synapse user `%s` with `Can Download` permissions." % (submission['entityId'], admin))
        else:
            raise(e)
    return True, "Validated!"
```

**Comment by brucehoff** [comment]
I did the following in Python:
```
>>> import synapseclient
>>> syn = synapseclient.Synapse()
>>> syn = synapseclient.login("dmchallengeit", "xxxxx")
Welcome, DM Challenge IT!

>>> submission=syn.getSubmission("9612960")
>>> ent = syn.getPermissions(submission['entityId'])
>>> ent
[]
>>> ent = syn.getPermissions(submission['entityId'], False)
>>> ent
[]
>>> ent = syn.getPermissions(submission['entityId'], True)
>>> ent
[]
```
So, for some reason 'getPermissions' isn't returning anything.

**Comment by brucehoff** [comment]
The instructions for submission are here https://www.synapse.org/#!Synapse:syn4224222/wiki/426788:
```
Share your private directory with the Synapse user dmchallengeit with Can Download permissions.
```
This explains why validation doesn't work:  Participants share their project with 'dmchallengeit' but the validation script is checking that they made their project public.

What is unclear is why *any* submission passed validation.  For example, 9610593 passed, though the submitted project, syn9819678, is not public.  Perhaps the submitter made their project public and then switched it back after submitting.

**Comment by thomasyu888** [comment]
If you look in the shell script. There is a --admin parameter i pass in. Please look closely in the config python file again... Notice there is a if admin is not None.... The way this challenge is set up, it goes into there and does syn.getPermissions(entId, myuserprofId)

**Comment by thomasyu888** [comment]
Sorry about the confusion... Im not entirely sure why this is failing. My only thought it that she has actually not shared it..

**Comment by thomasyu888** [comment]
Please notice this in the python script runWriteuptool.py in that repo


        validateSub = ['python','challenge.py','--challengeName',chalName,'-u',synUser,'-p',synPass,'--send-messages','--notifications','--acknowledge-receipt','validate','9603284','--admin','3336298

**Comment by thomasyu888** [comment]
An easy solution is to check if you can actually access the page with the account dmchallengeit. Sorry but I will be offline now...

**Comment by brucehoff** [comment]
I changed the code to check that `dmchallengeit`, not Public has access:
https://github.com/Sage-Bionetworks/DM-Challenge-Writeup-Copytool/commit/158bd0fdb8433dd6ecd0befb272ce76849935f37

**Comment by brucehoff** [comment]
@thomasyu888:
```
There is a --admin parameter i pass in.
...
Please notice this in the python script runWriteuptool.py in that repo
```
OK, I see.  There does not seem to be a bug in your code.  I will undo the Github commit I did earlier.

```
My only thought it that she has actually not shared it..
```
In at least one case which I have checked she did, indeed share it.

**Comment by brucehoff** [comment]
There is clearly an error is the message returned to the user:   When the code checks that you have shared with 'admin', if the check fails then it says 
``
Please share your private directory (...) with the `Public`
``
when it should instead say
``
Please share your private directory (syn5195038) with the Synapse user `dmchallengeit`
``

I changed the code here:

https://github.com/Sage-Bionetworks/DM-Challenge-Writeup-Copytool/commit/67f9c49154025d7c69497ca0a79d6ef7910e2220

**Comment by brucehoff** [comment]
I changed the status of submission 9613098 (one of the three listed by Thomas) from INVALID to RECEIVED, reran the validator and saw it change from RECEIVED to VALIDATED.  It's still running though (presumably mirroring the submitted project), so I have to verify that the process doesn't change the submission status again.

**Comment by tschaffter** [comment]
I updated the spreadsheet with the latest write-up validated for Yuanfang.

**Comment by brucehoff** [comment]
I verified that 9613098 is VALIDATED when the validation process finished.  I then reset the remaining two submissions (9612960, 9612961)  reran the validator, and checked that they are now VALIDATED.  The validator archived Yuanfang's project here: https://www.synapse.org/#!Synapse:syn9893180/wiki/432071  Thus the requirements in the issue have been met.
