### ISSUE TITLE
Fixing SC2 baseline methods

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#835]
The Docker image of the SC2 baseline submission referenced in the Validation Leaderboard does not follow the format defined for the predictions files.

Because the Dockerfile of the image is not available to me right now (Tom is off), I've built the following docker image from the archived image and Elias R script:

```
FROM docker.synapse.org/syn7887972/9611321/scoring@sha256:a7f320def8ddbcf84df14979f5cbc8fa96ab6f8fbbcbd2acb07c15d536cd265a
WORKDIR /
COPY age_baseline_sc2_for_tom_5_17_2017.R age_baseline_sc2.R
```

I fixed an error included in the R script where the confidence level is divided by maxAge, which is the maximum age value among all the test subjects. This violates the rule that the predictions for one subject must not depend on the data from other test subject. I replaced maxAge by 89, which is the largest value that can be found in the training set (and in the entire Group Health dataset).

I pushed the new image to the Dry Run project:

```
docker push docker.synapse.org/syn5644795/age_baseline_sc2
```

@echaibub @brucehoff There are two options which you may take from there.

### Quick and dirty
I'm confident that the patched image is now OK. You may take it as well as the patched predictions files sent by email by email and tweak the annotation of the submission entry in the leaderboard to patch it (docker image, archived image, prediction file). This option is only valid if Elias confirms that the change in the predictions file format does not affect the AUC, pAUC, and SpecAtSens associated to the current submission.

### Slow but proper way
Resubmit the patched image to the evaluation queue, run it against the entire dataset, and reassociate the write-up to this new submission.

**Comment by thomasyu888** [comment]
Patched
