### ISSUE TITLE
Submissions limit

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#842]
The following information needs to be defined and configured.

- Maximum number of scoring submission
- Maximum amount of data (log file + trained model) that can be retrieve during the three month of the collaborative phase

I'll post the information below once defined.

**Comment by thomasyu888** [comment]
Set the quota of submissions to 3

**Comment by tschaffter** [comment]
For the data quota (once you have figured out how it works with Burce), set the limit to 30 GB. We will increase it the 1st of every month (30 GB / month). You can close this ticket once the limit is set for this month.

**Comment by brucehoff** [comment]
Note:  Here's how the limits are set:

Maximum number of scoring submission: This is a property of the submission queue.  Some references:
http://docs.synapse.org/python/Evaluation.html#evaluation
http://docs.synapse.org/rest/org/sagebionetworks/evaluation/model/SubmissionQuota.html

Maximum amount of data (log file + trained model) that can be retrieve[d]:

The max is controlled by an environment variable DATA_QUOTA_PER_ROUND_GB, which defaults to 28 as shown here:
https://github.com/Sage-Bionetworks/ChallengeDockerAgent/blob/master/src/main/resources/global.properties

You can check in a change to the default via git OR pass in an override via Docker.

You also have to set the round start and round end dates (ROUND_START_DATE_TIME, ROUND_END_DATE_TIME), both in the challenge agents and in the 'model state unlocker' container.  You can see the current settings in the start up shell scripts:
 
https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/blob/master/dmagent_core.sh

https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/blob/master/modelstateunlocker.sh

**Comment by brucehoff** [comment]
@tschaffter Please confirm that the max number of inference submissions should be three per round.  Can you also say what the end dates are for the rounds (or for the whole collab phase if there is just one, big round) and whether the limits are multiplied by the number of inference data sets?

**Comment by tschaffter** [comment]
There are no longer "rounds". We have decided to not limit the number of scoring submission that the participants can make. They are qualified enough to prevent overfitting. However, please set an initial limit to 20 submissions for each inference queue (for now only Group Health is up and running) so that we are alerted once a team bump into it.

**Comment by tschaffter** [comment]
If you need to set an end dates for the collaborative phase, you can put October 15.

**Comment by thomasyu888** [comment]
Quota is set for 20 now, we can just close the queues on the 15th of Oct.
