### ISSUE TITLE
Review Docker container cleanup script

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#843]

**Comment by tschaffter** [comment]
I've written a python script that cleanup docker containers and images when the data space available is less than specified (e.g. 20 GB). First, the script remove all stopped container whose docker image is not in a list specified. This feature is used to protected stopped agents from the image "brucehoff/challengedockeragent" to be removed so that if needed we can still access the logs of the stopped agents. Finally, all images that are not used by a running container are removed.

@thomasyu888 Can you confirm that agent containers are still run from the Docker image "brucehoff/challengedockeragent"?

**Comment by tschaffter** [comment]
@brucehoff Does the above logic seems fine to you? Is there a need to implement a timeout so that containers that have been stopped less than X minutes ago should not be removed?

**Comment by thomasyu888** [comment]
Yes, they are still run from "brucehoff/challengedockeragent"

**Comment by tschaffter** [comment]
The machines have a new cleanup script installed.

**Comment by brucehoff** [comment]
> Does the above logic seems fine to you? Is there a need to implement a timeout so that containers that have been stopped less than X minutes ago should not be removed?

Yes, that's the one issue that occurred to me:  There is a delay between when a container stops and when the server-side agent completes its work, e.g. collecting the container's log files.  The clean up script should not delete containers that have not yet been handled.  

Here is one way to avoid cleaning up containers that are still being used:  When the agent is done with a container is changes the name, prepending "archive.".  If you only clean up containers with such prefixes then there should not be any conflicts.

**Comment by tschaffter** [comment]
@brucehoff The issue with cleaning up containers that match a criterion (name starts with "archive.") is that I'm afraid that we will miss containers that haven't been renamed for reason X or Y (e.g. due to an error). Over time this may result in the Docker data space to become full and Docker to crash. The cleanup script installed does not remove containers that have been stopped for less than A minutes (command-line arguments set to 20). Also, cleanup is performed only if there is less than B GB of available data (command-line arguments set to 20)  Do you think that this approach is good enough?

**Comment by brucehoff** [comment]
> Do you think that this approach is good enough?

Yes, it will probably work.  We can try it and see how things go, and adjust as needed.
