### ISSUE TITLE
Capture usage metrics

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#844]
In the Validation Phase, I've had a script running on the machines that was collecting usage metrics (CPU used, memory used, GPU memory used, etc.) for each submissions running + health of the servers.

- [ ] Modify the script to push the metrics to a database instead of saving to file
- [ ] Implement a REST API so that team can track the metrics for their submissions (progress, CPU used, etc.)

**Comment by tschaffter** [comment]
I'm configuring an instance on AWS for the database and the REST API.

**Comment by tschaffter** [comment]
@brucehoff Assuming that there are N agents running on a machine, can you confirm that the first agent will attribute the first X/N GPUs to the container it runs (X = total number of GPUs), the second agent will attribute the following X/N GPUs, etc. where the GPUs are ordered based on their listing as `/dev/nvidiaX`?

**Comment by brucehoff** [comment]
@tschaffter Agents don't have any particular logic for allocating GPUs, they use all GPUs for which they are configured to run the one job they are executing.  Currently this is 'hard coded' in a very simple way:  Agent No. 1 used GPUs 0 and 1, Agent No. 2 uses and 3. Please see lines 26 and 37 here: https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/blob/master/dmagent_core.sh

**Comment by tschaffter** [comment]
@brucehoff OK. Please keep the same GPUs order convention when running more agents per machines.

1 agent: GPU 0-3
2 agents: GPU 0-1 (agent 1) and GPU 2-3 (agent 2)
4 agents: GPU i-1 (agent i)

**Comment by tschaffter** [comment]
The script collecting CPU, memory, GPU, etc. is parsing the name of a container to determine if its a submission, in which case data are collected for it and pushed to a database.

Example of container name: 9605233.bm23-1.SCORE_SC_1.SCORING

The information extracted from the name of the container are the submission ID, the index of the agent, the submission queue (TRAIN, SCORE_SC_1, SCORE_SC_2) and the type of submission (PREPROCESS, TRAIN, SCORE).

@brucehoff @thomasyu888 Can you confirm that the name of the container follow the same logic in the collaborative phase and use the same values?

**Comment by brucehoff** [comment]
@tschaffter The container naming convention has not been changed since the competitive phase.

**Comment by tschaffter** [comment]
Done
