### ISSUE TITLE
Inference submissions generates two predictions files in the Collaborative Phase

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#845]
In the competitive phase, inference submissions were generating the breast-level predictions file `/output/predictions.tsv`.

In the collaborative phase, we are asking participants to generate predictions at the breast and exam level. The change must continue to allow submissions from the competitive phase to run on the collaborative infrastructure. Therefore, the breast-level predictions file is still named `/output/predictions.tsv`. Collaborative participants will be asked to save their exam-level predictions in the file `/output/predictions_exams.tsv`.

Regarding the evaluation of the predictions file, the gold standard at the exams level can be obtained by contacting Thomas Schaffter. Submission from the competitive phase must still be able to be evaluated, i.e. even if the exam-level predictions file is not generated. If the exam-level predictions file exists, evaluate it use the corresponding gold standard. The same leaderboard table must display evaluation at the breast and exam level.

**Comment by brucehoff** [comment]
Duplicates https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/852
