### ISSUE TITLE
Create Collaborative leaderboard

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#847]
Collaborative teams will evaluate their submissions on different dataset. During this phase, they will be evaluated on so called "leaderboard" sets. The final validation will be done on the "validation" sets.

Group Health leaderboard: https://www.synapse.org/#!Synapse:syn9935146/wiki/450008
MSSM leaderboard: https://www.synapse.org/#!Synapse:syn9935146/wiki/450009
Karolinska leaderboard: https://www.synapse.org/#!Synapse:syn9935146/wiki/450010

On each of the above pages, create two tables:
1. A table that lists the best submission from each team
2. A table that lists all the scored submissions on the given dataset

In a first time, only Group Health dataset will be available for training and scoring.

**Comment by tschaffter** [comment]
@thomasyu888 I'm reopening the ticket as the format of the table is not yet final.

**Comment by thomasyu888** [comment]
What needs to be added to the table?

**Comment by thomasyu888** [comment]
Ok.  Keep me posted and we can add to the tables.

**Comment by tschaffter** [comment]
@thomasyu888 The leaderboard table does not show yet AUC, etc.

**Comment by thomasyu888** [comment]
It does:

Group health: https://www.synapse.org/#!Synapse:syn9935146/wiki/454831
Mt Sinai: https://www.synapse.org/#!Synapse:syn9935146/wiki/454830

**Comment by tschaffter** [comment]
@thomasyu888 What sensitivity do you use when computing the specificity?

**Comment by thomasyu888** [comment]
Unchanged from competitive phase. 0.8

**Comment by tschaffter** [comment]
We are now interested at the specificity at fixed sensitivity 0.87. Can you:

- make the change in the scoring script.
- add the notes

AUC: Area under the Receiver Operating Characteristics Curve.
pAUC: Partial AUC.
SpecAtSens: Specificity at fixed sensitivity 0.87.
inTeamRanking: Ranks from 1 to the number of submissions made by a given team.

**Comment by tschaffter** [comment]
@thomasyu888 
- [ ] Add the description of the columns provided above
- [ ] Make Mount Sinai leaderboard table looks the same as Group Health table

GH: https://www.synapse.org/#!Synapse:syn9935146/wiki/454831
MS: https://www.synapse.org/#!Synapse:syn9935146/wiki/454830

- [ ] Deszo and Yuanfang have successfully scored on the Mount Sinai dataset, however the following table doesn't show information about how many times a team has scored on Mount Sinai dataset.

https://www.synapse.org/#!Synapse:syn9935146/wiki/450007

**Comment by thomasyu888** [comment]
The Mt. Sinai Leaderboard and Group Health table use different Synapse Infrastructure.  The Mt. Sinai Leaderboard uses the Synapse leaderboard tables (because there is only one queue), while the other uses Synapse tables (Combined from all the queues). They display the same information, it just looks different.

**Comment by tschaffter** [comment]
@thomasyu888 Welcome back!

Mount Sinai table is missing the column "inTeamRanking". Is there no straight forward way to forward Mount Sinai queue to provide the same search features as those proposed for Group Health dataset?

**Comment by thomasyu888** [comment]
I added the column into the Mount Sinai table. Should look the same now.

**Comment by tschaffter** [comment]
Thanks!
