### ISSUE TITLE
Allow 1, 2 or 4 agents per machine

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#849]
In the DM Challenge a server 'agent' controls a set of exclusive resources on a server and runs one submissions at a time.  This is how we ensure a submission has exclusive access to resources and does not "collide" with other submissions.

In the competitive phase we had 2 agents per server.  The logic for setting up an agent's resources is on lines 24-50 here: https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/blob/master/dmagent_core.sh

So this needs to be updated to reflect not just the agent index but also the total number.  That is, currently the agent is 1of2 or 2of2 (where the "of2" is implicit), but the logic needs to allow 1of1, 1of2, 2of2, 1of4, 2of4, 3of4, or 4of4.

Need volumes set up on host for 'scratch' space and model state (see ll. 55-58).  

Line 156 specifies 200GB RAM per agent, but that amount must be reduced if there are four agents running.

The 'updateAgents.sh' script assumes 2 agents and needs to be made more general:  https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/blob/master/updateAgents.sh

@tschaffter Would you care to specify what resources (GPU, CPU, memory) should be available for 1, 2, or 4 agents and communicate it to the participants?

@thomasyu888 Would you update the various shell scripts as needed?

**Comment by tschaffter** [comment]
@brucehoff The configuration (CPU, GPU, memory) are defined here: https://www.synapse.org/#!Synapse:syn9935146/discussion/threadId=2162. I'll send an email tomorrow to the participants with additional information about dataset and resources.

All machines have four pre-processed data partitions (8 TB each). I've just made a change on bm13 and bm14 (DeepHealth Mammography): they now have four scratch partitions.

**Comment by tschaffter** [comment]
The 16 machines setup for the collaborative phase (bm07-bm23 but not bm16) have four scratch partitions each. In terms of resources, these machines (and future ones) are ready to run 4 agents.

**Comment by brucehoff** [comment]
Per Bill Lotter:
```
If it's a pain and I'm the only one using the alternative configuration, I'm fine using the standard approach. No problem at all. 
```
So I wonder if we need this at all.

**Comment by tschaffter** [comment]
I'm OK if you decide to give him the default configuration.
