### ISSUE TITLE
Keep track of two predictions files instead of one

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#852]
Keep track of two predictions files instead of one:
- breast-level predictions: /output/predictions.tsv (same name as in the competitive phase so that submissions in the competitive phase are still compatible)
- exam-level predictions: /output/predictions_exams.tsv

Tom can use the breast-level gold standard to define the exam-level gold standard (exam is positive if at least one breast is positive). Tom already has the gold standard for Group Health Leaderboard Inference set.

**Comment by brucehoff** [comment]
Here's the code change:
https://github.com/Sage-Bionetworks/ChallengeDockerAgent/pull/23

**Comment by brucehoff** [comment]
The challenge docker image is now updated with the necessary change.  After running an inference submission a zipped archive is uploaded to Synapse.  (This is as before.)  Instead of containing just the predictions.tsv file, the archive will have both the specified files.

**Comment by tschaffter** [comment]
> Tom can use the breast-level gold standard to define the exam-level gold standard (exam is positive if at least one breast is positive). Tom already has the gold standard for Group Health Leaderboard Inference set.

Is this also implemented?

**Comment by brucehoff** [comment]
> Is this also implemented?

Seems like a separate issue.   https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/854

**Comment by tschaffter** [comment]
OK
