### ISSUE TITLE
Update the way inference submissions are scored

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#853]
- do not longer add missing predictions as done in the competitive phase
- use only the part of the gold standard for which predictions have been submitted. This is to enable participants to do internal experiments where they don’t need to make predictions for all the negative exams

In the leaderboard tables, report:
- breast level
  - AUC
  - pAUC
  - spec at sens (may be redefined but no idea yet)
  - num breasts in prediction files / num breasts in gold standard
- exam level
  - AUC
  - pAUC
  - spec at sens
  - num exams in prediction files / num exams in gold standard

We want that containers submitted during the competitive phase can still be used in the collaborative phase. Therefore a submission that generates only predictions at the breast level must be accepted.

**Comment by thomasyu888** [comment]
num breasts = len(set(subjectId + laterality))
num exams = len(set(subjectId))
