### ISSUE TITLE
compute metrics at exam level

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#854]
Per @tschaffter 

> use the breast-level gold standard to define the exam-level gold standard (exam is positive if at least one breast is positive). Tom already has the gold standard for Group Health Leaderboard Inference set.

**Comment by tschaffter** [comment]
@thomasyu888 The following validation would make sense:

If exam-level predictions are provided, check that the unique subjectId listed in the exam-level predictions file are the same as the unique subjectId listed in the breast-level predictions file. If not, reject the submission.

That way, we have only to compute and report in the leaderboard table length(unique(subjectId + laterality)) in the prediction files / length(unique(subjectId + laterality)). If the above validation is performed, there is no need to compute this ratio for the exam-level predictions.
