### ISSUE TITLE
Submissions working?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#872]
https://www.synapse.org/#!Synapse:syn9935146/discussion/threadId=2216

**Comment by brucehoff** [comment]
@thomasyu888 I see you assigned this to me.  Could you do some investigation first?  For example find out if they actually submitted something, what is its disposition, are the agents running on their machine, etc.?

**Comment by tschaffter** [comment]
@brucehoff @thomasyu888 Kiko is constantly coming back to have write access to /preprocessedData and complain with the rigidity of the strategy implemented regarding pre-processed data. I've made suggestions to allow participants to have more than one pre-processed data copy (#836) and allow participants to generate to update an existing pre-processed data copy and save the output to another pre-processed data storage (#837). Please provide support to Kiko.

**Comment by brucehoff** [comment]
> Please provide support to Kiko.
We are doing so by fulfilling #836
