### ISSUE TITLE
About submission...

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#874]
https://www.synapse.org/#!Synapse:syn9935146/discussion/threadId=2225

**Comment by tschaffter** [comment]
Bruce: Can you take care of this item since you have the pre-processing pipeline fresh in your mind as you are working on it? Thanks!

**Comment by brucehoff** [comment]
@tschaffter  I do not understand what is being requested.  Is our guide to creating submissions (including preprocessing) not complete?

**Comment by tschaffter** [comment]
@brucehoff I believe it is.

@thomasyu888 Please check with him and close this ticket if he got the information required in the meanwhile.
