### ISSUE TITLE
Table that tells how many times a teams has scored against a dataset

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#875]
The goal is to keep track of the number of times a teams a successfully scored against a given leaderboard set. For each one of the leaderboard sets (Group Health, Mount Sinai, etc.), can we have a table that lists the number of scored submissions per teams and display it on the wiki?

**Comment by thomasyu888** [comment]
https://www.synapse.org/#!Synapse:syn9935146/wiki/450007

**Comment by thomasyu888** [comment]
Is this place ok to put it? https://www.synapse.org/#!Synapse:syn9935146/wiki/450007
