### ISSUE TITLE
bm20 is not responding

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#878]
I've opened a ticket with the DST support.

**Comment by tschaffter** [comment]
I'll prepare a couple of backup machines for the participants.

**Comment by tschaffter** [comment]
@thomasyu888 bm03 and bm04 are two backup machines that you can use whenever required. One can be used to replace bm20, which is still being investigated by DST. On Hangout, you asked if bm21 was working fine. What hints do you have that it may not work properly? At least I can tell that I can connect to it and see both agents running.

**Comment by thomasyu888** [comment]
The participant says that his log file wasn't being updated, but it was.  Im telling him to submit to bm21 again to see.

**Comment by tschaffter** [comment]
DST has fixed the issue with the machine. I'm closing the ticket.

@thomasyu888 The machine started containers 5 days ago.

```
[root@bm20 ~]# docker ps
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS              PORTS               NAMES
e49b26aa0f6f        brucehoff/challengedockeragent                  "/usr/local/bin/mv..."   5 days ago          Up 5 days                               model-state-unlocker
1617f24b10f9        docker.synapse.org/syn5644795/nvml-cloudwatch   "/bin/sh -c 'pytho..."   5 days ago          Up 5 days                               nvml-cloudwatch
f699d23a56a0        brucehoff/challengedockeragent                  "/usr/local/bin/mv..."   5 days ago          Up 5 days                               bm20-train-and-score-2
c46f2f8942ea        brucehoff/challengedockeragent                  "/usr/local/bin/mv..."   5 days ago          Up 5 days                               bm20-train-and-score-1
```

What is exactly the tasks performed by the model unlocker?
