### ISSUE TITLE
Making Mount Sinai dataset visible to participants

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#879]
Hi @thomasyu888 and @brucehoff,

I have transferred the Mount Sinai *training* and *leaderboard* sets on the machines prepared for the participants (bm07 to bm23 - bm16, backup machines: bm03, bm04, bm06). Can you please make the dataset visible to the participants today if possible?

Here is configuration to mount the Docker volume for training submissions: `/data/data/mssm-split2/training:/dm_mountsinai`. Remember that all available training datasets are made visible to training submission. Therefore the above configuration must be *added* to the existing ones.

For inference submissions, you must create a new evaluation queue. For the name of the evaluation queue, please take the name of the Group Health submission queue and replace "Group Health" by "Mount Sinai". The images and metadata files must be mounted with the same target as done for the Group Health dataset.

- /data/data/mssm-split2/leaderboard/dcm/*.dcm
- /data/data/mssm-split2/leaderboard/metadata/images_crosswalk.tsv
- /data/data/mssm-split2/leaderboard/metadata/exams_metadata.tsv

I'll send you the link to the leaderboard goldstandard by email since this github repository is public.

Thanks!

**Comment by tschaffter** [comment]
Please test the evaluation submission queue with SC1 baseline method before opening the submission queue (not SC2 because exam metadata file is slightly different from group health, which I'll document on the wiki).

**Comment by thomasyu888** [comment]
Can you update this: https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/wiki/Install-Challenge-Dataset

**Comment by tschaffter** [comment]
Hi Tom, I said something gwrong in answer to your question in the chat. /trainedData is obviously not for inference. For training, you just have to mount the volume I specified above. For inference, the mounting points for images and metadata files are the same as for group health leaderboard. As you know, when submitting to group health leaderboard queue you mount group health leaderboard data and when a submission is sent to Mount Sinai leaderboard, you mount the Mount Sinai data but keep the same target volumes.

**Comment by thomasyu888** [comment]
So right now for inference the images are mounted at /sc1ScoringData and /sc2ScoringData.  Should they have different mount points?

**Comment by tschaffter** [comment]
There are no SC1-like data in the collaborative phase. Basically a participant should be able to submit the same inference method to the group health and mount sinai inference submission queues.

**Comment by thomasyu888** [comment]
Right, but Im more concerned about the mount mounts of the data.  Basically the script right now mounts 
/data/data/dm-challenge-dcm/SC2_leaderboard:/sc2ScoringData

and 
/data/data/mssm-split2/leaderboard/dcm:/sc1ScoringData

So participants will read in images from mt sinai by looking in sc1ScoringData.

**Comment by tschaffter** [comment]
> Basically the script right now mounts
/data/data/dm-challenge-dcm/SC2_leaderboard:/sc2ScoringData

This is not correct. In the competitive phase, images were mounted as `/inferenceData/*.dcm`.

https://www.synapse.org/#!Synapse:syn4224222/wiki/401759

The way you are mounting the files does not allow submissions from the competitive phase to run on the collaborative infrastructure, as requested in a previous thread.

**Comment by thomasyu888** [comment]
Nowhere in the script do I see the images being mounted as `/inferenceData/*.dcm`. Hmmm....

Furthermore, if this is the case, we will still run into the issue of having multiple datasets trying to mount to `/inferenceData`

**Comment by thomasyu888** [comment]
@brucehoff Have I been updating the wrong scripts: `dmagentprod.sh`?  Should I be running `run_inference.sh`?

**Comment by brucehoff** [comment]
@thomasyu888 you ask:
> Have I been updating the wrong scripts: dmagentprod.sh? Should I be running run_inference.sh?

The comments at the top of run_inference.sh say:

> # This script runs an inference submission on a challenge server directly.
# First use Docker Machine to 'point' the Docker client to the server daemon.

So the script is not related to the operation of the challenge submission queues.

**Comment by tschaffter** [comment]
@thomasyu888 Can you pleaee send an email to the collaborative Synapse group once the infrastructure is ready for the participants to use the Mount Sinai data?

**Comment by thomasyu888** [comment]
This is set up

**Comment by tschaffter** [comment]
Hi @thomasyu888,

Where do we stand regarding this ticket? You can then close it once it's done.

**Comment by thomasyu888** [comment]
Closed.

**Comment by tschaffter** [comment]
@thomasyu888 In response to one of you previous question, here is how the Mount Sinai training set must be mounted:

https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/wiki/Install-Challenge-Dataset

Can you confirm that the Mount Sinai training data are mounted as documented?

**Comment by tschaffter** [comment]
The Mount Sinai files needed to be updated:

- [x] Add columns *assessL* and *assessR* to the training exams metadata file
- [x] Add the column *examIndex* to all the images crosswalk files

The files have been deployed to all the collaborative and backup machines.

The dataset have been documented on the wiki:
https://www.synapse.org/#!Synapse:syn9935146/wiki/454581

**Comment by tschaffter** [comment]
The mount Sinai dataset need to be redeployed to the bmXX machines.

- [ ] bm01 (do not deploy; internal machine)
- [ ] bm02 (do not deploy; internal machine)
- [ ] bm03
- [ ] bm04
- [ ] bm05 (do not deploy; internal machine)
- [ ] bm06
- [ ] bm07
- [ ] bm08
- [ ] bm09
- [ ] bm10
- [ ] bm11
- [ ] bm12
- [ ] bm13
- [ ] bm14
- [ ] bm15
- [ ] bm16 (do not deploy; internal machine)
- [ ] bm17
- [ ] bm18
- [ ] bm19
- [ ] bm20
- [ ] bm21
- [ ] bm22
- [ ] bm23

**Comment by tschaffter** [comment]
@thomasyu888 The updated Mount Sinai dataset (training and leaderboard) has been deployed to all active + backup machines.

**Important:** When mounting the Mount Sinai dataset to the containers, replace `/data/data/mssm-split2` by `/data/data/mssm-split2-20170809`.

Can you please:

- [ ] Update the agents so that they mount the Mount Sinai dataset.
- [ ] Run SC2 baseline method on bm20.

**Comment by tschaffter** [comment]
The latest version of the Mount Sinai dataset has been updated on all the machines yesterday in coordination with Tom.
