### ISSUE TITLE
can not retrieve model state

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#891]
https://www.synapse.org/#!Synapse:syn9935146/discussion/threadId=2290

**Comment by tschaffter** [comment]
@brucehoff Is this something you can look at while Tom is on vacation?

**Comment by brucehoff** [comment]
Reset the state of the email to retrigger processing:
```
synRestPUT("/message/status", list(recipientId="3351415", status="UNREAD", messageId="171467"))
```
Model state file is now unlocked.
