### ISSUE TITLE
Double-check scoring scripts on Synapse

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#892]
Deszo is saying that breast-level evaluation on the Mount Sinai dataset is 9% lower than in his cross-validation on the training set, while exam-level predictions on Mount Sinai are consistent with his observations from cross-validation.

@thomasyu888 Can you confirm that the same code is used to score all datasets with only a small variant for scoring exam-level predictions from breast-level gold standard? I can't check right now but assuming Group Health gold standard list all L first then R and Mount Sinai gold standard lists Nx {L,R}, are all gold standards read correctly?

**Comment by thomasyu888** [comment]
Yes. they are all read in correctly.  I checked as well.
