### ISSUE TITLE
Add running time for the current job in human-readable format (hh:mm)

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#9]
In the dashboard of the participant, show the current runtime in human-readable format (hh:mm) next to a given submission.

**Comment by brucehoff** [comment]
We will add the 'Submitted On' time stamp and the 'Time Remaining'.  Not sure why this is needed.

**Comment by tschaffter** [comment]
Is the remaining time now shown to the participants?

**Comment by brucehoff** [comment]
> @brucehoff Is the remaining time now shown to the participants?
It will be shortly.
